### ISSUE TITLE
Seagate Ironwolf ST4000NE0025 is not in smartd database

### ISSUE THREAD

**Issue by stratege1401** [smartmontools/smartmontools#10]
Seem the new Seagate Ironwolf is not in smartd database.
Wonder if this might cause smatmontools reading error ?

`smartd[519]: Device: /dev/sde, type changed from 'scsi' to 'sat'
smartd[519]: Device: /dev/sde [SAT], opened
smartd[519]: Device: /dev/sde [SAT], ST4000NE0025-2EW107, S/N:redacted, WWN:5-000c50-0af6717a5,                     FW:EN02, 4.00 TB
smartd[519]: Device: /dev/sde [SAT], not found in smartd database.
`

**Comment by chrfranke** [comment]
This only affects attribute naming and raw value print format.  For HDDs the defaults are sufficient in most cases. Please provide sample `smartctl -x` output of this device.

**Comment by chrfranke** [comment]
Added in r4868, r4869 and included in smartmontools 7.0.
