### ISSUE TITLE
Intel SSD behind LSI MegaRAID adapter shows failed via "smartctl" command - continuation of #98

### ISSUE THREAD

**Issue by MrPippin66** [smartmontools/smartmontools#101]
Environment: RHEL V7.8

smartmontools = smartmontools-7.0-2.el7.x86_64

smartctl = 7.0 2018-12-30 r4883

This is actually a continuation of #98, and I have a question, since I'm working with Lenovo hardware support (firmware) on this issue.

I see in the LSI (megaraid) code, there is actually a hard coded filter for this command.

`  if (iop->cmnd[0] == SAT_ATA_PASSTHROUGH_12 || iop->cmnd[0] == SAT_ATA_PASSTHROUGH_16) { 
    // Controller does not return ATA output registers in SAT sense data
    if (iop->cmnd[2] & (1 << 5)) // chk_cond
      return set_err(ENOSYS, "ATA return descriptor not supported by controller firmware");
  }`
  
I'm not sure if this is still valid, considering I see there was a firmware fix that may address this (I have no details other than the change title and description).
  
**Smart Return Status passthru command failed on SATA drives.(SCGCQ01802574 port of SCGCQ01802574)**

With the code block above, this simply is hard coded to fail on megaraid controllers as shown.

Would it be appropriate to see if this firmware issue still exists, and this code block may not be required? Or is regardless, the change you did in reference to #98 still your official resolution to this?

**Comment by chrfranke** [comment]
IIRC this limitation was added to the `-d megaraid,N` specific code because of some reports about critical errors (device hangs or disconnects) after issuing SAT_ATA_PASSTHROUGH_XX with CK_COND bit set.

If possible, please build a custom version of smartctl without this filter and report the test result here. Don't test on a production system.

**Comment by MrPippin66** [comment]
Hmmm, possibly not.

smartctl -r ioctl,2 -H /dev/bus/0 -d megaraid,0

For the relevant smart check results:

=== START OF READ SMART DATA SECTION ===

REPORT-IOCTL: Device=/dev/bus/0 Command=SMART STATUS CHECK
 Input:   FR=0xda, SC=...., LL=...., LM=0x4f, LH=0xc2, DEV=...., CMD=0xb0
 [ata pass-through(16): 85 06 2c 00 da 00 00 00 00 00 4f 00 c2 00 b0 00 ]
sat_device::ata_pass_through: scsi_pass_through() failed, errno=5 [megasas_cmd result: 0.0 = 0/45]
 [Duration: 0.000461s]
REPORT-IOCTL: Device=/dev/bus/0 Command=SMART STATUS CHECK returned -1 errno=5 [megasas_cmd result: 0.0 = 0/45]
SMART Status command failed: megasas_cmd result: 0.0 = 0/45
SMART overall-health self-assessment test result: PASSED
Warning: This result is based on an Attribute check.


Nothing from megaraid driver in dmesg.

**Comment by chrfranke** [comment]
> SMART Status command failed: megasas_cmd result: 0.0 = 0/45

A MegaRAID driver/firmware expert may know the meaning of the `cmd_status = 45` code returned by the `MEGASAS_IOC_FIRMWARE` I/O-control.

Conclusion: Possibly more sane behavior than in the past, but the SAT layer is still incomplete/buggy. The pass-through of ATA SMART RETURN STATUS is still not supported.
