### ISSUE TITLE
Silent Installation

### ISSUE THREAD

**Issue by Dozentz** [smartmontools/smartmontools#106]
Tell me how to install program via  .bat

**Comment by chrfranke** [comment]
Silent install:
```
smartmontools-VERSION-win32-setup.exe /S
```
Show a dialog with further options:
```
smartmontools-VERSION-win32-setup.exe /SO
```
You could also unpack files from the installer with a 7-Zip CLI. Note that `smartctl.exe` is self-contained and does not require an actual installation.
