### ISSUE TITLE
update-smart-drivedb: add a --quiet switch

### ISSUE THREAD

**Issue by sbraz** [smartmontools/smartmontools#110]
Hello,
Would it please be possible to suppress output from the script via a switch so that it doesn't trigger a cron email on success? For now, redirecting the output of the crontab to `/dev/null` works but this is not ideal.

**Comment by chrfranke** [comment]
Added `-q` in [r5242](https://www.smartmontools.org/changeset/5242) (56363df). Please test if possible.

**Comment by sbraz** [comment]
Hi @chrfranke, that works perfectly, thanks! I've backported it for our Gentoo package in https://github.com/gentoo/gentoo/commit/55ea66e73da3b7d76f05bc512d4b01bf4802155a.
