### ISSUE TITLE
Unable to monitor megaraid_sas in smartd when run with --capabilities

### ISSUE THREAD

**Issue by speachy** [smartmontools/smartmontools#113]
If I invoke smartctl on the command line, I am able to query SMART data.  This works, for example:

   $ sudo smartctl -a -d megaraid,21  /dev/sda

However, if I place this in the smartd.conf:

  /dev/sda -a -d megaraid,21

And launch it manually in debug mode:

   sudo /usr/sbin/smartd -n -q never --capabilities -d

It fails to work, resulting in this error:

  Device: /dev/sda, not available
  Device: /dev/sda [megaraid_disk_21], open() failed: cannot open /dev/megaraid_sas_ioctl_node or /dev/megadev0

It seems that smartd is dropping capabilities before it tries to open the megaraid device node.  Getting rid of the --capabilities (default config under Fedora, at least) allows it to work.

I'm using smartmontools 7.2 as provided by Fedora 34:

  smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.14.11-200.fc34.x86_64] (local build)

With Fedora 34's 5.4.11-200 kernel with a MegaRAID SAS controller:

  $ lspci -v |grep SAS
  01:00.0 RAID bus controller: Broadcom / LSI MegaRAID SAS 2208 [Thunderbolt] (rev 05)

On one hand this is a problem with Fedora's default config, however it does seem to me that this is still an upstream smartd issue, and even if not practical to fix it should at least be documented in the FAQ or Help pages.

Thanks!

**Comment by chrfranke** [comment]
The maintainer of the RHEL/Fedora smartmontools package found the root of the problem: Nodes created with mknod() have no permission bits set. Then even root needs CAP_DAC_OVERRIDE which is not available if `--capabilites` is used.

**Comment by iavael** [comment]
Fix doesn't work for me in latest release

**Comment by chrfranke** [comment]
> Fix doesn't work for me in latest release

Please provide more details (distribution, package version, `smartd -q onecheck` output, smartd command line parameters, `smartd.conf` file, does it work with `--capabilities=mail` ?, ...).
