### ISSUE TITLE
The life time in log of selftest is wrong

### ISSUE THREAD

**Issue by k79e** [smartmontools/smartmontools#118]
For a same disk.

```
When using -l selftest it shows this.
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA
_of_first_error
...
# 5  Short offline       Completed without error       00%       105         -
# 6  Short offline       Completed without error       00%       166         -

But in -x the time is different and is correct.
...
# 5  Short offline       Completed without error       00%       617         -
# 6  Short offline       Completed without error       00%       422         -
```

**Comment by chrfranke** [comment]
The truncated output above is not sufficient to diagnose this issue.
Please provide output of `smartctl -a -x ...` (both options in one command) as an attachment. Add option `-q noserial` if desired.

**Comment by k79e** [comment]
Here it is 

`smartctl 7.2 2020-12-30 r5155 [x86_64-w64-mingw32-win7-sp1] (sf-7.2-1)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     PLEXTOR PX-512M8VC +
Firmware Version: 1.00
User Capacity:    512,110,190,592 bytes [512 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Form Factor:      2.5 inches
TRIM Command:     Available, deterministic, zeroed
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ACS-2 (minor revision not indicated)
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Sun Nov 21 23:11:31 2021 
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
AAM feature is:   Unavailable
APM feature is:   Unavailable
Rd look-ahead is: Enabled
Write cache is:   Enabled
DSN feature is:   Unavailable
ATA Security is:  Disabled, frozen [SEC2]
Wt Cache Reorder: Unknown

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x02)	Offline data collection activity
					was completed without error.
					Auto Offline Data Collection: Disabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(    2) seconds.
Offline data collection
capabilities: 			 (0x11) SMART execute Offline immediate.
					No Auto Offline data collection support.
					Suspend Offline collection upon new
					command.
					No Offline surface scan supported.
					Self-test supported.
					No Conveyance Self-test supported.
					No Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   1) minutes.
Extended self-test routine
recommended polling time: 	 (  10) minutes.
SCT capabilities: 	       (0x003d)	SCT Status supported.
					SCT Error Recovery Control supported.
					SCT Feature Control supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 1
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
  1 Raw_Read_Error_Rate     POSR-K   100   100   000    -    0
  5 Reallocated_Sector_Ct   PO----   100   100   000    -    0
  9 Power_On_Hours          -O----   100   100   000    -    1202
 12 Power_Cycle_Count       PO----   100   100   000    -    84
170 Unknown_Attribute       -O--CK   100   100   000    -    0
171 Unknown_Attribute       PO----   100   100   000    -    0
172 Unknown_Attribute       PO----   100   100   000    -    0
173 Unknown_Attribute       PO----   100   100   000    -    2
174 Unknown_Attribute       PO----   100   100   000    -    2
175 Program_Fail_Count_Chip PO----   100   100   000    -    0
176 Erase_Fail_Count_Chip   PO----   100   100   000    -    0
178 Used_Rsvd_Blk_Cnt_Chip  PO----   100   100   000    -    0
179 Used_Rsvd_Blk_Cnt_Tot   PO----   100   100   000    -    0
180 Unused_Rsvd_Blk_Cnt_Tot PO--CK   100   100   005    -    130
181 Program_Fail_Cnt_Total  PO----   100   100   000    -    0
182 Erase_Fail_Count_Total  PO----   100   100   000    -    0
183 Runtime_Bad_Block       -O--CK   100   100   000    -    0
194 Temperature_Celsius     -O----   100   100   000    -    25
195 Hardware_ECC_Recovered  PO----   100   100   000    -    0
199 UDMA_CRC_Error_Count    PO----   100   100   000    -    0
232 Available_Reservd_Space PO----   100   100   010    -    100
233 Media_Wearout_Indicator PO----   100   100   000    -    1366
241 Total_LBAs_Written      PO----   100   100   000    -    15414
242 Total_LBAs_Read         PO----   100   100   000    -    41333
                            ||||||_ K auto-keep
                            |||||__ C event count
                            ||||___ R error rate
                            |||____ S speed/performance
                            ||_____ O updated online
                            |______ P prefailure warning

General Purpose Log Directory Version 1
SMART           Log Directory Version 1 [multi-sector log support]
Address    Access  R/W   Size  Description
0x00       GPL,SL  R/O      1  Log Directory
0x01       GPL,SL  R/O      1  Summary SMART error log
0x02       GPL,SL  R/O      1  Comprehensive SMART error log
0x03       GPL,SL  R/O      1  Ext. Comprehensive SMART error log
0x04       GPL,SL  R/O      8  Device Statistics log
0x06       GPL,SL  R/O      1  SMART self-test log
0x07       GPL,SL  R/O      1  Extended self-test log
0x09       GPL,SL  R/W      1  Selective self-test log
0x10       GPL,SL  R/O      1  NCQ Command Error log
0x11       GPL,SL  R/O      1  SATA Phy Event Counters log
0x30       GPL,SL  R/O      9  IDENTIFY DEVICE data log
0x80-0x9f  GPL,SL  R/W     16  Host vendor specific log
0xe0       GPL,SL  R/W      1  SCT Command/Status
0xe1       GPL,SL  R/W      1  SCT Data Transfer

SMART Extended Comprehensive Error Log Version: 1 (1 sectors)
No Errors Logged

SMART Error Log Version: 1
No Errors Logged

SMART Extended Self-test Log Version: 1 (1 sectors)
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%      1191         -
# 2  Short offline       Completed without error       00%      1107         -
# 3  Short offline       Completed without error       00%       941         -
# 4  Short offline       Completed without error       00%       879         -
# 5  Short offline       Completed without error       00%       617         -
# 6  Short offline       Completed without error       00%       422         -
# 7  Short offline       Completed without error       00%        26         -

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%       167         -
# 2  Short offline       Completed without error       00%        83         -
# 3  Short offline       Completed without error       00%       173         -
# 4  Short offline       Completed without error       00%       111         -
# 5  Short offline       Completed without error       00%       105         -
# 6  Short offline       Completed without error       00%       166         -
# 7  Short offline       Completed without error       00%        26         -

Selective Self-tests/Logging not supported

SCT Status Version:                  3
SCT Version (vendor specific):       0 (0x0000)
Device State:                        Active (0)
Current Temperature:                    22 Celsius
Power Cycle Min/Max Temperature:     12/12 Celsius
Lifetime    Min/Max Temperature:      0/36 Celsius
Under/Over Temperature Limit Count:   0/0

SCT Temperature History Version:     2
Temperature Sampling Period:         0 minutes
Temperature Logging Interval:        0 minutes
Min/Max recommended Temperature:      0/100 Celsius
Min/Max Temperature Limit:            0/100 Celsius
Temperature History Size (Index):    128 (85)

Index    Estimated Time   Temperature Celsius
  86    2021-11-21 21:04     0  -
 ...    ..(126 skipped).    ..  -
  85    2021-11-21 23:11     0  -

SCT Error Recovery Control:
           Read: Disabled
          Write: Disabled

Device Statistics (GP Log 0x04)
Page  Offset Size        Value Flags Description
0x01  =====  =               =  ===  == General Statistics (rev 1) ==
0x01  0x008  4              84  ---  Lifetime Power-On Resets
0x01  0x010  4            1202  ---  Power-on Hours
0x01  0x018  6      1010191907  ---  Logical Sectors Written
0x01  0x020  6        27720087  ---  Number of Write Commands
0x01  0x028  6      2708845564  ---  Logical Sectors Read
0x01  0x030  6        41207109  ---  Number of Read Commands
0x04  =====  =               =  ===  == General Errors Statistics (rev 1) ==
0x04  0x008  4               0  ---  Number of Reported Uncorrectable Errors
0x04  0x010  4               2  ---  Resets Between Cmd Acceptance and Completion
0x05  =====  =               =  ===  == Temperature Statistics (rev 1) ==
0x05  0x008  1              22  ---  Current Temperature
0x05  0x020  1              12  ---  Highest Temperature
0x05  0x028  1              12  ---  Lowest Temperature
0x05  0x038  1              85  ---  Lowest Average Short Term Temperature
0x05  0x058  1             100  ---  Specified Maximum Operating Temperature
0x06  =====  =               =  ===  == Transport Statistics (rev 1) ==
0x06  0x008  4             179  ---  Number of Hardware Resets
0x06  0x010  4               0  ---  Number of ASR Events
0x06  0x018  4               0  ---  Number of Interface CRC Errors
0x07  =====  =               =  ===  == Solid State Device Statistics (rev 1) ==
0x07  0x008  1               0  ---  Percentage Used Endurance Indicator
                                |||_ C monitored condition met
                                ||__ D supports DSN
                                |___ N normalized value

Pending Defects log (GP Log 0x0c) not supported

SATA Phy Event Counters (GP Log 0x11)
ID      Size     Value  Description
0x0001  2            0  Command failed due to ICRC error
0x0002  2            0  R_ERR response for data FIS
0x0003  2            0  R_ERR response for device-to-host data FIS
0x0004  2            0  R_ERR response for host-to-device data FIS
0x0005  2            0  R_ERR response for non-data FIS
0x0006  2            0  R_ERR response for device-to-host non-data FIS
0x0007  2            0  R_ERR response for host-to-device non-data FIS
0x0008  2            0  Device-to-host non-data FIS retries
0x0009  2            0  Transition from drive PhyRdy to drive PhyNRdy
0x000a  2            1  Device-to-host register FISes sent due to a COMRESET
0x000b  2            0  CRC errors within host-to-device FIS
0x000d  2            0  Non-CRC errors within host-to-device FIS
0x000f  2            0  R_ERR response for host-to-device data FIS, CRC
0x0010  2            0  R_ERR response for host-to-device data FIS, non-CRC
0x0012  2            0  R_ERR response for host-to-device non-data FIS, CRC
0x0013  2            0  R_ERR response for host-to-device non-data FIS, non-CRC

`

**Comment by chrfranke** [comment]
```
SMART Extended Self-test Log Version: 1 (1 sectors)
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%      1191         -
# 2  Short offline       Completed without error       00%      1107         -
# 3  Short offline       Completed without error       00%       941         -
# 4  Short offline       Completed without error       00%       879         -
# 5  Short offline       Completed without error       00%       617         -
# 6  Short offline       Completed without error       00%       422         -
# 7  Short offline       Completed without error       00%        26         -

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%       167         -
# 2  Short offline       Completed without error       00%        83         -
# 3  Short offline       Completed without error       00%       173         -
# 4  Short offline       Completed without error       00%       111         -
# 5  Short offline       Completed without error       00%       105         -
# 6  Short offline       Completed without error       00%       166         -
# 7  Short offline       Completed without error       00%        26         -
```

(1191 & 0xff) = 167, (1107 & 0xff) = 83, ..., (422 & 0xff) = 166, (26 & 0xff) = 26.

This suggests that the drive firmware truncates the 16-bit life time value to 8 bit in the legacy SMART self-test log. This is a (possibly harmless) drive firmware bug.

Smartctl should print this log correctly as outputs for many other devices show.
If not convinced, please provide output of `smartctl -r ioctl,2 -l selftest ...`, otherwise close this issue.

**Comment by k79e** [comment]
But I don't see the output for 0x0269=617h in the output of the commend.
smartctl -r ioctl,2 -l selftest /dev/sdc|grep -i "69"
160-175: f0 03 00 00 6b 74 01 7d 63 41 **69** 74 01 bc 63 41 |....kt.}cAit..cA|
048-063: 00 00 01 00 **69** 00 00 00 00 00 00 00 00 00 00 00 |....i...........|


```
smartctl 7.2 2020-12-30 r5155 [x86_64-w64-mingw32-win7-sp1] (sf-7.2-1)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

 \\.\PhysicalDrive2: successfully opened
  IOCTL_STORAGE_QUERY_PROPERTY returns:
    Vendor:   "PLEXTOR "
    Product:  "PX-512M8VC +"
    Revision: "1.00"
    Removable: No
    BusType:   0x0b
\\.\PhysicalDrive2: successfully opened

REPORT-IOCTL: Device=/dev/sdc Command=IDENTIFY DEVICE
 Input:   FR=...., SC=0x01, LL=...., LM=...., LH=...., DEV=...., CMD=0xec IN
  IOCTL_ATA_PASS_THROUGH succeeded, bytes returned: 564
    Input : CMD=0xec, FR=0x00, SC=0x01, SN=0x00, CL=0x00, CH=0x00, SEL=0x00
    Output: STS=0x50,ERR=0x00, SC=0x01, SN=0x00, CL=0x00, CH=0x00, SEL=0x00
 [Duration: 0.002s]
 Output: ERR=0x00, SC=0x01, LL=0x00, LM=0x00, LH=0x00, DEV=0x00, STS=0x50
REPORT-IOCTL: Device=/dev/sdc Command=IDENTIFY DEVICE returned 0

===== [IDENTIFY DEVICE] DATA START (BASE-16) =====
000-015: 40 00 ff 3f 37 c8 10 00 00 00 00 00 3f 00 00 00 |@..?7.......?...|
016-031: 00 00 00 00 30 50 31 32 36 31 30 34 34 30 33 35 |....0P1261044035|
032-047: 20 20 20 20 20 20 20 20 00 00 00 00 00 00 2e 31 |        .......1|
048-063: 30 30 20 20 20 20 4c 50 58 45 4f 54 20 52 58 50 |00    LPXEOT RXP|
064-079: 35 2d 32 31 38 4d 43 56 2b 20 20 20 20 20 20 20 |5-218MCV+       |
080-095: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 02 80 |              ..|
096-111: 00 40 00 2f 00 40 00 00 00 00 07 00 ff 3f 10 00 |.@./.@.......?..|
112-127: 3f 00 10 fc fb 00 02 01 ff ff ff 0f 00 00 07 00 |?...............|
128-143: 03 00 78 00 78 00 78 00 78 00 20 4d 00 00 00 00 |..x.x.x.x. M....|
144-159: 00 00 00 00 00 00 1f 00 0e 07 06 00 4c 00 4c 00 |............L.L.|
160-175: f0 03 00 00 6b 74 01 7d 63 41 69 74 01 bc 63 41 |....kt.}cAit..cA|
176-191: 7f 40 02 00 02 00 00 00 fe ff 00 00 00 00 00 00 |.@..............|
192-207: 00 00 00 00 00 00 00 00 b0 12 9e 3b 00 00 00 00 |...........;....|
208-223: 00 00 08 00 00 40 00 00 8f 53 16 60 2f 10 9a 71 |.....@...S.`/..q|
224-239: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 1c 40 |...............@|
240-255: 1c 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |.@..............|
256-271: 29 00 01 00 01 01 00 00 00 ec 00 00 00 00 00 00 |)...............|
272-287: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
288-303: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
304-319: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
320-335: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
336-351: 03 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
352-367: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
368-383: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
384-399: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
400-415: 00 00 00 00 00 00 00 00 00 00 00 00 3d 00 00 00 |............=...|
416-431: 00 00 00 40 00 00 00 00 00 00 00 00 00 00 00 00 |...@............|
432-447: 00 00 01 00 00 00 00 00 00 00 00 00 7f 10 00 00 |................|
448-463: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
464-479: 00 00 00 00 01 00 00 02 00 00 00 00 00 00 00 00 |................|
480-495: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
496-511: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 a5 d3 |................|
===== [IDENTIFY DEVICE] DATA END (512 Bytes) =====


REPORT-IOCTL: Device=/dev/sdc Command=SMART READ ATTRIBUTE VALUES
 Input:   FR=0xd0, SC=0x01, LL=...., LM=0x4f, LH=0xc2, DEV=...., CMD=0xb0 IN
  IOCTL_ATA_PASS_THROUGH succeeded, bytes returned: 564
    Input : CMD=0xb0, FR=0xd0, SC=0x01, SN=0x00, CL=0x4f, CH=0xc2, SEL=0x00
    Output: STS=0x50,ERR=0x00, SC=0x01, SN=0x00, CL=0x4f, CH=0xc2, SEL=0x00
 [Duration: 0.001s]
 Output: ERR=0x00, SC=0x01, LL=0x00, LM=0x4f, LH=0xc2, DEV=0x00, STS=0x50
REPORT-IOCTL: Device=/dev/sdc Command=SMART READ ATTRIBUTE VALUES returned 0

===== [SMART READ ATTRIBUTE VALUES] DATA START (BASE-16) =====
000-015: 01 00 01 2f 00 64 64 00 00 00 00 00 00 00 05 03 |.../.dd.........|
016-031: 00 64 64 00 00 00 00 00 00 00 09 02 00 64 64 b9 |.dd..........dd.|
032-047: 04 00 00 00 00 00 0c 03 00 64 64 55 00 00 00 00 |.........ddU....|
048-063: 00 00 aa 32 00 64 64 00 00 00 00 00 00 00 ab 03 |...2.dd.........|
064-079: 00 64 64 00 00 00 00 00 00 00 ac 03 00 64 64 00 |.dd..........dd.|
080-095: 00 00 00 00 00 00 ad 03 00 64 64 02 00 00 00 00 |.........dd.....|
096-111: 00 00 ae 03 00 64 64 02 00 00 00 00 00 00 af 03 |.....dd.........|
112-127: 00 64 64 00 00 00 00 00 00 00 b0 03 00 64 64 00 |.dd..........dd.|
128-143: 00 00 00 00 00 00 b2 03 00 64 64 00 00 00 00 00 |.........dd.....|
144-159: 00 00 b3 03 00 64 64 00 00 00 00 00 00 00 b4 33 |.....dd........3|
160-175: 00 64 64 82 00 00 00 00 00 00 b5 03 00 64 64 00 |.dd..........dd.|
176-191: 00 00 00 00 00 00 b6 03 00 64 64 00 00 00 00 00 |.........dd.....|
192-207: 00 00 b7 32 00 64 64 00 00 00 00 00 00 00 c2 02 |...2.dd.........|
208-223: 00 64 64 19 00 00 00 00 00 00 c3 03 00 64 64 00 |.dd..........dd.|
224-239: 00 00 00 00 00 00 c7 03 00 64 64 00 00 00 00 00 |.........dd.....|
240-255: 00 00 e8 03 00 64 64 64 00 00 00 00 00 00 e9 03 |.....ddd........|
256-271: 00 64 64 66 05 00 00 00 00 00 f1 03 00 64 64 a3 |.ddf.........dd.|
272-287: 3c 00 00 00 00 00 f2 03 00 64 64 d9 a1 00 00 00 |<........dd.....|
288-303: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
304-319: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
320-335: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
336-351: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
352-367: 00 00 00 00 00 00 00 00 00 00 02 00 02 00 00 11 |................|
368-383: 03 00 01 00 01 0a 00 00 00 00 00 00 00 00 00 00 |................|
384-399: 00 00 31 2e 30 30 20 20 20 20 00 00 00 00 00 00 |..1.00    ......|
400-415: 53 4d 32 32 35 38 00 00 00 00 00 00 00 00 00 00 |SM2258..........|
416-431: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
432-447: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
448-463: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
464-479: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
480-495: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
496-511: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 81 |................|
===== [SMART READ ATTRIBUTE VALUES] DATA END (512 Bytes) =====

=== START OF READ SMART DATA SECTION ===

REPORT-IOCTL: Device=/dev/sdc Command=SMART READ LOG InputParameter=0
 Input:   FR=0xd5, SC=0x01, LL=0x00, LM=0x4f, LH=0xc2, DEV=...., CMD=0xb0 IN
  IOCTL_ATA_PASS_THROUGH succeeded, bytes returned: 564
    Input : CMD=0xb0, FR=0xd5, SC=0x01, SN=0x00, CL=0x4f, CH=0xc2, SEL=0x00
    Output: STS=0x50,ERR=0x00, SC=0x01, SN=0x00, CL=0x4f, CH=0xc2, SEL=0x00
 Output: ERR=0x00, SC=0x01, LL=0x00, LM=0x4f, LH=0xc2, DEV=0x00, STS=0x50
REPORT-IOCTL: Device=/dev/sdc Command=SMART READ LOG returned 0

===== [SMART READ LOG] DATA START (BASE-16) =====
000-015: 01 00 01 00 01 00 01 00 08 00 00 00 01 00 01 00 |................|
016-031: 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
032-047: 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
048-063: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
064-079: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
080-095: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
096-111: 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
112-127: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
128-143: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
144-159: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
160-175: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
176-191: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
192-207: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
208-223: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
224-239: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
240-255: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
256-271: 10 00 10 00 10 00 10 00 10 00 10 00 10 00 10 00 |................|
272-287: 10 00 10 00 10 00 10 00 10 00 10 00 10 00 10 00 |................|
288-303: 10 00 10 00 10 00 10 00 10 00 10 00 10 00 10 00 |................|
304-319: 10 00 10 00 10 00 10 00 10 00 10 00 10 00 10 00 |................|
320-335: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
336-351: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
352-367: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
368-383: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
384-399: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
400-415: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
416-431: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
432-447: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
448-463: 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
464-479: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
480-495: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
496-511: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
===== [SMART READ LOG] DATA END (512 Bytes) =====


REPORT-IOCTL: Device=/dev/sdc Command=SMART READ LOG InputParameter=6
 Input:   FR=0xd5, SC=0x01, LL=0x06, LM=0x4f, LH=0xc2, DEV=...., CMD=0xb0 IN
  IOCTL_ATA_PASS_THROUGH succeeded, bytes returned: 564
    Input : CMD=0xb0, FR=0xd5, SC=0x01, SN=0x06, CL=0x4f, CH=0xc2, SEL=0x00
    Output: STS=0x50,ERR=0x00, SC=0x01, SN=0x06, CL=0x4f, CH=0xc2, SEL=0x00
 [Duration: 0.001s]
 Output: ERR=0x00, SC=0x01, LL=0x06, LM=0x4f, LH=0xc2, DEV=0x00, STS=0x50
REPORT-IOCTL: Device=/dev/sdc Command=SMART READ LOG returned 0

===== [SMART READ LOG] DATA START (BASE-16) =====
000-015: 01 00 01 00 1a 00 00 00 00 00 00 00 00 00 00 00 |................|
016-031: 00 00 00 00 00 00 00 00 00 00 01 00 a6 00 00 00 |................|
032-047: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
048-063: 00 00 01 00 69 00 00 00 00 00 00 00 00 00 00 00 |....i...........|
064-079: 00 00 00 00 00 00 00 00 00 00 01 00 6f 00 00 00 |............o...|
080-095: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
096-111: 00 00 01 00 ad 00 00 00 00 00 00 00 00 00 00 00 |................|
112-127: 00 00 00 00 00 00 00 00 00 00 01 00 53 00 00 00 |............S...|
128-143: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
144-159: 00 00 01 00 a7 00 00 00 00 00 00 00 00 00 00 00 |................|
160-175: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
176-191: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
192-207: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
208-223: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
224-239: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
240-255: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
256-271: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
272-287: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
288-303: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
304-319: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
320-335: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
336-351: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
352-367: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
368-383: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
384-399: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
400-415: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
416-431: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
432-447: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
448-463: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
464-479: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
480-495: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
496-511: 00 00 00 00 00 00 00 00 00 00 00 00 07 00 00 b2 |................|
===== [SMART READ LOG] DATA END (512 Bytes) =====

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%       167         -
# 2  Short offline       Completed without error       00%        83         -
# 3  Short offline       Completed without error       00%       173         -
# 4  Short offline       Completed without error       00%       111         -
# 5  Short offline       Completed without error       00%       105         -
# 6  Short offline       Completed without error       00%       166         -
# 7  Short offline       Completed without error       00%        26         -
```

**Comment by chrfranke** [comment]
> But I don't see the output for 0x0269=617h in the output of the commend. 

Of course, as `-l selftest` only reads the legacy SMART self-test log which is affected by the firmware bug.

```
REPORT-IOCTL: Device=/dev/sdc Command=SMART READ LOG InputParameter=6
...
===== [SMART READ LOG] DATA START (BASE-16) =====
000-015: 01 00 01 00 1a 00 00 00 00 00 00 00 00 00 00 00 |................|
                     ^^-^^--------------------------- #7 Life time 0x001a = 26
         ^^-^^--- Revision 1
016-031: 00 00 00 00 00 00 00 00 00 00 01 00 a6 00 00 00 |................|
                                             ^^-^^--- #6 Life time 0x00a6 = 166
032-047: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
048-063: 00 00 01 00 69 00 00 00 00 00 00 00 00 00 00 00 |....i...........|
                     ^^-^^--------------------------- #5 Life time 0x0069 = 105
064-079: 00 00 00 00 00 00 00 00 00 00 01 00 6f 00 00 00 |............o...|
                                             ^^-^^--- #4 Life time 0x006f = 111
080-095: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
096-111: 00 00 01 00 ad 00 00 00 00 00 00 00 00 00 00 00 |................|
                     ^^-^^--------------------------- #3 Life time 0x00ad = 173
112-127: 00 00 00 00 00 00 00 00 00 00 01 00 53 00 00 00 |............S...|
                                             ^^-^^--- #2 Life time 0x0053 = 83
128-143: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
144-159: 00 00 01 00 a7 00 00 00 00 00 00 00 00 00 00 00 |................|
                     ^^-^^--------------------------- #1 Life time 0x00a7 = 167
160-175: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
...
496-511: 00 00 00 00 00 00 00 00 00 00 00 00 07 00 00 b2 |................|
                                                      ^^--- Checksum
                                             ^^--- Index of most recent entry in ring buffer
````
Conclusion: The drive firmware never sets the upper byte of this field.

This is a firmware bug. Cannot be fixed by smartctl.
