### ISSUE TITLE
Support for Samsung EVO 970 NVME SSD

### ISSUE THREAD

**Issue by gwtuser** [smartmontools/smartmontools#12]
On Windows 7 SP1 x64, with the Samsung-supplied secnvmeF.sys driver installed (rather than the hotfix driver stornvme.sys from Microsoft), both CrystalDiskInfo 7.6.0 and DiskCheckup v3.4 are able to get the "Raw Value" of many SMART attributes from the Samsung EVO 970 NVME SSD, though they're not able to pull up the "Current/Worst/Threshold" values as they do for the EVO 850 2.5" SATA SSD.

However, smartctl.exe fails to show any information for this drive, and reports an error, though it works for the EVO 850 (run from an elevated command prompt):

> c:\cygwin\usr\sbin>smartctl.exe -d nvme -a /dev/sdc
> smartctl 6.6 2017-11-05 r4594 [i686-pc-cygwin-win7(64)-sp1] (cygwin-6.6-1)
> Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org
> 
> Read NVMe Identify Controller failed: IOCTL_STORAGE_QUERY_PROPERTY(NVMe) failed, Error=1

Can support be added for the Samsung NVME driver so that the call above will return info?
Driver here: https://www.samsung.com/semiconductor/minisite/ssd/download/tools/

**Comment by gmiranda** [comment]
Same issue with a WD Black nvme (2018) drive using the Windows 7 hotfix driver, but I would say the driver is the culprit:
```
smartctl 6.7 2018-06-21 r4735 [i686-w64-mingw32-win7(64)-sp1] (daily-20180621)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

Read NVMe Identify Controller failed: IOCTL_STORAGE_QUERY_PROPERTY(NVMe) failed, Error=1
```

**Comment by chrfranke** [comment]
> On Windows 7 SP1 x64, with the Samsung-supplied secnvmeF.sys driver installed ...

Samsung drivers should support NVME_PASS_THROUGH, try 'smartctl -d nvme --scan' to see valid /dev/nvme* pseudo device names. Sample output here was done with some Samsung NVMe driver:
https://www.smartmontools.org/wiki/NVMe_Support

> Same issue with a WD Black nvme (2018) drive using the Windows 7 hotfix driver ...

Same issue, different story: Unfortunately MS never implemented NVME_PASS_THROUGH in stornvme.sys. Windows 10 driver versions provide limited pass-through support via IOCTL_STORAGE_QUERY_PROPERTY, but versions for older Windows releases don't.

**Comment by gwtuser** [comment]
Thanks, that seems to work:
> c:\cygwin\usr\sbin>smartctl -d nvme --scan
> /dev/sdc -d nvme # /dev/sdc, NVMe device
> /dev/nvme0 -d nvme # /dev/nvme0, NVMe device

The first device listed is the one that I originally reported as yielding the error, so I tried the second:

> c:\cygwin\usr\sbin>smartctl.exe -d nvme -a /dev/nvme0
> smartctl 6.6 2017-11-05 r4594 [i686-pc-cygwin-win7(64)-sp1] (cygwin-6.6-1)
> Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org
> 
> === START OF INFORMATION SECTION ===
> Model Number:                       Samsung SSD 970 EVO 500GB
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  :
