### ISSUE TITLE
Smartctl should have a single command that activates && or || based on self-test result

### ISSUE THREAD

**Issue by Callistemon** [smartmontools/smartmontools#124]
Currently, <smartctl -a> can be used to display self-test results, but the information fetching process completes successfully even when the self-test result did not, and activates && regardless of what the result is. There should be a command that only outputs the self-test result, and activates || if the most recent had errors. <smartctl -H> has a concise output, but it is for firmware-specific attribute thresholds, not self-test results. The other problem with how <smartctl -H> behaves is that || activates when the disk slot is empty, and would trigger the same actions as if the disk was defective (if it even does || when defective, cannot test since HDDs rarely ever fail firmware thresholds). I would like to use Task Scheduler to automate <smartctl -t short> and be able to display VBS warning messages if the self-test completed with errors.

**Comment by chrfranke** [comment]
Please provide a more specific example use case.

**Comment by samm-git** [comment]
I think your usecase is covered with `smartd` already, but please provide more details

**Comment by chrfranke** [comment]
No feedback from reporter.
