### ISSUE TITLE
Add Samsung SSD 970 EVO Plus to drivedb.h

### ISSUE THREAD

**Issue by hsieger** [smartmontools/smartmontools#125]
smartctl is able to identify the Samsung SSD 970 EVO Plus NVMe drives and their SMART capabilities:

```
smartctl -x '/dev/nvme0'
...
=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        46 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    0%
...

```
Please add the model to the drive database.

Question: Can I add it myself using the following line under Samsung SSD:
   ` "Samsung SSD 970 EVO Plus ((250|500)G|[12]T)B|"`

or do these drives need different -v options?

**Comment by Firminator** [comment]
It's an NVMe drive... which they don't support. So it's not going to be added to the DB.
