### ISSUE TITLE
smartctl is using a deprecated SCSI ioctl, please convert it to SG_IO

### ISSUE THREAD

**Issue by hlovdal** [smartmontools/smartmontools#129]
Running smartctl generates syslog entries like

```text
2022-02-25T21:32:33.116930+01:00 myhostname kernel: program smartctl is using a deprecated SCSI ioctl, please convert it to SG_IO
```

package: smartmontools-7.1-1.el8.x86_64
os: CentOS Stream 8
kernel: 4.18.0-365.el8.x86_64

I notice Centos is lagging a bit behind on version, Is this fixed in 7.2?

**Comment by hlovdal** [comment]
Hm, seems to be a duplicate of [this ticket](https://www.smartmontools.org/ticket/350).

**Comment by hlovdal** [comment]
The `SG_IO` pre-processor token must have existed from the start since `smartmontools/os_linux.cpp` contains an `#ifndef SG_IO` from 2004.

But comparing [4.18](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/scsi/scsi_ioctl.c?h=v4.18)* and [5.16](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/drivers/scsi/scsi_ioctl.c?h=v5.16) gives the following list of newer ioctl values that are handled

* SG_GET_VERSION_NUM
* SG_SET_TIMEOUT
* SG_GET_TIMEOUT
* SG_GET_RESERVED_SIZE
* SG_SET_RESERVED_SIZE
* SG_EMULATED_HOST
* SG_IO

and `SG_IO` is now also used as a ioctl value. And `smartmontools/os_linux.cpp` has been using that since 2017, although that might not be significant. From briefly looking at the code I assume `sg_io_cmnd_io` fails for some reason (`SG_IO` or not) and falls back to `SCSI_IOCTL_SEND_COMMAND`/`SG_IO_UNSUPP`.

So the conclusion on my analysis is that there seems to be nothing wrong with compilation of the package, the issue is lack of ioctl support in the kernel.

---------
\* Although the 365 kernel version number include many backports done by Redhat, so the actual difference might be less but I have not checked.

**Comment by samm-git** [comment]
Some of the drivers not working with newer ioctl and smartctl reverting back to old one which kernel does not like. So not a bug

**Comment by doug-gilbert** [comment]
Yes, the Linux kernel folks have been trying to get rid of ioctl(SCSI_IOCTL_SEND_COMMAND) for some time. Just looked at lk 5.17.0-rc6 and it is still there. I'll have a look at this when the dust settles from the very recent smartmontools version 7.3 release.

**Comment by chrfranke** [comment]
Looks like the observations from [ticket #93](https://www.smartmontools.org/ticket/93) are still valid: SCSI_IOCTL_SEND_COMMAND is only unconditionally used for very old controllers (`-d 3ware,N`, `-d marvell`).
If this ioctl is used elsewhere, this means that either SG_IO is not supported by the kernel or the related detection code in os_linux.cpp does not always work or smartctl was compiled with very old kernel headers.

We could possibly now remove the `#ifndef SG_IO ...` part to prevent the latter case.

**Comment by chrfranke** [comment]
SCSI_IOCTL_SEND_COMMAND is no longer used in the generic part since [r5348](https://www.smartmontools.org/changeset/5348) (534376e).

Please test this or any later pre-release. Source tarballs and binaries are available at https://builds.smartmontools.org/

**Comment by chrfranke** [comment]
[r5348](https://www.smartmontools.org/changeset/5348) (534376e) successfully tested, see ticket [#1618](https://www.smartmontools.org/ticket/1618#comment:2).
