### ISSUE TITLE
Samsung 850 PRO - Values

### ISSUE THREAD

**Issue by interduo** [smartmontools/smartmontools#13]
Hellou this is Samsung 850 PRO smarty table.

```
$ smartctl -a /dev/sdh | grep -E 'Wear_Leveling_Count'\|'LBAs'\|'Model'\|'Number'\|'Firmware'
Model Family:     Samsung based SSDs
Device Model:     Samsung SSD 850 PRO 128GB
Serial Number:    S24ZNXAH211973D
Firmware Version: EXM02B6Q
177 Wear_Leveling_Count     0x0013   002   002   000    Pre-fail  Always       -       5887
241 Total_LBAs_Written      0x0032   099   099   000    Old_age   Always       -       62578693422
```

I used calculator `https://www.virten.net/2016/12/ssd-total-bytes-written-calculator/` and put raw LBAs  value (62578693422) in it. The result is: 29.14 TB.

I looked up in specs and find out that:
"Samsung's 3D V-NAND technology is built to handle 150 Tera Bytes Written (TBW) for 128GB"
So it's 1/5 part of its wareout.

So why the "Wear_Leveling_Count" is so low? How to interprate this? Are these parameters depends on each other or not? 

Is this disc is junk right now or not? Does smartctl reads this values in good way?

**Comment by interduo** [comment]
`=== START OF INFORMATION SECTION ===
Model Family:     Samsung based SSDs
Device Model:     Samsung SSD 850 PRO 128GB
Serial Number:    S24ZNXAH211973D
LU WWN Device Id: 5 002538 840198860
Firmware Version: EXM02B6Q
User Capacity:    128,035,676,160 bytes [128 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-2, ATA8-ACS T13/1699-D revision 4c
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Thu Oct 25 09:40:00 2018 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
AAM feature is:   Unavailable
APM feature is:   Unavailable
Rd look-ahead is: Enabled
Write cache is:   Enabled
ATA Security is:  Disabled, NOT FROZEN [SEC1]
Unexpected SCT status 0x0001 (action_code=4, function_code=2)
Wt Cache Reorder: Unknown (SCT Feature Control command failed)

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x00)	Offline data collection activity
					was never started.
					Auto Offline Data Collection: Disabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(    0) seconds.
Offline data collection
capabilities: 			 (0x53) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Suspend Offline collection upon new
					command.
					No Offline surface scan supported.
					Self-test supported.
					No Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   2) minutes.
Extended self-test routine
recommended polling time: 	 (  68) minutes.
SCT capabilities: 	       (0x003d)	SCT Status supported.
					SCT Error Recovery Control supported.
					SCT Feature Control supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 1
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
  5 Reallocated_Sector_Ct   PO--CK   100   100   010    -    0
  9 Power_On_Hours          -O--CK   093   093   000    -    32575
 12 Power_Cycle_Count       -O--CK   099   099   000    -    20
177 Wear_Leveling_Count     PO--C-   001   001   000    -    6586
179 Used_Rsvd_Blk_Cnt_Tot   PO--C-   100   100   010    -    0
181 Program_Fail_Cnt_Total  -O--CK   100   100   010    -    0
182 Erase_Fail_Count_Total  -O--CK   100   100   010    -    0
183 Runtime_Bad_Block       PO--C-   100   100   010    -    0
187 Uncorrectable_Error_Cnt -O--CK   100   100   000    -    0
190 Airflow_Temperature_Cel -O--CK   078   057   000    -    22
195 ECC_Error_Rate          -O-RC-   200   200   000    -    0
199 CRC_Error_Count         -OSRCK   100   100   000    -    0
235 POR_Recovery_Count      -O--C-   099   099   000    -    19
241 Total_LBAs_Written      -O--CK   099   099   000    -    70269450390
                            ||||||_ K auto-keep
                            |||||__ C event count
                            ||||___ R error rate
                            |||____ S speed/performance
                            ||_____ O updated online
                            |______ P prefailure warning

General Purpose Log Directory Version 1
SMART           Log Directory Version 1 [multi-sector log support]
Address    Access  R/W   Size  Description
0x00       GPL,SL  R/O      1  Log Directory
0x01           SL  R/O      1  Summary SMART error log
0x02           SL  R/O      1  Comprehensive SMART error log
0x03       GPL     R/O      1  Ext. Comprehensive SMART error log
0x06           SL  R/O      1  SMART self-test log
0x07       GPL     R/O      1  Extended self-test log
0x09           SL  R/W      1  Selective self-test log
0x10       GPL     R/O      1  SATA NCQ Queued Error log
0x11       GPL     R/O      1  SATA Phy Event Counters log
0x13       GPL     R/O      1  SATA NCQ Send and Receive log
0x30       GPL,SL  R/O      9  IDENTIFY DEVICE data log
0x80-0x9f  GPL,SL  R/W     16  Host vendor specific log
0xa1       GPL,SL  VS      16  Device vendor specific log
0xa5       GPL,SL  VS      16  Device vendor specific log
0xce       GPL,SL  VS      16  Device vendor specific log
0xde           SL  VS       1  Device vendor specific log
0xe0       GPL,SL  R/W      1  SCT Command/Status
0xe1       GPL,SL  R/W      1  SCT Data Transfer

SMART Extended Comprehensive Error Log Version: 1 (1 sectors)
No Errors Logged

SMART Extended Self-test Log Version: 1 (1 sectors)
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%     22403         -
# 2  Short offline       Completed without error       00%     22379         -
# 3  Short offline       Completed without error       00%     22355         -
# 4  Short offline       Completed without error       00%     22331         -
# 5  Short offline       Completed without error       00%     22307         -
# 6  Short offline       Completed without error       00%     22283         -
# 7  Short offline       Completed without error       00%     22259         -
# 8  Short offline       Completed without error       00%     22235         -
# 9  Short offline       Completed without error       00%     22211         -
#10  Short offline       Completed without error       00%     22187         -
#11  Short offline       Completed without error       00%     22163         -
#12  Short offline       Completed without error       00%     22139         -
#13  Short offline       Completed without error       00%     22115         -
#14  Short offline       Completed without error       00%     22090         -
#15  Short offline       Completed without error       00%     22066         -
#16  Short offline       Completed without error       00%     22042         -
#17  Short offline       Completed without error       00%     22018         -
#18  Short offline       Completed without error       00%     21994         -
#19  Short offline       Completed without error       00%     21970         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.

SCT Status Version:                  3
SCT Version (vendor specific):       1 (0x0001)
SCT Support Level:                   1
Device State:                        Active (0)
Current Temperature:                    22 Celsius
Power Cycle Min/Max Temperature:      ?/ ? Celsius
Lifetime    Min/Max Temperature:      ?/ ? Celsius
Under/Over Temperature Limit Count:   0/123900

SCT Temperature History Version:     2
Temperature Sampling Period:         10 minutes
Temperature Logging Interval:        10 minutes
Min/Max recommended Temperature:      ?/ ? Celsius
Min/Max Temperature Limit:            ?/ ? Celsius
Temperature History Size (Index):    128 (109)

Index    Estimated Time   Temperature Celsius
 110    2018-10-24 12:30    22  ***
 ...    ..( 29 skipped).    ..  ***
  12    2018-10-24 17:30    22  ***
  13    2018-10-24 17:40    21  **
  14    2018-10-24 17:50    22  ***
  15    2018-10-24 18:00    21  **
  16    2018-10-24 18:10    22  ***
 ...    ..( 92 skipped).    ..  ***
 109    2018-10-25 09:40    22  ***

SCT Error Recovery Control:
           Read: Disabled
          Write: Disabled

Device Statistics (GP/SMART Log 0x04) not supported

SATA Phy Event Counters (GP Log 0x11)
ID      Size     Value  Description
0x0001  2            0  Command failed due to ICRC error
0x0002  2            0  R_ERR response for data FIS
0x0003  2            0  R_ERR response for device-to-host data FIS
0x0004  2            0  R_ERR response for host-to-device data FIS
0x0005  2            0  R_ERR response for non-data FIS
0x0006  2            0  R_ERR response for device-to-host non-data FIS
0x0007  2            0  R_ERR response for host-to-device non-data FIS
0x0008  2            0  Device-to-host non-data FIS retries
0x0009  2           23  Transition from drive PhyRdy to drive PhyNRdy
0x000a  2           23  Device-to-host register FISes sent due to a COMRESET
0x000b  2            0  CRC errors within host-to-device FIS
0x000d  2            0  Non-CRC errors within host-to-device FIS
0x000f  2            0  R_ERR response for host-to-device data FIS, CRC
0x0010  2            0  R_ERR response for host-to-device data FIS, non-CRC
0x0012  2            0  R_ERR response for host-to-device non-data FIS, CRC
0x0013  2            0  R_ERR response for host-to-device non-data FIS, non-CRC`

**Comment by interduo** [comment]
https://gist.github.com/interduo/770ffeb2ae0ecc50d9aa6e190f296bbc

**Comment by samm-git** [comment]
Just googled about it:

> That's the exact opposite of my experience. My new drives (Samsung 850 Pro, Samsung 840 Pro) had started at a Raw Value of 0 and went up from there. In fact my current 840 Pro was at 97 about a month ago, and it's now at 99. (This is from looking at SMART data through the Samsung Magician software.) 

So as you could see - for 850 it should go up and it mean that you are safe. Please note that these attributes are not standardized, and as you could see may differ even for a single vendor, and `-l devstat` which is part of the standard is not supported by this drive. Anyway, looks like no reason to worry about.

**Comment by samm-git** [comment]
And yes, smartctl reads exactly what is in the smart page. And is not interpreting them

**Comment by samm-git** [comment]
Also attribute 241 is probably not showing erase counts, so this calculation is not correct

**Comment by interduo** [comment]
Thank You for the answer.

But how to determinate what is the state in percents of this disc life? Is it really possible?

**Comment by samm-git** [comment]
@interduo always depends on the vendor. Newer drives do have `devstat` log page, so its a bit better. But still not always accurate. Root here is to monitor smart health and do backups :) Every prediction module could be accurate but could be wrong.
