### ISSUE TITLE
smartd prevents fstab mount of external hdd

### ISSUE THREAD

**Issue by Vannixxo** [smartmontools/smartmontools#136]
Hello, I noticed that smartd accessing my external hdd during boot prevents it from being correctly mounted by fstab.
This way I cannot access the drive anymore.

If I remove any config from the smartd configuration file, so the service doesn't start, and then manually starting it (after restoring the correct configuration, and having the drive already mounted) everything works.

Is there any way I could prevent this? Like delaying the smartd service start?

Thanks

**Comment by Vannixxo** [comment]
Solved after re-doing mount point

**Comment by samm-git** [comment]
1. No idea why it happens and it should not.
2. Please show your fstab entries and corresponding journald errors

**Comment by samm-git** [comment]
No reply within 2 weeks, feel free to reopen if still the case
