### ISSUE TITLE
cannot compile under android os

### ISSUE THREAD

**Issue by 3735943886** [smartmontools/smartmontools#142]
```
g++ -DHAVE_CONFIG_H -I.  -DBUILD_INFO='"(local build)"' -DSMARTMONTOOLS_SYSCONFDIR='"/usr/local/etc"' -DSMARTMONTOOLS_SMARTDSCRIPTDIR='"/usr/local/etc"' -DSMARTMONTOOLS_DRIVEDBDIR='"/usr/local/share/smartmontools"'        -g -O2 -std=gnu++11 -Wall -W -Wformat=2 -Werror=return-type -fstack-protector-strong -MT smartd.o -MD -MP -MF .deps/smartd.Tpo -c -o smartd.o smartd.cpp
smartd.cpp:1436:16: error: use of undeclared identifier 'getdtablesize'; did you mean 'getpagesize'?
  for (int i = getdtablesize(); --i >= 0; )
               ^~~~~~~~~~~~~
               getpagesize
1 error generated.
make[1]: *** [Makefile:1316: smartd.o] Error 1
make: *** [Makefile:953: all] Error 2
~/smartmontools-7.3 $
```

refering from [man page](https://linux.die.net/man/2/getdtablesize) of getdtablesize,
it could be changed to sysconf(_SC_OPEN_MAX)

**Comment by chrfranke** [comment]
Most libc should provide `getdtablesize()` because it appeared in both old SysV and old BSD.
Which libc is used here? 
Did you test with for example `./configure CPPFLAGS=-D_BSD_SOURCE` ?

Changing to `sysconf(_SC_OPEN_MAX)` unconditionally should be safe because this even appeared in POSIX predecessors:
https://pubs.opengroup.org/onlinepubs/007908799/xsh/sysconf.html

PS: I don't remember any feedback regarding smartmontools under android. What is your use case?

**Comment by 3735943886** [comment]
Thank you for prompt answer. 

Because I set up android device (not a phone but an SBC) for multimedia server. Eventually I need some monitoring tools of storage devices but apps on google play don't have enough permissions for deep monitoring system devices. Thus I decided to compile smartmontools. Thank you again for great project!

However, configuration with CPPFLAGS=-D_BSD_SOURCE also failed with same error messages. 

I manually modified two occurrences (in smartd.cpp and popen_as_guid.cpp) and compiled it without any problems. 

As far as I know, Android OS is a kind of linux but there seems to be some differences of libraries from pure linux system. 

I hope you'd please consider adding this modification to your project for better compatibilities. 

Thank you.

**Comment by chrfranke** [comment]
Interestingly `getdtablesize()` was already declared LEGACY five years before smartmontools project started in 2002: https://pubs.opengroup.org/onlinepubs/007908799/xsh/getdtablesize.html
It was intentionally removed from android SDK: https://issuetracker.google.com/issues/37001193

**Comment by chrfranke** [comment]
Added in [r5402](https://www.smartmontools.org/changeset/5402) (3be728e).
