### ISSUE TITLE
Potential resource leak (file not closed)

### ISSUE THREAD

**Issue by ilikesearch** [smartmontools/smartmontools#143]
There is a potential resource leak in function `linux_smart_interface::get_dev_megasas(smart_device_list & devlist)`. (in "os_linux.cpp")

In rare cases, the call to function `megasas_pd_add_list` could throw a `bad_alloc` exception, which causes resource leaks on `fp` and `dp`.

**Comment by chrfranke** [comment]
Indeed, including the `list` before the `list = ... realloc(list, list_size)` call. These leaks are harmless and cannot accumulate even in `smartd` because the `throw` is handled by `main()` which exits immediately then.

**Comment by ilikesearch** [comment]
The memory leaks are probably harmless, but I think the files still need to be closed even the program exits.

**Comment by chrfranke** [comment]
No, if a process terminates or crashes, the kernel closes all remaining open file descriptors and frees other resources. This is long standing behavior since the old Unix (pre-Linux) days, see for example [SUS 1997](https://pubs.opengroup.org/onlinepubs/007908799/xsh/exit.html)

**Comment by ilikesearch** [comment]
Thanks for the reference, I didn't know that before. I found the file was already closed in the normal flow so that I thought it still needed to be closed in the exception flow.
