### ISSUE TITLE
smartctl does not allow to query individual attributes

### ISSUE THREAD

**Issue by stefanct** [smartmontools/smartmontools#148]
It would be nice to have an option to just query a single attribute instead of all of them, e.g. with an optional argument to the -A option. Even nicer would be if one could select the format as well, e.g., to only get the raw value.
(Yes, I have heard about grep :P)

**Comment by chrfranke** [comment]
For specific use cases not covered by the default output, we provide `smartctl --json[=...]` support.

**Comment by samm-git** [comment]
+1. Also `jq` is a superpowerful tool to filter on specific atrribute when json is in use
