### ISSUE TITLE
smartctl does only operate on a single device

### ISSUE THREAD

**Issue by stefanct** [smartmontools/smartmontools#149]
The last parameter of smartctl specifies the device to access. There is no way to specify multiple devices in a single invocation. That's not a big deal of course but is there any reason for it other than that nobody has implemented the loop around argv's elements?

**Comment by chrfranke** [comment]
This will not be added, sorry. Usually outputs for each device are required separately and not as a part of a long plain text sequence. It is also not obvious, how the exit status should be handled.

Here a sample bash script which accepts multiple devices and accumulates error bits in exit status:
```bash
#!/bin/bash

declare -a opts
while [ $# -gt 0 ] && [ "$1" != "--" ]; do
  opts+=( "$1" ); shift
done
if [ "$1" != "--" ] || [ $# -lt 2 ]; then
  echo "Usage: $0 [OPTION...] -- DEVICE..."; exit 1
fi
shift

status=0
for dev in "$@"; do
  echo "============================================================================"
  echo "$dev:"
  smartctl "${opts[@]}" -- "$dev"
  st=$?
  echo "exit status: $st"
  status=$((status | $st))
done

exit $status
```
