### ISSUE TITLE
Add a new -M TYPE

### ISSUE THREAD

**Issue by urbanogilson** [smartmontools/smartmontools#153]
We currently have the options once, daily, and diminishing for email frequency.

I would like to have an "on every occurrence" option. Basically it will send a notification on every detection even if it is duplicated.

I can implement it and create a PR, but I would like to hear your opinion before I start working on it.

https://www.smartmontools.org/browser/trunk/smartmontools/smartd.conf.5.in

**Comment by chrfranke** [comment]
Thanks for the offer and sorry for the delay. Yes, such a `-M always` option makes plenty of sense. I already have a related patch series (which adds an `enum` first to this very old code) on the local stash and will commit it soon.

**Comment by chrfranke** [comment]
Fixed, see [ticket #1018](https://www.smartmontools.org/ticket/1018#comment:6).
