### ISSUE TITLE
How To: how can we install newer versions of smartmontools on debian flavour / Ubuntu LTS?

### ISSUE THREAD

**Issue by fermulator** [smartmontools/smartmontools#166]
Lots of servers will be on Ubuntu 18.04 or 20.04 for quite some time, and the version of `smartmontools` could be arguably old.

- On 20.04, we have 7.1 :checkered_flag: 
- But on 18.04 we have 6.5 :x: 

Are there any instructions to get it installed on older Ubuntu flavours? (i tried downloading `.deb` 7.1 on Ubuntu 18.04 server but it was missing a bunch of dependencies and they weren't automatically resolved)

Any known/supported PPAs?

**Comment by chrfranke** [comment]
smartmontools 7.0 is available in 18.04 backports repo: https://packages.ubuntu.com/bionic-backports/smartmontools

Please note that we do not provide packages for any Linux distribution. Backports needs to be requested from the official package maintainer. On Ubuntu, Launchpad is possibly the correct way to do this: https://launchpad.net/ubuntu/+source/smartmontools/+bugs

**Comment by chrfranke** [comment]
You could also build 7.3 from the latest source tarball (`./configure && make && make install`) or use a recent CI build from https://builds.smartmontools.org/. These builds are statically linked, so there are not dependencies to shared libraries.
