### ISSUE TITLE
Limited support for 2nd disk behind ASM1352R USB to SATA bridges

### ISSUE THREAD

**Issue by wiedem** [smartmontools/smartmontools#167]
Any chance you can add support for the [ASM1352R](https://www.asmedia.com.tw/product/509Yqd4SX5yG9gm7/3AbyQ83xZAUr3qW5) based USB bridges (e.g. the IcyBox RD3662)?

The current version does allow to read the S.M.A.R.T. info of the first device via `-d sat` but doesn't support reading the info of the second device.

CrystalDiskInfo has a working implementation:
https://github.com/hiyohiyo/CrystalDiskInfo/commit/0f944fa6d5bbbca04919c2577506ed5de1197d41

**Comment by chrfranke** [comment]
Thanks for the info. Looks like the ASM1352R uses a reserved value of the PROTOCOL field of the ATA PASS-THROUGH command to address the 2nd device.

To make sure that this is correct, please apply this patch and test whether `-d sat` addresses the 2nd device then:
```diff
Index: scsiata.cpp
===================================================================
--- scsiata.cpp (revision 5430)
+++ scsiata.cpp (working copy)
@@ -248,7 +248,7 @@
 bool sat_device::ata_pass_through(const ata_cmd_in & in, ata_cmd_out & out)
 {
     if (!ata_cmd_is_supported(in,
-      ata_device::supports_data_out |
+      //ata_device::supports_data_out | // ASM1352R: DATA OUT disabled for now
       ata_device::supports_output_regs |
       ata_device::supports_multi_sector |
       ata_device::supports_48bit,
@@ -290,6 +290,7 @@
         return set_err(EINVAL, "sat_device::ata_pass_through: invalid direction=%d",
             (int)in.direction);
     }
+    protocol = 0xe; // ASM1352R: selects 2nd drive

     // Check condition if any output register needed
     if (in.out_needed.is_set())
```

**Comment by wiedem** [comment]
That's easier than I thought! Yes, it actually works like that.

First device without patch:
```
smartctl pre-7.4 (build date Jan 12 2023) [armv7l-linux-5.15.76-v7l+] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Western Digital Green
Device Model:     WDC WD30EZRX-00DC0B0
Serial Number:    WD-WMC1T21XXXXXX
LU WWN Device Id: 5 0014ee 603155e48
Firmware Version: 80.00A80
User Capacity:    3.000.592.982.016 bytes [3,00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Device is:        In smartctl database
ATA Version is:   ACS-2 (minor revision not indicated)
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Thu Jan 12 18:38:26 2023 CET
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

Second device with patch:

```
smartctl pre-7.4 (build date Jan 12 2023) [armv7l-linux-5.15.76-v7l+] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Western Digital Green
Device Model:     WDC WD30EZRX-00DC0B0
Serial Number:    WD-WMC1T22XXXXX
LU WWN Device Id: 5 0014ee 6adbfe7d6
Firmware Version: 80.00A80
User Capacity:    3.000.592.982.016 bytes [3,00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Device is:        In smartctl database
ATA Version is:   ACS-2 (minor revision not indicated)
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Thu Jan 12 18:40:26 2023 CET
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

**Comment by wiedem** [comment]
> Looks like the ASM1352R uses a reserved value of the PROTOCOL field of the ATA PASS-THROUGH command to address the 2nd device.

As you already wrote and can be read from the code comment of CrystalDiskInfo:
>  // PROTOCOL field should be "0Dh”SATA port0 and "0Eh" SATA port1.

I tested it again, with 0x0D you address port0, with 0x0E port1.

**Comment by chrfranke** [comment]
Thanks. Then a new `-d` option could be easily added.

Please also test whether DATA OUT commands possibly work (`smartctl -l scterc -l scttemp`, included in `smartctl -x`) after re-adding the commented out `ata_device::supports_data_out` flag. Could only be tested if drive advertises SCT support.

**Comment by wiedem** [comment]
Sure, here we go:
```
smartctl pre-7.4 (build date Jan 12 2023) [armv7l-linux-5.15.76-v7l+] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SCT Status Version:                  3
SCT Version (vendor specific):       258 (0x0102)
Device State:                        Active (0)
Current Temperature:                    25 Celsius
Power Cycle Min/Max Temperature:     25/25 Celsius
Lifetime    Min/Max Temperature:      2/43 Celsius
Under/Over Temperature Limit Count:   0/0
Vendor specific:
01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

SCT Temperature History Version:     2
Temperature Sampling Period:         1 minute
Temperature Logging Interval:        1 minute
Min/Max recommended Temperature:      0/60 Celsius
Min/Max Temperature Limit:           -41/85 Celsius
Temperature History Size (Index):    478 (267)

Index    Estimated Time   Temperature Celsius
[...]

SCT Error Recovery Control command not supported
```

I removed the index entries, but they are there in the output.

**Comment by chrfranke** [comment]
Thanks - I will add `-d usbasm1352r,N` soon.

**Comment by chrfranke** [comment]
Added in [r5437](https://www.smartmontools.org/changeset/5437) (559856c), please test.

**Comment by chrfranke** [comment]
If possible, please test also the behavior of  `-d usbasm1352r,N` and `-d sat` if only one or no drive is connected.

**Comment by wiedem** [comment]
## Using `-d sat`

| Parameter | 2 Drives | 1 Drive | No Drives |
| --- | :---: | :---: | :---: |
| `-a`  | :white_check_mark: | :white_check_mark: | :white_check_mark:<br><sub>Read Device Identity failed: scsi error no medium present</sub> |
| `-H`  | :white_check_mark: | :white_check_mark: | :white_check_mark:<br><sub>Read Device Identity failed: scsi error no medium present</sub> |
| `-t short`  | :white_check_mark: | :white_check_mark: | :white_check_mark:<br><sub>Read Device Identity failed: scsi error no medium present</sub> |

All commands are performed on the first connected drive. I.e. if only one drive is connected to the second port, all SMART commands including self-tests are performed on this drive.

## Using `-d usbasm1352r,N`
| Parameter | 2 Drives | 1 Drive | No Drives |
| --- | :---: | :---: | :---: |
| `-i`  | :white_check_mark: | :white_check_mark: | :white_check_mark:<br><sub>Read Device Identity failed: scsi error unsupported field in scsi command</sub> |
| `-c`  | :white_check_mark: | :white_check_mark: | :white_check_mark:<br><sub>Read Device Identity failed: scsi error unsupported field in scsi command</sub> |
| `-g all`  | :white_check_mark: | :white_check_mark: | :white_check_mark:<br><sub>Read Device Identity failed: scsi error unsupported field in scsi command</sub> |
| `-A`  | :white_check_mark: | :white_check_mark: | :white_check_mark:<br><sub>Read Device Identity failed: scsi error unsupported field in scsi command</sub> |
| `-a`  | :x: | :x: | :x: |
| `-H`  | :x: | :x: | :x: |
| `-t short`  | :x: | :x: | :x: |

All failing commands return with a `Connection timed out` error.

@chrfranke hope this helps.

**Comment by chrfranke** [comment]
Thanks for testing. Please also test `-x` as `-a` only covers the legacy (28-bit ATA) SMART subset.
`-d sat` behavior looks good, in particular because it accesses the second drive if the first port is empty.

The timeouts on `-d usbasm1352r,N` should not happen. This is in particular interesting because CrystalDiskInfo uses the same commands for `-H` on second drive (it does not support `-t` etc) and this reportedly works.

**Comment by wiedem** [comment]
`-x` works as expected via `-d sat`.
```
=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED
```

I've also retested `-H` and `-x` via `-d usbasm1352r,N`.
`-x` takes a very long time, but eventually returns a result with a timeout error message `SMART Status command failed` but otherwise the output seems to be working.

```
=== START OF READ SMART DATA SECTION ===
SMART Status command failed: Connection timed out
SMART overall-health self-assessment test result: PASSED
Warning: This result is based on an Attribute check.
```

`-H` however always causes a timeout, which I guess is consistent with what I'm observing using `-x`.

I don't know what CrystalDiskInfo does differently, but as you describe, I can't observe this problem with the same hardware under Windows.

**Comment by chrfranke** [comment]
`smartctl -x` should always work without such problems at least if the corresponding drive is connected. Reopening this issue as this is apparently not the case.

Do the timeouts occur with both  `-d usbasm1352r,0` and `-d usbasm1352r,1` if the corresponding drives are connected?

CrystalDiskInfo does the equivalent of:
- `smartctl -i -A -H -d sat ...` for the first drive (`protocol=0x[34]` according to SAT standard)
- `smartctl -i -A -H -d usbasm1352r,1 ...` for the second drive (`protocol=0xe`).

`protocol=0xd` only appears in a comment and is not used by CrystalDiskInfo.

**Comment by wiedem** [comment]
> Do the timeouts occur with both `-d usbasm1352r,0` and `-d usbasm1352r,1` if the corresponding drives are connected?

Yes.

> CrystalDiskInfo does the equivalent of:
> smartctl `-i -A -H -d usbasm1352r,1` ... for the second drive (`protocol=0xe` ).

Something seems to be different, because this command leads to a timeout as described. A direct comparison is of course a bit difficult, because I run the tests with the customized smartctl version on Linux (5.15.76 armv7l), but the CrystalDiskInfo tests on a Windows 10 system.
I will try to build a Windows version of smartctl the next days to exclude that there are problems regarding the platform.

**Comment by chrfranke** [comment]
Thanks! Building a Windows version is not needed as we provide CI builds here: https://builds.smartmontools.org/

**Comment by wiedem** [comment]
Thanks for the hint.
I've now used `smartctl pre-7.4 2023-01-28 r5447 [x86_64-w64-mingw32-w10-22H2] (CircleCI)` for my tests.

This build causes different issues using `-d usbasm1352r,N` compared to my own Linux based build:
> === START OF READ SMART DATA SECTION ===
> SMART Status command failed: IOCTL_SCSI_PASS_THROUGH_DIRECT failed, Error=121
> SMART overall-health self-assessment test result: PASSED
> Warning: This result is based on an Attribute check.

`-d sat` works fine just like with the Linux build.

**Comment by wiedem** [comment]
@chrfranke Is there anything else you want me to test?

**Comment by chrfranke** [comment]
Sorry for the long delay. If possible, please test [r5482](https://www.smartmontools.org/changeset/5482) (c472970) or later. Timeouts should no longer occur but functionality is limited (self-tests not supported etc.).

**Comment by chrfranke** [comment]
Added in and [r5437](https://www.smartmontools.org/changeset/5437) (559856c) and [r5482](https://www.smartmontools.org/changeset/5482) (c472970).

It is unknown whether support for NO DATA commands could be added, so support is limited. Summary changed accordingly before closing ticket.
