### ISSUE TITLE
"GetLogPage failed" for NVMe Error Information Log on macOS/Darwin

### ISSUE THREAD

**Issue by forthrin** [smartmontools/smartmontools#176]
I'm getting a "GetLogPage failed" error on two MacBook Air M1 that don't seem to be on the issue trackers or the FAQ. There are [a few mentions](https://duckduckgo.com/?q=%22GetLogPage+failed%22), but no solutions. What does the error mean? How can one run tests on these machines?

```
$ smartctl -a disk1
smartctl 7.3 2022-02-28 r5338 [Darwin 22.3.0 arm64] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       APPLE SSD AP0256Q
Serial Number:                      ****************
Firmware Version:                   873.40.4
PCI Vendor/Subsystem ID:            0x106b
IEEE OUI Identifier:                0x000000
Controller ID:                      0
NVMe Version:                       <1.2
Number of Namespaces:               3
Local Time is:                      ****************************
Firmware Updates (0x02):            1 Slot
Optional Admin Commands (0x0004):   Frmw_DL
Optional NVM Commands (0x0004):     DS_Mngmt
Maximum Data Transfer Size:         256 Pages

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +     0.00W       -        -    0  0  0  0        0       0

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        ** Celsius
Available Spare:                    ***%
Available Spare Threshold:          **%
Percentage Used:                    *%
Data Units Read:                    ********************
Data Units Written:                 ********************
Host Read Commands:                 ***********
Host Write Commands:                ***********
Controller Busy Time:               0
Power Cycles:                       ***
Power On Hours:                     ***
Unsafe Shutdowns:                   ***
Media and Data Integrity Errors:    0
Error Information Log Entries:      0

Read 1 entries from Error Information Log failed: GetLogPage failed: system=0x38, sub=0x0, code=745
```

**Comment by chrfranke** [comment]
There are various reasons why self-tests do not work here:

> `smartctl 7.3 2022-02-28 r5338 [Darwin 22.3.0 arm64] (local build)`

This version of smartctl does not support NVMe self-tests. These were added in [r5408](https://www.smartmontools.org/changeset/5408) and will be part of upcoming release 7.4.

But unfortunately this does not work on macOS/Darwin because, unlike other platforms, it does not provide full-fledged pass-through APIs. According to https://developer.apple.com/documentation/iokit/ionvmesmartinterface, NVMe self-tests are not yet supported.

> `NVMe Version:                       <1.2`

The device only implements a very old NVMe version. Self-tests were added in NVMe 1.3.

> `Optional Admin Commands (0x0004):   Frmw_DL`

The device does not advertise self-test support because `Self_Test` does not appear above.

**Comment by chrfranke** [comment]
This error message is unrelated to self-tests:
> `Read 1 entries from Error Information Log failed: GetLogPage failed: system=0x38, sub=0x0, code=745`

Needs to be investigated by a macOS/Darwin expert. Adjusted issue summary accordingly.

**Comment by forthrin** [comment]
FYI, everything works on an older MacBook Air 2017.

```
smartctl 7.3 2022-02-28 r5338 [Darwin 21.6.0 x86_64] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Apple SD/SM/TS...E/F/G SSDs
Device Model:     APPLE SSD SM0512F
Serial Number:    **************
LU WWN Device Id: * ****** *********
Firmware Version: UXM2JA1Q
User Capacity:    *************** bytes [500 GB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    Solid State Device
TRIM Command:     Available
Device is:        In smartctl database 7.3/5319
ATA Version is:   ATA8-ACS T13/1699-D revision 4c
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    ******************* 2023 ***
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x00)	Offline data collection activity
					was never started.
					Auto Offline Data Collection: Disabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(    0) seconds.
Offline data collection
capabilities: 			 (0x5f) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Abort Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					No Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   2) minutes.
Extended self-test routine
recommended polling time: 	 (  10) minutes.

SMART Attributes Data Structure revision number: 40
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x001a   200   200   000    Old_age   Always       -       0
  5 Reallocated_Sector_Ct   0x0033   100   100   000    Pre-fail  Always       -       0
  9 Power_On_Hours          0x0032   090   090   000    Old_age   Always       -       49115
 12 Power_Cycle_Count       0x0032   075   075   000    Old_age   Always       -       25095
169 Unknown_Apple_Attrib    0x0013   253   253   010    Pre-fail  Always       -       3415186873856
173 Wear_Leveling_Count     0x0032   178   178   100    Old_age   Always       -       1550526513637
174 Host_Reads_MiB          0x0022   099   099   000    Old_age   Always       -       99551419
175 Host_Writes_MiB         0x0022   099   099   000    Old_age   Always       -       82066203
192 Power-Off_Retract_Count 0x0012   099   099   000    Old_age   Always       -       306
194 Temperature_Celsius     0x0022   075   075   000    Old_age   Always       -       25 (Min/Max 0/76)
197 Current_Pending_Sector  0x0022   100   100   000    Old_age   Always       -       0
199 UDMA_CRC_Error_Count    0x001a   200   200   000    Old_age   Always       -       0
240 Unknown_SSD_Attribute   0x0022   100   100   000    Old_age   Always       -       0

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%         0         -
# 2  Short offline       Completed without error       00%         0         -
# 3  Short offline       Completed without error       00%         0         -
# 4  Short offline       Completed without error       00%         8         -
# 5  Short offline       Completed without error       00%         0         -
# 6  Short offline       Completed without error       00%         0         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.
```

**Comment by chrfranke** [comment]
This is a SATA device which differs considerably from NVMe devices. ATA Self-tests are supported by smartctl and also the Darwin ATA pass-through API, see https://developer.apple.com/documentation/iokit/ioatasmartinterface/1477737-smartexecuteofflineimmediate.

**Comment by forthrin** [comment]
> There are various reasons why self-tests do not work here:
> 
> > `smartctl 7.3 2022-02-28 r5338 [Darwin 22.3.0 arm64] (local build)`
> 
> This version of smartctl does not support NVMe self-tests. These were added in [r5408](https://www.smartmontools.org/changeset/5408) and will be part of upcoming release 7.4.

Great!

> But unfortunately this does not work on macOS/Darwin because, unlike other platforms, it does not provide full-fledged pass-through APIs. According to https://developer.apple.com/documentation/iokit/ionvmesmartinterface, NVMe self-tests are not yet supported.
> 
> > `NVMe Version:                       <1.2`
> 
> The device only implements a very old NVMe version. Self-tests were added in NVMe 1.3.
> 
> > `Optional Admin Commands (0x0004):   Frmw_DL`
> 
> The device does not advertise self-test support because `Self_Test` does not appear above.

You refer ambigiously to _"it"_ and _"the device"_. Is it **macOS**, the **disk**, or the **motherboard** that lacks support?

**Comment by chrfranke** [comment]
Both macOS and the NVMe disk do not support NVMe self-tests.

**Comment by forthrin** [comment]
OK, so this disk will never be testable. I'll check this capability next time I buy a MacBook (in five years or so).

Will `smartctl` be of any use for this disk? Which output information should I keep an eye on?

PS! If anyone knows if this applies for all recent macOS devices or just certain production batches, post this here.

**Comment by samm-git** [comment]
Few notes here:

1. Smartmontools on macOS using private and undocumented API which initially was reverse-engineered and later published in one of the recent SDK headers. This applies to both SATA and NVME, but for NVME even more.
2. This API allows only to implement only very limited functionality (e.g. no self-tests possible). Moreover, NVME disks in M1 are not "real" NVME but are very apple-customized devices with their own firmware. So it is possible that they will not match the entire standard. 
3. Despite that smartctl is still very useful on m1. Things to monitor are:
     - `Percentage Used` (and take actions  if it's growing fast)
     - `Temperature` (usually very low on my m1)
     - `Critical Warning` (should be 0x00)
     - `Data Units Read/Written` - something to take a look at if `Percentage Used` growing fast.

Message 
> Read 1 entries from Error Information Log failed: GetLogPage failed: system=0x38, sub=0x0, code=745

could be safely ignored

**Comment by forthrin** [comment]
@samm-git: Thanks for your helpful pointers. Does "Percentage used" count sectors that are "worn out" and unusable? Or is this a more general lifespan estimate, based on Power On Hours and Data Read/Written?

**Comment by samm-git** [comment]
@forthrin yw. According to the specification it is:

> Percentage Used: Contains a vendor specific estimate of the percentage of NVM subsystem life used based on the actual usage and the manufacturer’s prediction of NVM life. A value of 100 indicates that the estimated endurance of the NVM in the NVM subsystem has been consumed, but may not indicate an NVM subsystem failure. The value is allowed to exceed 100. Percentages greater than 254 shall be represented as 255. This value shall be updated once per power-on hour (when the controller is not in a sleep state).

How exactly is calculated is up to the vendor.

**Comment by forthrin** [comment]
Very nice. Such monitoring can be easily done with a simple Ruby script.

```
smart = `smartctl -a disk1`.scan(/(.*?):\s*(.*)/).to_h
puts "Global Warming Alert!" if smart['Temperature'].to_i >= 40
# etc
```
