### ISSUE TITLE
"-f hex" option is not working

### ISSUE THREAD

**Issue by eLvErDe** [smartmontools/smartmontools#18]
Hello,

I'm trying to get SMART information using attribute IDs instead of pretty display name and it just don't work (neither with 6.5 nor 6.6):

```
smartctl -f hex,id -a /dev/sdb
```

```
[...]
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000c5008422ecab
Serial number:        Z1Z9H2EZ
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Tue Sep 25 13:47:32 2018 CEST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

Current Drive Temperature:     24 C
Drive Trip Temperature:        60 C
[...]
```

I expect to see attributes id...

Regards, Adam.

**Comment by chrfranke** [comment]
The '-f' option only affects the output of the ATA SMART attribute table, see man page. SCSI/SAS devices don't provide ATA-like attributes. For easier parsing of smartctl output, try new '--json' option of current SVN revision.

**Comment by chrfranke** [comment]
The are no plans to enhance the `-f` option to other parts of smartctl output.
