### ISSUE TITLE
WD80EAZZ-00BKLB0 Not in smartctl drivedb

### ISSUE THREAD

**Issue by Kruge** [smartmontools/smartmontools#192]
This Western Digital Blue CMR drive released early last year isn't in drivedb yet. Figured I'd make the request.

Attached is the output of **smartctl -q noserial -x**

[smartctl-WD80EAZZ-00BKLB0.txt](https://github.com/smartmontools/smartmontools/files/11455658/smartctl-WD80EAZZ-00BKLB0.txt)

**Comment by chrfranke** [comment]
See [ticket 1576](https://www.smartmontools.org/ticket/1576).
