### ISSUE TITLE
Scttemp log shows 2nd oldest temp 1st, oldest last. WDC WD80EDAZ

### ISSUE THREAD

**Issue by crgithubmoth** [smartmontools/smartmontools#194]
Smartctl 7.2 r5155
Firmware 81.00A81
More to come...

**Comment by crgithubmoth** [comment]
Do you have a ubuntu ppa for 7.3?

**Comment by crgithubmoth** [comment]
Log on #51 shows the same thing I see
Log on #97 does NOT show the error
Log on #34 has the error too.
smartctl 7.1 r5022 also shows it on WDC WD161KFGX
Log on #174:
 Device Model:     WDC WD181KFGX-68AFPN0
Firmware Version: 83.00A83

**Comment by crgithubmoth** [comment]
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-6.2.0-20-generic] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     WDC WD161KFGX-68AFPN0
Firmware Version: 83.00A83
User Capacity:    16,000,900,661,248 bytes [16.0 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ACS-4 published, ANSI INCITS 529-2018
SATA Version is:  SATA 3.3, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Mon Jun 19 16:15:01 2023 EDT
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
AAM feature is:   Unavailable
APM level is:     254 (maximum performance)
Rd look-ahead is: Enabled
Write cache is:   Enabled
DSN feature is:   Unavailable
ATA Security is:  Disabled, frozen [SEC2]
Wt Cache Reorder: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x82)	Offline data collection activity
					was completed without error.
					Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(  101) seconds.
Offline data collection
capabilities: 			 (0x5b) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Suspend Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					No Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   2) minutes.
Extended self-test routine
recommended polling time: 	 (1943) minutes.
SCT capabilities: 	       (0x003d)	SCT Status supported.
					SCT Error Recovery Control supported.
					SCT Feature Control supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
  1 Raw_Read_Error_Rate     PO-R--   100   100   001    -    0
  2 Throughput_Performance  --S---   137   137   054    -    92
  3 Spin_Up_Time            POS---   088   088   001    -    144 (Average 356)
  4 Start_Stop_Count        -O--C-   100   100   000    -    5
  5 Reallocated_Sector_Ct   PO--CK   100   100   001    -    0
  7 Seek_Error_Rate         -O-R--   100   100   001    -    0
  8 Seek_Time_Performance   --S---   140   140   020    -    15
  9 Power_On_Hours          -O--C-   100   100   000    -    3785
 10 Spin_Retry_Count        -O--C-   100   100   001    -    0
 12 Power_Cycle_Count       -O--CK   100   100   000    -    3
 22 Unknown_Attribute       PO---K   100   100   025    -    100
192 Power-Off_Retract_Count -O--CK   100   100   000    -    163
193 Load_Cycle_Count        -O--C-   100   100   000    -    163
194 Temperature_Celsius     -O----   056   056   000    -    38 (Min/Max 23/46)
196 Reallocated_Event_Count -O--CK   100   100   000    -    0
197 Current_Pending_Sector  -O---K   100   100   000    -    0
198 Offline_Uncorrectable   ---R--   100   100   000    -    0
199 UDMA_CRC_Error_Count    -O-R--   100   100   000    -    0
                            ||||||_ K auto-keep
                            |||||__ C event count
                            ||||___ R error rate
                            |||____ S speed/performance
                            ||_____ O updated online
                            |______ P prefailure warning

General Purpose Log Directory Version 1
SMART           Log Directory Version 1 [multi-sector log support]
Address    Access  R/W   Size  Description
0x00       GPL,SL  R/O      1  Log Directory
0x01           SL  R/O      1  Summary SMART error log
0x02           SL  R/O      1  Comprehensive SMART error log
0x03       GPL     R/O      1  Ext. Comprehensive SMART error log
0x04       GPL     R/O    256  Device Statistics log
0x04       SL      R/O    255  Device Statistics log
0x06           SL  R/O      1  SMART self-test log
0x07       GPL     R/O      1  Extended self-test log
0x08       GPL     R/O      2  Power Conditions log
0x09           SL  R/W      1  Selective self-test log
0x0c       GPL     R/O  30001  Pending Defects log
0x10       GPL     R/O      1  NCQ Command Error log
0x11       GPL     R/O      1  SATA Phy Event Counters log
0x12       GPL     R/O      1  SATA NCQ Non-Data log
0x13       GPL     R/O      1  SATA NCQ Send and Receive log
0x15       GPL     R/W      1  Rebuild Assist log
0x21       GPL     R/O      1  Write stream error log
0x22       GPL     R/O      1  Read stream error log
0x24       GPL     R/O    256  Current Device Internal Status Data log
0x25       GPL     R/O    256  Saved Device Internal Status Data log
0x2f       GPL     -        1  Set Sector Configuration
0x30       GPL,SL  R/O      9  IDENTIFY DEVICE data log
0x80-0x9f  GPL,SL  R/W     16  Host vendor specific log
0xe0       GPL,SL  R/W      1  SCT Command/Status
0xe1       GPL,SL  R/W      1  SCT Data Transfer

SMART Extended Comprehensive Error Log Version: 1 (1 sectors)
No Errors Logged

SMART Extended Self-test Log Version: 1 (1 sectors)
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%      3784         -
# 2  Short offline       Completed without error       00%        17         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.

SCT Status Version:                  3
SCT Version (vendor specific):       256 (0x0100)
Device State:                        Active (0)
Current Temperature:                    38 Celsius
Power Cycle Min/Max Temperature:     23/46 Celsius
Lifetime    Min/Max Temperature:     23/46 Celsius
Under/Over Temperature Limit Count:   0/0
SMART Status:                        0xc24f (PASSED)
Minimum supported ERC Time Limit:    70 (7.0 seconds)

SCT Temperature History Version:     2
Temperature Sampling Period:         1 minute
Temperature Logging Interval:        1 minute
Min/Max recommended Temperature:      0/60 Celsius
Min/Max Temperature Limit:           -40/70 Celsius
Temperature History Size (Index):    128 (86)

Index    Estimated Time   Temperature Celsius
  87    2023-06-19 14:08    41  **********************
 ...    ..( 74 skipped).    ..  **********************
  34    2023-06-19 15:23    41  **********************
  35    2023-06-19 15:24    40  *********************
  36    2023-06-19 15:25    41  **********************
  37    2023-06-19 15:26    41  **********************
  38    2023-06-19 15:27    41  **********************
  39    2023-06-19 15:28    40  *********************
 ...    ..( 12 skipped).    ..  *********************
  52    2023-06-19 15:41    40  *********************
  53    2023-06-19 15:42    41  **********************
 ...    ..(  9 skipped).    ..  **********************
  63    2023-06-19 15:52    41  **********************
  64    2023-06-19 15:53    40  *********************
  65    2023-06-19 15:54    40  *********************
  66    2023-06-19 15:55    39  ********************
  67    2023-06-19 15:56    39  ********************
  68    2023-06-19 15:57    38  *******************
  69    2023-06-19 15:58    38  *******************
  70    2023-06-19 15:59    37  ******************
  71    2023-06-19 16:00    37  ******************
  72    2023-06-19 16:01    36  *****************
 ...    ..(  4 skipped).    ..  *****************
  77    2023-06-19 16:06    36  *****************
  78    2023-06-19 16:07    37  ******************
 ...    ..(  4 skipped).    ..  ******************
  83    2023-06-19 16:12    37  ******************
  84    2023-06-19 16:13    38  *******************
  85    2023-06-19 16:14    37  ******************
  86    2023-06-19 16:15    41  **********************

SCT Error Recovery Control:
           Read:     70 (7.0 seconds)
          Write:     70 (7.0 seconds)

Device Statistics (GP Log 0x04)
Page  Offset Size        Value Flags Description
0x01  =====  =               =  ===  == General Statistics (rev 1) ==
0x01  0x008  4               3  ---  Lifetime Power-On Resets
0x01  0x010  4            3785  ---  Power-on Hours
0x01  0x018  6     17304184178  ---  Logical Sectors Written
0x01  0x020  6        27302762  ---  Number of Write Commands
0x01  0x028  6     26258077981  ---  Logical Sectors Read
0x01  0x030  6        45148197  ---  Number of Read Commands
0x01  0x038  6     13627536050  ---  Date and Time TimeStamp
0x03  =====  =               =  ===  == Rotating Media Statistics (rev 1) ==
0x03  0x008  4            3781  ---  Spindle Motor Power-on Hours
0x03  0x010  4            3780  ---  Head Flying Hours
0x03  0x018  4             163  ---  Head Load Events
0x03  0x020  4               0  ---  Number of Reallocated Logical Sectors
0x03  0x028  4               0  ---  Read Recovery Attempts
0x03  0x030  4               0  ---  Number of Mechanical Start Failures
0x04  =====  =               =  ===  == General Errors Statistics (rev 1) ==
0x04  0x008  4               0  ---  Number of Reported Uncorrectable Errors
0x04  0x010  4               0  ---  Resets Between Cmd Acceptance and Completion
0x05  =====  =               =  ===  == Temperature Statistics (rev 1) ==
0x05  0x008  1              38  ---  Current Temperature
0x05  0x010  1              41  N--  Average Short Term Temperature
0x05  0x018  1              39  N--  Average Long Term Temperature
0x05  0x020  1              46  ---  Highest Temperature
0x05  0x028  1              23  ---  Lowest Temperature
0x05  0x030  1              43  N--  Highest Average Short Term Temperature
0x05  0x038  1              25  N--  Lowest Average Short Term Temperature
0x05  0x040  1              42  N--  Highest Average Long Term Temperature
0x05  0x048  1              25  N--  Lowest Average Long Term Temperature
0x05  0x050  4               0  ---  Time in Over-Temperature
0x05  0x058  1              60  ---  Specified Maximum Operating Temperature
0x05  0x060  4               0  ---  Time in Under-Temperature
0x05  0x068  1               0  ---  Specified Minimum Operating Temperature
0x06  =====  =               =  ===  == Transport Statistics (rev 1) ==
0x06  0x008  4              17  ---  Number of Hardware Resets
0x06  0x010  4               3  ---  Number of ASR Events
0x06  0x018  4               0  ---  Number of Interface CRC Errors
0xff  =====  =               =  ===  == Vendor Specific Statistics (rev 1) ==
0xff  0x040  7              55  ---  Vendor Specific
0xff  0x048  7               0  ---  Vendor Specific
0xff  0x050  7               0  ---  Vendor Specific
0xff  0x058  7               0  ---  Vendor Specific
0xff  0x060  7               0  ---  Vendor Specific
0xff  0x068  7               0  ---  Vendor Specific
0xff  0x070  7               0  ---  Vendor Specific
0xff  0x078  7               0  ---  Vendor Specific
0xff  0x080  7           30014  ---  Vendor Specific
                                |||_ C monitored condition met
                                ||__ D supports DSN
                                |___ N normalized value

Pending Defects log (GP Log 0x0c)
No Defects Logged

SATA Phy Event Counters (GP Log 0x11)
ID      Size     Value  Description
0x0001  2            0  Command failed due to ICRC error
0x0002  2            0  R_ERR response for data FIS
0x0003  2            0  R_ERR response for device-to-host data FIS
0x0004  2            0  R_ERR response for host-to-device data FIS
0x0005  2            0  R_ERR response for non-data FIS
0x0006  2            0  R_ERR response for device-to-host non-data FIS
0x0007  2            0  R_ERR response for host-to-device non-data FIS
0x0008  2            0  Device-to-host non-data FIS retries
0x0009  2            8  Transition from drive PhyRdy to drive PhyNRdy
0x000a  2            4  Device-to-host register FISes sent due to a COMRESET
0x000b  2            0  CRC errors within host-to-device FIS
0x000d  2            0  Non-CRC errors within host-to-device FIS

**Comment by crgithubmoth** [comment]
Last entry has newest time but oldest temperature 
Current temp 38, not 41

**Comment by crgithubmoth** [comment]
To reproduce on a Red Pro,
Use hdparm -y to sleep drive, wait 10min, then smartctl -x ..

**Comment by chrfranke** [comment]
Likely a harmless firmware bug. Please provide output of `smartctl -r ioctl,2 -A -l scttemp ...` of an affected drive as an attachment.

> Do you have a ubuntu ppa for 7.3?

We do not provide packages for any Linux distro. Use https://launchpad.net/ubuntu/+source/smartmontools/+bugs to request a backport or use a recent CI build from https://builds.smartmontools.org/

**Comment by chrfranke** [comment]
This is likely a harmless firmware bug. No feedback from reporter.
