### ISSUE TITLE
TSxxxSSD420K not recognized

### ISSUE THREAD

**Issue by iurly** [smartmontools/smartmontools#20]
https://github.com/smartmontools/smartmontools/blob/457592c3560d50692c8d51ca714dd96d09fce06b/smartmontools/drivedb.h#L1712

I have a TS32GSSD420K/P1225CE which exposes the same identical interface, but is currently not recognized as such. I tried replacing `420I?` with `420K?` and that seems to work.

Any chance this could be added to the database?
Thank you!

**Comment by chrfranke** [comment]
Added in SVN commits r4845, r4846
