### ISSUE TITLE
NVME error logging

### ISSUE THREAD

**Issue by ixhamza** [smartmontools/smartmontools#208]
The error-log information in NVME serves as additional status information for command completion. Currently, `smartd` generates the log entry whenever there is an increment in the NVME `error_count`, regardless of the specific error type. However, these errors should be retrieved and processed by the original command originator and might not be significant for the user space.
For instance, I encountered a scenario where the Linux kernel was periodically executing `NVME_ID_CNS_CS_CTRL` command, which is unsupported by NVME version 1.4. As a result, `smartd` periodically displays an increment in the NVME error count like: `Device: /dev/nvme3n1, the number of Error Log entries increased from 14611 to 14620,` for the following error type that it should have ignored:
```
.................
 Entry[63]
.................
error_count     : 14644
sqid            : 0
cmdid           : 0x7009
status_field    : 0x6002(Invalid Field in Command: A reserved coded value or an unsupported value in a defined field)
phase_tag       : 0
parm_err_loc    : 0x28
lba             : 0xffffffffffffffff
nsid            : 0
vs              : 0
trtype          : The transport type is not indicated or the error is not transport related.
cs              : 0xffffffffffffffff
trtype_spec_info: 0
.................
```

**Comment by chrfranke** [comment]
Please retry with smartmontools 7.4, see [ticket 1222](https://www.smartmontools.org/ticket/1222).

**Comment by ixhamza** [comment]
Thank you, @chrfranke, for the swift response. I will use the latest version, thus closing this ticket.
