### ISSUE TITLE
WD Red Plus WD120EFBX not in smartctl database

### ISSUE THREAD

**Issue by nl6720** [smartmontools/smartmontools#210]
`WDC WD120EFBX-68B0EN0`

[smartctl-WDC-WD120EFBX.txt](https://github.com/smartmontools/smartmontools/files/12447818/smartctl-WDC-WD120EFBX.txt)
[Product Brief](https://documents.westerndigital.com/content/dam/doc-library/en_us/assets/public/western-digital/product/internal-drives/wd-red-plus-hdd/product-brief-western-digital-wd-red-plus-hdd.pdf)

**Comment by dipohl** [comment]
Added in [r5569](https://sourceforge.net/p/smartmontools/code/5569/) Thanks!
