### ISSUE TITLE
How to display "LU WWN Device ID" and SMART data of Transcend TS4TSSD230S?

### ISSUE THREAD

**Issue by KigenHasebe** [smartmontools/smartmontools#214]
Hello, thanks for Smartmontools.
I  built smart-montools-7.4.tar.gz, and applied the smartctl for Transcend SSD230S SSD's on USB thumb drive installed Ubuntu 22.04 LTS on Lenovo ThinkPad L540.
The smartctl works well for TS256GSSD230S,  but not well for TS512GSSD230S, TS1TSSD230S and TS4TSSD230S.
TS256GSSD230S, TS512GSSD230S and TS1TSSD230S are found in smartctl database 7.3/5528, that's OK.
TS4TSSD230S is not found in smartctl database 7.3/5528.
Smartctl displays "LU WWN Device ID" and SMART data for TS256GSSD230S, that's OK.
Nonetheless, for TS512GSSD230S,  TS1TSSD230S and TS4TSSD230S, smartctl display  "Information Section" and "General SMART Values",  but none of "LU WWN Device ID" and SMART data.
That is the problem. How to display "LU WWN Device ID" and SMART data of Transcend SSD's?
By the way,  TS256GSSD230S is conected to the internal SATA adapter of L540, but TS512GSSD230S,  TS1TSSD230S and TS4TSSD230S in a external SSD box are connected through an eSATA port of the box and an external PCI Express SATA card.

**Comment by chrfranke** [comment]
Please try this for the affected device:
```
smartctl --identify=wb /dev/... | grep -2 'World Wide Name'
````

**Comment by KigenHasebe** [comment]
Thanks for your quick reply.
The result of your advice follows:

@ TS256GSSD230S
# ./smartctl -i /dev/sda
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.2.0-34-generic] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Silicon Motion based SSDs
Device Model:     TS256GSSD230S
Serial Number:    F806712289
LU WWN Device Id: 5 7c3548 195b62fe1
Firmware Version: 02J0S7JA
User Capacity:    256,060,514,304 bytes [256 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
TRIM Command:     Available, deterministic, zeroed
Device is:        In smartctl database 7.3/5528
ATA Version is:   ACS-2 (minor revision not indicated)
SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Thu Oct  5 22:20:20 2023 JST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
---
# ./smartctl --identify=wb /dev/sda | grep -2 "World Wide Name"
   84     10          0   URG bit for WRITE STREAM (DMA) EXT supported [OBS-8]
   84      9          0   URG bit for READ STREAM (DMA) EXT supported [OBS-8]
   84      8          1   64-bit World Wide Name supported
   84      7          0   WRITE DMA QUEUED FUA EXT supported [OBS-ACS-2]
   84      6          1   WRITE DMA/MULTIPLE FUA EXT supported
--
   87     10          0   URG bit for WRITE STREAM (DMA) EXT supported [OBS-8]
   87      9          0   URG bit for READ STREAM (DMA) EXT supported [OBS-8]
   87      8          1   64-bit World Wide Name supported
   87      7          0   WRITE DMA QUEUED FUA EXT supported [OBS-ACS-2]
   87      6          1   WRITE DMA/MULTIPLE FUA EXT supported
--
  107      -     0x0000   Inter-seek delay for ISO 7779 acoustic testing

  108-111  -     .        World Wide Name
  108-111  .     0x57c3:5481:95b6:2fe1

@ TS512GSSD230S
# ./smartctl -i /dev/sdc
...
=== START OF INFORMATION SECTION ===
Model Family:     Silicon Motion based SSDs
Device Model:     TS512GSSD230S
Serial Number:    F686001685
Firmware Version: 81100040
...
Device is:        In smartctl database 7.3/5528
...
---
＃ ./smartctl --identify=wb /dev/sdc | grep -2 "World Wide Name"
   84     10          0   URG bit for WRITE STREAM (DMA) EXT supported [OBS-8]
   84      9          0   URG bit for READ STREAM (DMA) EXT supported [OBS-8]
   84      8          0   64-bit World Wide Name supported
   84      7          0   WRITE DMA QUEUED FUA EXT supported [OBS-ACS-2]
   84      6          1   WRITE DMA/MULTIPLE FUA EXT supported
--
   87     10          0   URG bit for WRITE STREAM (DMA) EXT supported [OBS-8]
   87      9          0   URG bit for READ STREAM (DMA) EXT supported [OBS-8]
   87      8          0   64-bit World Wide Name supported
   87      7          0   WRITE DMA QUEUED FUA EXT supported [OBS-ACS-2]
   87      6          1   WRITE DMA/MULTIPLE FUA EXT supported
--
  107      -     0x0000   Inter-seek delay for ISO 7779 acoustic testing

  108-111  -     0x00...  World Wide Name

  112-115  -     0x00...  Reserved

@ TS1TSSD230S
# ./smartctl -i /dev/sdc
...
=== START OF INFORMATION SECTION ===
Model Family:     Silicon Motion based SSDs
Device Model:     TS1TSSD230S
Serial Number:    H685750005
Firmware Version: 81100040
...
Device is:        In smartctl database 7.3/5528
...
---
# ./smartctl --identify=wb /dev/sdc | grep -2 "World Wide Name"
   84     10          0   URG bit for WRITE STREAM (DMA) EXT supported [OBS-8]
   84      9          0   URG bit for READ STREAM (DMA) EXT supported [OBS-8]
   84      8          0   64-bit World Wide Name supported
   84      7          0   WRITE DMA QUEUED FUA EXT supported [OBS-ACS-2]
   84      6          1   WRITE DMA/MULTIPLE FUA EXT supported
--
   87     10          0   URG bit for WRITE STREAM (DMA) EXT supported [OBS-8]
   87      9          0   URG bit for READ STREAM (DMA) EXT supported [OBS-8]
   87      8          0   64-bit World Wide Name supported
   87      7          0   WRITE DMA QUEUED FUA EXT supported [OBS-ACS-2]
   87      6          1   WRITE DMA/MULTIPLE FUA EXT supported
--
  107      -     0x0000   Inter-seek delay for ISO 7779 acoustic testing

  108-111  -     0x00...  World Wide Name

  112-115  -     0x00...  Reserved
  
@ TS4TSSD230S
# /smartctl -i /dev/sdc
...
=== START OF INFORMATION SECTION ===
Device Model:     TS4TSSD230S
Serial Number:    H786030006
Firmware Version: 81100040
...
Device is:        Not in smartctl database 7.3/5528
...
# ./smartctl --identify=wb /dev/sdc | grep -2 "World Wide Name"
   84     10          0   URG bit for WRITE STREAM (DMA) EXT supported [OBS-8]
   84      9          0   URG bit for READ STREAM (DMA) EXT supported [OBS-8]
   84      8          0   64-bit World Wide Name supported
   84      7          0   WRITE DMA QUEUED FUA EXT supported [OBS-ACS-2]
   84      6          1   WRITE DMA/MULTIPLE FUA EXT supported
--
   87     10          0   URG bit for WRITE STREAM (DMA) EXT supported [OBS-8]
   87      9          0   URG bit for READ STREAM (DMA) EXT supported [OBS-8]
   87      8          0   64-bit World Wide Name supported
   87      7          0   WRITE DMA QUEUED FUA EXT supported [OBS-ACS-2]
   87      6          1   WRITE DMA/MULTIPLE FUA EXT supported
--
  107      -     0x0000   Inter-seek delay for ISO 7779 acoustic testing

  108-111  -     0x00...  World Wide Name

  112-115  -     0x00...  Reserved

=================

**Comment by chrfranke** [comment]
> `Device Model:     TS4TSSD230S`
> `...`
> `  84      8          0   64-bit World Wide Name supported`

The device does not indicate WWN support. This is OK if `smartctl -i` prints `ATA Version is: ACS-2 ...` or earlier. Otherwise the firmware violates the advertised standard.

WWN was introduced in ATA-7 (2004) and was optional until ATA ACS-2  (2011).  It is mandatory since ATA ACS-3 (2013).

**Comment by KigenHasebe** [comment]
Thanks for the answer about WWN.

How about the remaining part "SMART data" of my problems.

> That is the problem. How to display "LU WWN Device ID" and SMART data of Transcend SSD's?

The addtional output from smartctl follows. "SMART data" are not displayed after the "START OF READ SMART DATA SECTION" line.

The problem is the same on TS512GSSD230S and TS1TSSD230S. Nevertheless, TS256GSSD230S is OK.  Setting "-s on -S on" for TS4TSSD230 etc. had been done on the time of my first posting. Setting "-o on" was not acceptted because of "SMART Automatic Timers not supported".

By the way, "Firmware Version" 02J0S7JA of TS256GSSD230S is different from 81100040 of TS512GSSD230S, TS1TSSD230S and TS4TSSD230S.

=========
# ./smartctl -a /dev/sdc
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.2.0-34-generic] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     TS4TSSD230S
Serial Number:    H786030006
Firmware Version: 81100040
User Capacity:    4,096,805,658,624 bytes [4.09 TB]
Sector Size:      512 bytes logical/physical
Device is:        Not in smartctl database 7.3/5528
ATA Version is:   ATA/ATAPI-7 (minor revision not indicated)
Local Time is:    Fri Oct  6 10:44:56 2023 JST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x00)	Offline data collection activity
					was never started.
					Auto Offline Data Collection: Disabled.
Total time to complete Offline
data collection: 		(    0) seconds.
Offline data collection
capabilities: 			 (0x00) 	Offline data collection not supported.
SMART capabilities:            (0x0000)	Automatic saving of SMART data		is not implemented.
Error logging capability:        (0x00)	Error logging NOT supported.
					No General Purpose Logging support.

SMART Error Log not supported

SMART Self-test Log not supported

Selective Self-tests/Logging not supported

The above only provides legacy SMART information - try 'smartctl -x' for more

# ./smartctl -x /dev/sdc
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.2.0-34-generic] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     TS4TSSD230S
Serial Number:    H786030006
Firmware Version: 81100040
User Capacity:    4,096,805,658,624 bytes [4.09 TB]
Sector Size:      512 bytes logical/physical
Device is:        Not in smartctl database 7.3/5528
ATA Version is:   ATA/ATAPI-7 (minor revision not indicated)
Local Time is:    Fri Oct  6 10:45:07 2023 JST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
AAM feature is:   Unavailable
APM level is:     254 (maximum performance)
Rd look-ahead is: Disabled
Write cache is:   Disabled
DSN feature is:   Unavailable
ATA Security is:  Disabled, frozen [SEC2]
Wt Cache Reorder: Unavailable

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x00)	Offline data collection activity
					was never started.
					Auto Offline Data Collection: Disabled.
Total time to complete Offline
data collection: 		(    0) seconds.
Offline data collection
capabilities: 			 (0x00) 	Offline data collection not supported.
SMART capabilities:            (0x0000)	Automatic saving of SMART data		is not implemented.
Error logging capability:        (0x00)	Error logging NOT supported.
					No General Purpose Logging support.

Read SMART Log Directory failed: scsi error badly formed scsi parameters

General Purpose Log Directory not supported

SMART Extended Comprehensive Error Log (GP Log 0x03) not supported

SMART Error Log not supported

SMART Extended Self-test Log (GP Log 0x07) not supported

SMART Self-test Log not supported

Selective Self-tests/Logging not supported

SCT Commands not supported

Device Statistics (GP/SMART Log 0x04) not supported

Pending Defects log (GP Log 0x0c) not supported

SATA Phy Event Counters (GP Log 0x11) not supported

**Comment by KigenHasebe** [comment]
Thanks for the answer.

Nevertheless, TS1TSSD230S is said to support "WWN 64 Bit" and to be supported by my Ubuntu 22.04.

+ https://www.runonpc.com/ts1tssd230s-driver-downloads-update/
Hard Disk TS1TSSD230S

Basic Parameters > Instruction
Command Set Support: Smart Commands, ... Smart Error Log, Smart Self Test, ... WWN 64 Bit

+ https://www.computerstore.co.za/TS1TSSD230S-Transcend-SSD230S-Series-1TB-2-5-SATA3-Buy-p-194888.php
TS1TSSD230S 2.5" SATA3 Notebook SSD Transcend
TS1TSSD230S information and overview

Specifications
Product Code	TS1TSSD230S
Operating System	... Linux Kernel 2.6.31 or later

The kernel of my Ubuntu and the driver are:

# cat /proc/version_signature
Ubuntu 6.2.0-34.34~22.04.1-generic 6.2.16
# lsmod | grep sata
sata_sil24             20480  0

**Comment by chrfranke** [comment]
Looks like the SATA driver does not properly implement ATA PASS-THROUGH. Please provide output of the following command as an attachment:
```
./smartctl -r ioctl,2 -H -A /dev/sdc
```

PS: Please don't paste smartctl output unchanged to comments. Use Markdown syntax for preformatted text instead or (for longer outputs) plaintext attachments.

**Comment by samm-git** [comment]
No reply from user, closing
