### ISSUE TITLE
/usr/sbin/update-smart-drivedb is missing on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by EmptyStackExn** [smartmontools/smartmontools#22]
Just the similar bug as in [bug #1574894 reported on Launchpad](https://bugs.launchpad.net/ubuntu/+source/smartmontools/+bug/1574894). How should we proceed to update database on Ubuntu ?
Thanks!

**Comment by samm-git** [comment]
This has nothing to do with smartmontools project. Please contact debian/ubuntu maintainers asking them why they doing such strange things or use another distro.

**Comment by w-barath** [comment]
Wild guess: debian admins figured that the stock script's updates would get obliterated by package updates so they removed it.   Ubuntu simply chose to follow the relative wisdom of their upstream package managers @debian.

For those who just want a simple solution to this conundrum, write the following to `/usr/local/bin/update-smart-drivedb`:

```
#!/bin/bash

(( UID == 0 )) || exec sudo "$0";

wget https://raw.githubusercontent.com/smartmontools/smartmontools/master/smartmontools/drivedb.h -O /var/lib/smartmontools/drivedb/drivedb.h
```

**Comment by samm-git** [comment]
true is that they did not provided alternate way to update but removed one we have. This is nothing but stupid. Anyway - up to Debian users what to do with that.

**Comment by w-barath** [comment]
If the stock script downloaded the `drivedh.h` file to a different location, ie `/var/cache/smartctl/drivedb.h` (which is the correct place for volatile updates), 
 and if the `smartctl` command looked first for the cached download before looking at the one in /var/lib (the correct place for non-volatile package data), then chances are the Debian admins wouldn't have felt the need to remove the script to prevent pathological behaviour on update.   So there's that...

**Comment by ciampix** [comment]
Why is this closed? Was the file inserted into the updated package or not? If not, why close the PR as if the problem simply vanished?

**Comment by samm-git** [comment]
@ciampix becaue this have nothing to do with smartmontools project. Open corresponding bug to the debian maintainer or install smartmontools from source.

**Comment by samm-git** [comment]
@ciampix just to make it very clear:

- Smartmontools provides mechanism to update drivedb.h from the internet
- Debian maintainers decided to exclude it without providing any kind of alternatives for the users or any kind of patches/suggestions to the upstream

We are not maintaining debian package, so all the issues needs to be opened in the debian tracker, not here.

**Comment by ciampix** [comment]
Ok but let me tell you that the very same problem affect (consequently) also gsmartcontrol that calls that missing file ... is there a bug report also for that? And why not fix it temporarily in the ubuntu package in the meantime?

**Comment by samm-git** [comment]
@ciampix because we are not maintainers of the ubuntu package. One more time - you opened bug in a wrong place.

**Comment by chrfranke** [comment]
Debian and Ubuntu re-added update-smart-drivedb recently, see [Launchpad Bug 1858121](https://bugs.launchpad.net/ubuntu/+source/smartmontools/+bug/1858121). Launchpad is the right place to request a backport to 18.04 LTS.

**Comment by ciampix** [comment]
Ok thank you for your patience.
