### ISSUE TITLE
sntrealtek: Read NVMe Identify Controller failed: scsi error unsupported field in scsi command

### ISSUE THREAD

**Issue by Neil-0609** [smartmontools/smartmontools#227]
PS C:\Users\LTG\Desktop\Release> .\smartctl.exe --scan
/dev/sda -d ata # /dev/sda, ATA device
/dev/sdb -d scsi # /dev/sdb, SCSI device
/dev/sdc -d sntrealtek # /dev/sdc [USB NVMe Realtek], NVMe device
PS C:\Users\LTG\Desktop\Release> .\smartctl.exe -a /dev/sdc -d sntrealtek
smartctl pre-7.4 (build date Nov 30 2023) [i686-pc-mingw32-w10-1903(64)] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

Smartctl open device: /dev/sdc [USB NVMe Realtek] failed: \\.\PhysicalDrive2: Open failed, Error=5
PS C:\Users\LTG\Desktop\Release> .\smartctl.exe -a /dev/sdc
smartctl pre-7.4 (build date Nov 30 2023) [i686-pc-mingw32-w10-1903(64)] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

Smartctl open device: /dev/sdc [USB NVMe Realtek] failed: \\.\PhysicalDrive2: Open failed, Error=5
PS C:\Users\LTG\Desktop\Release>

**Comment by chrfranke** [comment]
`Error=5` is `ERROR_ACCESS_DENIED` which usually means that you didn't run smartctl with administrator privileges.

**Comment by Neil-0609** [comment]
> `Error=5` is `ERROR_ACCESS_DENIED` which usually means that you didn't run smartctl with administrator privileges.

when i run smartctl with administrator privileges.error tip:
PS C:\Users\Administrator\Desktop\HDW> .\smartctl.exe --scan
/dev/sda -d ata # /dev/sda, ATA device
/dev/sdb -d ata # /dev/sdb, ATA device
/dev/sdc -d sntrealtek # /dev/sdc [USB NVMe Realtek], NVMe device
/dev/csmi0,3 -d ata # /dev/csmi0,3, ATA device
/dev/csmi0,5 -d ata # /dev/csmi0,5, ATA device
PS C:\Users\Administrator\Desktop\HDW> .\smartctl.exe -a /dev/sdc -d sntrealtek
smartctl pre-7.4 (build date Nov 30 2023) [i686-pc-mingw32-w10-22H2(64)] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

Read NVMe Identify Controller failed: scsi error unsupported field in scsi command

**Comment by chrfranke** [comment]
> Read NVMe Identify Controller failed: scsi error unsupported field in scsi command

This either means that this firmware does not support the RealTek specific NVMe pass-through SCSI command or no NVMe device is connected. If a SATA device is connected, try `-d sat`.

**Comment by Neil-0609** [comment]
> > Read NVMe Identify Controller failed: scsi error unsupported field in scsi command
> 
> This either means that this firmware does not support the RealTek specific NVMe pass-through SCSI command or no NVMe device is connected. If a SATA device is connected, try `-d sat`.

Thank you for your reply.It's OK.
