### ISSUE TITLE
smartmontools can't support monitor PMC series raid chip 

### ISSUE THREAD

**Issue by SilenceAdele** [smartmontools/smartmontools#228]
I am using the Inspur pm8204 raid card. This raid card uses the pmc raid card chip. When I execute the `smartctl --scan-open `command,the result show:
```
[root@node-1 ~]# smartctl --scan-open
/dev/sda -d scsi # /dev/sda, SCSI device
/dev/sdb -d sat # /dev/sdb [SAT], ATA device
/dev/sdc -d sat # /dev/sdc [SAT], ATA device
/dev/sdd -d scsi # /dev/sdd, SCSI device
/dev/sde -d scsi # /dev/sde, SCSI device
/dev/sdf -d scsi # /dev/sdf, SCSI device
/dev/nvme0 -d nvme # /dev/nvme0, NVMe device
```
I cannot query the interface type between the disk and the raid card, the number of the disk on the raid card. Therefore,I can not query the detailed parameters of physics disk by specifying the -d parameter.

**Comment by chrfranke** [comment]
RAID controller support is platform and controller specific and not included in `--scan*` in many cases. There is currently no PMC support on any platform, see the [related Wiki page](https://www.smartmontools.org/wiki/Supported_RAID-Controllers).
Adding this would require documentation and/or sample source code for the vendor specific pass-through API.

**Comment by SilenceAdele** [comment]
@chrfranke  thank you about your answer. I have some questions to ask you. The Inspur pm8204 raid card my be used hp smart array controller. Because it can be used ssacli command to query. I see the [smartmontools help doc ](https://manpages.ubuntu.com/manpages/noble/en/man8/smartctl.8.html)describe that specifying the -d  'cciss,N'. I want to know that the 'N' only support 0-15? It mean‘s max support to monitor 16 disks on the raid?

**Comment by SilenceAdele** [comment]
@chrfranke yeah, it‘s my pleasure. I see the [smartmontools help doc](https://manpages.ubuntu.com/manpages/noble/en/man8/smartctl.8.html) describe that hpsa or hpahcisr drivers under Linux can use the command of `smartctl -a -d cciss,0 /dev/sg2` to query. I have a question that `cciss,0` don't need to be consistent with `/dev/sg2`? In my practice，the result of executing the command of `smartctl -a -d cciss,0 /dev/sgX` are same. when change the 'N', the command execute results have different. By the way, Is 'N' related to 'X'? For example, the '/dev/sg0' stand the 'N' is 0?

**Comment by samm-git** [comment]
@SilenceAdele if you have single raid adapter result should be the same.

**Comment by SilenceAdele** [comment]
@samm-git  right, my node has one raid. Do you know that the 'N' related to 'X'? For example, the '/dev/sg0' stand the 'N' is 0?

**Comment by samm-git** [comment]
its not related in your case, N is device identifier from the controller itself.

**Comment by SilenceAdele** [comment]
hi @samm-git Do you have any other way to get the 'N'? I use `smartctl --scan-open` to query that cannot get it. This confused me for a long time.
