### ISSUE TITLE
smartd can't start on systems with unlimited fd limit

### ISSUE THREAD

**Issue by mhlavink** [smartmontools/smartmontools#235]
Hi,

we found an issue that smartd can't start if file limit is set to unlimited, like
DefaultLimitNOFILE = infinity in /etc/systemd/system.conf

the issue is that smartd tries to loop over all possible fds:
https://github.com/smartmontools/smartmontools/blob/master/smartmontools/smartd.cpp#L1465C1-L1466C1
https://github.com/smartmontools/smartmontools/blob/master/smartmontools/popen_as_ugid.cpp

infinity gets interpreted "only" as

```
# ulimit -a
...
open files                          (-n) 1073741816

```
but that is big enough to make smartd essentially stuck in a loop:
```
# systemctl start smartd
Job for smartd.service failed because a timeout was exceeded.
See "systemctl status smartd.service" and "journalctl -xeu smartd.service" for details.

```

```
# journalctl -xeu smartd.service
Jan 09 18:55:46 ... systemd[1]: smartd.service: start operation timed out. Terminating.
Jan 09 18:55:46 ... systemd[1]: smartd.service: Failed with result 'timeout'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ 
░░ The unit smartd.service has entered the 'failed' state with result 'timeout'.
Jan 09 18:55:46 ... systemd[1]: Failed to start Self Monitoring and Reporting Technology (SMART) Daemon.
░░ Subject: A start job for unit smartd.service has failed
░░ Defined-By: systemd
░░ 
░░ A start job for unit smartd.service has finished with a failure.
░░ 
░░ The job identifier is 797 and the job result is failed.
Jan 09 18:55:46 ... systemd[1]: smartd.service: Consumed 1min 29.871s CPU time.

```

issue is easy to find, but fixing it is a bit tricky. It's obviously no good to iterate over all possible FD. This became issue for others too, so after some long debate linux and freebsd implemented close_range(...) method. Unfortunately it is relatively recent. It was added 2019 which probably isn't old enough for all OSes. I'm not familiar with windows builds but seems that for cygwin close_range was added 2021. For older pre-2019 linux versions, effective approach is to check /proc/<pid>/fd/ but that obviously won't work for all OSes either

**Comment by samm-git** [comment]
Ti fix that we probably need to use `close_range()` on Linux and `closefrom()` on BSD, so we will have to check that in configure. And fallback to old way if none found.

**Comment by samm-git** [comment]
I personally think that a good enough approach is to use `close_range` on systems which support it and fallback to the old method (and issue a warning if the loop is over 64k) on systems that don't. I was also looking on OpenSSH approach (https://github.com/openssh/openssh-portable/blob/master/openbsd-compat/bsd-closefrom.c), but to me it seems to be too complex and hard to maintain.

**Comment by chrfranke** [comment]
A quick check for availability of `close_range()` on some VMs here:
- Debian 11: Unavailable, but `__SYSCALL(__NR_close_range, sys_close_range)` exists.
- Debian 12: Available, but requires `-D_GNU_SOURCE` (currently not used during build).
- FreeBSD 13.2: Available.
- Cygwin: Unavailable.
- Windows native: Not affected, different API.

As a quick fix, we could IMO safely keep the old method but limit the number of FDs to for example `min(sysconf(_SC_OPEN_MAX), 1024)`. `smartd` will never open so many FDs. Device nodes are closed before the next device is checked.

**Comment by mhlavink** [comment]
yes, it is tricky to do it both nice and support multiple platforms.

Is there a list of all officially supported OSes and their minimal version?

**Comment by samm-git** [comment]
> Is there a list of all officially supported OSes and their minimal version?
@mhlavink Not really, build/release testing is mostly done for Linux, FreeBSD, and Windows. Other platforms are supported mostly by contributors.

**Comment by samm-git** [comment]
In Ubuntu it is also covered by `__USE_GNU` define, and it comes from GNU libc source code (https://github.com/bminor/glibc/blob/master/posix/unistd.h#L1205), so likely would apply to all glibc distros. In Musl wrapper is missing, only the syscall is listed.

**Comment by chrfranke** [comment]
> Is there a list of all officially supported OSes and their minimal version?

All we have is an *unwritten rule*: *Don't add anything which may likely break builds with the default C++ toolchains of well-known LTS distributions.*
That is the reason why started using C++11 enhancments very late in 2021.

**Comment by chrfranke** [comment]
Another possible fix using the old method: Heuristically assume that the size of the gaps between (leaked) open FDs do not exceed some reasonably large value:

```cpp
void closefrom(int lowfd)
{
  int highfd = sysconf(_SC_OPEN_MAX);
  for (int i = lowfd, failed = 0; i < highfd && failed < 1024; i++)
    failed = (!close(i) ? 0 : failed + 1);
}
```

**Comment by chrfranke** [comment]
Proposed patch, not fully tested yet:
```diff
Index: configure.ac
===================================================================
--- configure.ac	(revision 5576)
+++ configure.ac	(working copy)
@@ -118,10 +118,6 @@
   *-*-netbsd*|*-*-openbsd*)
     AC_CHECK_HEADERS([dev/ata/atavar.h])
     ;;
-  *-*-mingw*)
-    # Older MinGW-w64 (5.0.3) require -lwinpthread
-    AC_SEARCH_LIBS([clock_gettime], [winpthread])
-    ;;
 esac
 
 # Checks for typedefs, and compiler characteristics.
@@ -132,6 +128,16 @@
 AC_CHECK_FUNCS([getopt_long], [need_getopt_long=no], [need_getopt_long=yes])
 AM_CONDITIONAL(NEED_GETOPT_LONG, [test "$need_getopt_long" = "yes"])
 
+case "$host_os" in
+  mingw*)
+    # Older MinGW-w64 (5.0.3) require -lwinpthread
+    AC_SEARCH_LIBS([clock_gettime], [winpthread])
+    ;;
+  *)
+    AC_CHECK_FUNCS([close_range])
+    ;;
+esac
+
 # Check byte ordering (defines WORDS_BIGENDIAN)
 AC_C_BIGENDIAN
 
Index: popen_as_ugid.cpp
===================================================================
--- popen_as_ugid.cpp	(revision 5576)
+++ popen_as_ugid.cpp	(working copy)
@@ -67,10 +67,21 @@
   if (!pid) { // Child
     // Do not inherit any unneeded file descriptors
     fclose(fp);
-    for (int i = sysconf(_SC_OPEN_MAX); --i >= 0; ) {
+    int i;
+    for (i = 0; i <= pd[1] || i <= sd[1]; i++) {
       if (i == pd[1] || i == sd[1])
         continue;
       close(i);
+    } 
+    int open_max = sysconf(_SC_OPEN_MAX);
+#ifdef HAVE_CLOSE_RANGE
+    if (close_range(i, open_max - 1, 0))
+#endif
+    {
+      // Limit number of close() calls under the assumption that there
+      // are no large gaps between open FDs
+      for (int failed = 0; i < open_max && failed < 1024; i++)
+        failed = (!close(i) ? 0 : failed + 1);
     }
 
     FILE * fc = 0;
Index: smartd.cpp
===================================================================
--- smartd.cpp	(revision 5576)
+++ smartd.cpp	(working copy)
@@ -1462,8 +1462,16 @@
   }
 
   // close any open file descriptors
-  for (int i = sysconf(_SC_OPEN_MAX); --i >= 0; )
-    close(i);
+  int open_max = sysconf(_SC_OPEN_MAX);
+#ifdef HAVE_CLOSE_RANGE
+  if (close_range(0, open_max - 1, 0))
+#endif
+  {
+    // Limit number of close() calls under the assumption that there
+    // are no large gaps between open FDs
+    for (int i = 0, failed = 0; i < open_max && failed < 1024; i++)
+      failed = (!close(i) ? 0 : failed + 1);
+  }
   
   // redirect any IO attempts to /dev/null and change to root directory
   int fd = open("/dev/null", O_RDWR);
```

`-D_GNU_SOURCE` is not needed on Debian 12 because it is apparently implicitly set for C++ only.
Code duplication is intentional because I want to keep the `popen_as_ugid` module self-contained.
Any yes, the fallback to old method if `close_range()` fails is possibly too paranoid :-)

**Comment by mhlavink** [comment]
compile and works, tested on Fedora 39 and RHEL9

**Comment by samm-git** [comment]
@chrfranke btw, your check is not that paranoic. Libc just provides wrapper to syscall, without any checks. So in case of some [strange] case with older kernel and newer libc it could fail )

**Comment by chrfranke** [comment]
Applied in [r5579](https://www.smartmontools.org/changeset/5579) (ce275a8). Thanks for testing!
