### ISSUE TITLE
drivedb.h: HP EG001200JWJNK

### ISSUE THREAD

**Issue by MikaelKW** [smartmontools/smartmontools#238]
I'm not able to see S.M.A.R.T. data even tho it reports it as supported by the drive.

Output:

smartctl 7.2 2020-12-30 r5155 [x86_64-w64-mingw32-w10-b19044] (sf-7.2-1)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               HP
Product:              EG001200JWJNK
Revision:             HPD2
Compliance:           SPC-4
User Capacity:        1 200 243 695 616 bytes [1,20 TB]
Logical block size:   512 bytes
Rotation Rate:        10000 rpm
Form Factor:          2.5 inches
Logical Unit id:      0x50000398d8114a61
Serial number:        8850A0FTFF4F
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Mon Jan 22 21:44:16 2024 WEST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled
Read Cache is:        Enabled
Writeback Cache is:   Disabled

=== START OF READ SMART DATA SECTION ===
SMART Health Status: DATA CHANNEL IMPENDING FAILURE DATA ERROR RATE TOO HIGH [asc=5d, ascq=32]

Current Drive Temperature:     43 C
Drive Trip Temperature:        60 C

Accumulated power on time, hours:minutes 40114:54
Manufactured in week 31 of year 2018
Specified cycle count over device lifetime:  50000
Accumulated start-stop cycles:  61
Specified load-unload count over device lifetime:  600000
Accumulated load-unload cycles:  61
Elements in grown defect list: 81

**Comment by chrfranke** [comment]
There are no drive database entries for SAS and NVMe drives, see also the [FAQ](https://www.smartmontools.org/wiki/FAQ#MySCSISASdriveisnotinthesmartctlsmartddatabase).
