### ISSUE TITLE
smartd.conf manpage "-O" directive

### ISSUE THREAD

**Issue by marceloneil** [smartmontools/smartmontools#24]
I found what might be a typo in the manpage:
https://github.com/smartmontools/smartmontools/blob/20d0ed6f90353ce567003e495a018f7cd5ad149e/smartmontools/smartd.conf.5.in#L929-L930
I see no instances of an `-O` directive in the manpage or sourcecode, and I believe it should be replaced with the `-U` and `-W` directives.

**Comment by chrfranke** [comment]
Thanks for catching this 15 year old typo :-)
https://www.smartmontools.org/changeset/4918

**Comment by marceloneil** [comment]
My pleasure 😄
