### ISSUE TITLE
Wrong data on Crucial BX500

### ISSUE THREAD

**Issue by easymoney322** [smartmontools/smartmontools#243]
Hello,
I have two SSDs with different firmware versions and sizes.
By using smartctl_device, ones model_family isn't recognized.
500GB BX500: unknown, CT500BX500SSD1, M6CR061 
240GB BX500: Crucial/Micron Client SSDs, CT240BX500SSD1, M6CR056

Both of these drives came with these firmwares and were bought in last 3 months or so. 

But whats important, is that (at least) temperature data on 240Gb is wrong:
S.M.A.R.T.  194 reports 111669215238 (raw) or +80-something degrees C, when this drive is expected to have +0-25*C (Ambient is 0-11*C).

111669215238 is 0x1A 00 01 00 06, and I would assume that the 0x06 is an actual temperature.

The 500GB version have smart 194 raw 163210199071 (0x26 00 16 00 1F), and the value of 69 (nice), but I also doubt its correct.
It should be noted that both of these drives may or may not have different controllers SM2258XT/SM2259XT.

Both of these drives fall under the same regexp in drivedb.h file. The SMART 194 line is commented out for them https://github.com/smartmontools/smartmontools/blob/11415ee0b9d5f4a22ddfb3722fdfb05e72372a03/smartmontools/drivedb.h#L525  

I'm using prebuilt SmartCTL of last version for Windows.

The Database must be wrong. How shall I contribute?

**Comment by chrfranke** [comment]
Please provide complete `smartctl -x` outputs of both drives.

**Comment by easymoney322** [comment]
I've checked smartctl -x output and it looks fine, and it seems like I've found the problem.

The output of smartctl --json --xall /dev/sdX is
```
{
        "id": 194,
        "name": "Temperature_Celsius",
        "value": 34,
        "worst": 34,
        "thresh": 0,
        "when_failed": "",
        "flags": {
          "value": 34,
          "string": "-O---K ",
          "prefailure": false,
          "updated_online": true,
          "performance": false,
          "error_rate": false,
          "event_count": false,
          "auto_keep": true
        },
        "raw": {
          "value": 201864052770,
          "string": "34 (Min/Max 9/47)"
        }
},
```
      
for most of SSDs I've checked, and
 ```
{
        "id": 194,
        "name": "Temperature_Celsius",
        "value": 108,
        "worst": 102,
        "thresh": 0,
        "when_failed": "",
        "flags": {
          "value": 34,
          "string": "-O---K ",
          "prefailure": false,
          "updated_online": true,
          "performance": false,
          "error_rate": false,
          "event_count": false,
          "auto_keep": true
        },
        "raw": {
          "value": 35,
          "string": "35"
        }
 } 
```
for HDD.


Since I've been exporting data with https://github.com/prometheus-community/smartctl_exporter to collect data, it used raw.value, instead of raw.string:
```
smartctl_device_attribute{attribute_flags_long="updated_online,auto_keep",attribute_flags_short="-O---K",attribute_id="194",attribute_name="Temperature_Celsius",attribute_value_type="raw",device="sda"} 35

smartctl_device_attribute{attribute_flags_long="updated_online,auto_keep",attribute_flags_short="-O---K",attribute_id="194",attribute_name="Temperature_Celsius",attribute_value_type="raw",device="sdb"} 2.01864052771e+11

smartctl_device_attribute{attribute_flags_long="updated_online,auto_keep",attribute_flags_short="-O---K",attribute_id="194",attribute_name="Temperature_Celsius",attribute_value_type="thresh",device="sda"} 0

smartctl_device_attribute{attribute_flags_long="updated_online,auto_keep",attribute_flags_short="-O---K",attribute_id="194",attribute_name="Temperature_Celsius",attribute_value_type="thresh",device="sdb"} 0

smartctl_device_attribute{attribute_flags_long="updated_online,auto_keep",attribute_flags_short="-O---K",attribute_id="194",attribute_name="Temperature_Celsius",attribute_value_type="value",device="sda"} 108

smartctl_device_attribute{attribute_flags_long="updated_online,auto_keep",attribute_flags_short="-O---K",attribute_id="194",attribute_name="Temperature_Celsius",attribute_value_type="value",device="sdb"} 35

smartctl_device_attribute{attribute_flags_long="updated_online,auto_keep",attribute_flags_short="-O---K",attribute_id="194",attribute_name="Temperature_Celsius",attribute_value_type="worst",device="sda"} 102

smartctl_device_attribute{attribute_flags_long="updated_online,auto_keep",attribute_flags_short="-O---K",attribute_id="194",attribute_name="Temperature_Celsius",attribute_value_type="worst",device="sdb"} 35
```

So it looks like Value is fine for SSDs, and wrong for HDDs, while Raw.Value is fine for HDDs, but wrong for SSDs. 

This probably should be fixed on the smartctl_exporter's end, but I wonder if there is any reason why RAW.Value should mismatch Raw.String?

**Comment by chrfranke** [comment]
The `raw.value` is the 48-bit value as reported by the drive, the byte order may be modified by a drive database entry in rare cases. The `raw.string` is the same string as printed in the plaintext output (see `--json=o`). The format is selected by a drive database entry. This will not be changed.

For temperature info, use this instead:
```
  "temperature": {
    "current": 22,
    "power_cycle_min": 19,
    "power_cycle_max": 24,
    "lifetime_min": 15,
    "lifetime_max": 40,
    "op_limit_max": 70,
    "op_limit_min": 0,
    "limit_min": 0,
    "limit_max": 70
  },
```
The above output is independent from protocol ((S)ATA, SCSI/SAS, NVMe). For SATA devices, it collects information also from _SCT Status_ and/or _Device Statistics_ which are vendor independent and usually more reliable than the legacy (and obsoleted by T13) vendor specific _ATA SMART Attributes_.

**Comment by easymoney322** [comment]
Thanks for the advice!
