### ISSUE TITLE
Adding support for ASM225CM chipset [Darwin]

### ISSUE THREAD

**Issue by hexbus** [smartmontools/smartmontools#254]
This [chipset](https://www.asmedia.com.tw/product/d32yq49sx2YR9Jg6/d1Eyq85QN8GhBwRC) is a USB 3.2 Gen1 to SATA 6Gbps bridge solution that is being used in many popular USB external housings (like [this family](https://www.inateck.com/products/type-c-2-5-hard-drive-enclosure-usb-3-0-external-hard-drive-case-fe2004c) - 2.5 and 3.5 SATA externals).

Can this potentially be added to Smartmontools?

Thanks for all your hard work!

**Comment by chrfranke** [comment]
Does is work with `-d sat` ?
USB-Id ?

**Comment by hexbus** [comment]
Hi, @chrfranke -

`
Diskutil list:
/dev/disk11 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *16.0 TB    disk11
   1:                        EFI EFI                     209.7 MB   disk11s1
   2:                  Apple_HFS External                16.0 TB    disk11s2

Smartctl -d sat:
familyroomdesk:bin Jon$ ./smartctl /dev/disk11 -d sat
smartctl 7.4 2023-08-01 r5530 [Darwin 23.3.0 arm64] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/disk11: Type 'sat+...': Not a device of type 'scsi'
=======> VALID ARGUMENTS ARE: ata, scsi[+TYPE], nvme[,NSID], sat[,auto][,N][+TYPE], usbasm1352r,N, usbcypress[,X], usbjmicron[,p][,x][,N], usbprolific, usbsunplus, sntasmedia, sntjmicron[,NSID], sntrealtek, jmb39x[-q],N[,sLBA][,force][+TYPE], jms56x,N[,sLBA][,force][+TYPE], auto, test <=======

Use smartctl -h to get a usage summary

USB info from system profiler:
ASM225CM:

  Product ID:	0x55aa
  Vendor ID:	0x174c  (ASMedia Technology Inc.)
  Version:	1.00
  Serial Number:	AAAABBBBCCCC0003
  Speed:	Up to 5 Gb/s
  Manufacturer:	Inateck
  Location ID:	0x02600000 / 25
  Current Available (mA):	900
  Current Required (mA):	0
  Extra Operating Current (mA):	0
`

**Comment by chrfranke** [comment]
> smartctl 7.4 2023-08-01 r5530 [Darwin 23.3.0 arm64] (local build)

macOS/Darwin still lacks SCSI pass-through support which is required to access ATA SMART data behind USB bridges. This cannot be fixed in `smartctl`. It may work via the OS-X-SAT-SMART-Driver, see the [USB Wiki page](https://www.smartmontools.org/wiki/USB).

>   Product ID:	0x55aa
>   Vendor ID:	0x174c  (ASMedia Technology Inc.)

Newer ASMedia bridges usually support SAT.

**Comment by samm-git** [comment]
yep, this is true, macOS provides only very high-level API to access SMART data, so the driver is the only way to access it in macOS. Another possible workaround is to setup a VM with Linux or BSD and temporarily pass the USB device to it for diagnostic.
