### ISSUE TITLE
Add [0x05e3:0x0761 (0x2402)] to known USB Bridges

### ISSUE THREAD

**Issue by Uglymotha** [smartmontools/smartmontools#259]
Bus 002 Device 004: ID 7825:a2a4 Other World Computing External SATA Hard Drive Adapter cable PA023U3

/dev/sde: Unknown USB bridge [0x05e3:0x0761 (0x2402)]
Please specify device type with the -d option.

It works fine with -d sat
sudo smartctl -d sat -i /dev/sdd
```
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.8.5-ugly-linux-0.7.19-intel] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Seagate Barracuda 2.5 5400
Device Model:     ST2000LM015-2E8174
Serial Number:    WDZJZRRP
LU WWN Device Id: 5 000c50 0bf4c9b35
Firmware Version: SDM1
User Capacity:    2.000.398.934.016 bytes [2,00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
Device is:        In smartctl database 7.3/5528
ATA Version is:   ACS-3 T13/2161-D revision 3b
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Wed Apr 17 11:41:24 2024 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

**Comment by chrfranke** [comment]
Added in [r5621](https://www.smartmontools.org/changeset/5621) (33cbfe8), [r5622](https://www.smartmontools.org/changeset/5622).

**Comment by bw4518** [comment]
Another one,

```
ID 7825:a2a4 Other World Computing External SATA Hard Drive Adapter cable PA023U3

/dev/sda: Unknown USB bridge [0x7825:0xa2a4 (0x4101)]
Please specify device type with the -d option.
```

Also works with smartctl -d sat -i /dev/sda (is that a correct device type?)

**Comment by chrfranke** [comment]
> Another one,
> 
> ```
> ID 7825:a2a4 Other World Computing External SATA Hard Drive Adapter cable PA023U3
> ...
> ```

This issue has been closed in Oct 2024 and the above USB Id is completely different. Please create a new issue.
