### ISSUE TITLE
Bad block HOWTO: wrong LUKS offset

### ISSUE THREAD

**Issue by jwilk** [smartmontools/smartmontools#261]
https://www.smartmontools.org/wiki/BadBlockHowto#ext2ext3firstexample says:

> If you are hosting your ext filesystem in a LUKS-encrypted container, the "(L-S)" part of the formula becomes "(L-S-4096)". LUKS reserves 16MB at the beginning of the partition, so the actual location where your filesystem starts is 4096 4K blocks after the partition starts.

But *L* and *S* are the numbers of sectors. 16 MiB is 32768 sectors, not 4096.

**Comment by chrfranke** [comment]
Fixed in [version 34](https://www.smartmontools.org/wiki/BadBlockHowto?action=diff&version=34). Thanks!
