### ISSUE TITLE
smartmontools.service failed for eMMC devices

### ISSUE THREAD

**Issue by fti-sfuke** [smartmontools/smartmontools#271]
#### Description
I am using `smartmontools` on Debian Bookworm, and it works perfectly for standard SATA and NVMe devices. However, it fails on eMMC devices with a "No Device to monitor" error.

#### Observed Behavior
The `smartmontools` service (`smartd`) fails to start and logs an error message indicating that there is no device to monitor for eMMC devices.

#### Error Message

```
root@buildhost:~# systemctl status smartmontools.service
× smartmontools.service - Self Monitoring and Reporting Technology (SMART) Daemon
     Loaded: loaded (/lib/systemd/system/smartmontools.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-06-19 22:25:19 JST; 14h ago
       Docs: man:smartd(8)
             man:smartd.conf(5)
    Process: 63563 ExecStart=/usr/sbin/smartd -n $smartd_opts (code=exited, status=17)
   Main PID: 63563 (code=exited, status=17)
     Status: "No devices to monitor"
        CPU: 21ms

Jun 19 22:25:19 buildhost smartd[63563]: smartd 7.3 2022-02-28 r5338 [x86_64-linux-6.5.0-0.deb12.4-amd64] (local build)
Jun 19 22:25:19 buildhost smartd[63563]: Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org
Jun 19 22:25:19 buildhost smartd[63563]: Opened configuration file /etc/smartd.conf
Jun 19 22:25:19 buildhost smartd[63563]: Drive: DEVICESCAN, implied '-a' Directive on line 21 of file /etc/smartd.conf
Jun 19 22:25:19 buildhost smartd[63563]: Configuration file /etc/smartd.conf was parsed, found DEVICESCAN, scanning devices
Jun 19 22:25:19 buildhost smartd[63563]: In the system's table of devices NO devices found to scan
Jun 19 22:25:19 buildhost smartd[63563]: Unable to monitor any SMART enabled devices. Try debug (-d) option. Exiting...
Jun 19 22:25:19 buildhost systemd[1]: smartmontools.service: Main process exited, code=exited, status=17/n/a
Jun 19 22:25:19 buildhost systemd[1]: smartmontools.service: Failed with result 'exit-code'.
Jun 19 22:25:19 buildhost systemd[1]: Failed to start smartmontools.service - Self Monitoring and Reporting Technology (SMART) Daemon.

```

```
root@buildhost:~# lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
mmcblk0      179:0    0   233G  0 disk
├─mmcblk0p1  179:1    0   512M  0 part /boot/efi
├─mmcblk0p2  179:2    0    18G  0 part /
├─mmcblk0p3  179:3    0     6G  0 part /opt/scorer/log
└─mmcblk0p4  179:4    0 208.5G  0 part /var/lib/docker
                                       /mnt/data
mmcblk0boot0 179:256  0     4M  1 disk
mmcblk0boot1 179:512  0     4M  1 disk
```

```
root@buildhost:~# sudo smartctl -i /dev/mmcblk0
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.5.0-0.deb12.4-amd64] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/mmcblk0: Unable to detect device type
Please specify device type with the -d option.

Use smartctl -h to get a usage summary

```

#### Questions
1. Is eMMC supported by `smartmontools`?
   - If yes, how can I configure `smartd` to properly monitor eMMC devices?
2.  Is there any flag or configuration option in `smartd` to automatically check if a storage device is supported and skip unsupported 
    devices to prevent the service from failing?

#### Additional Information
- **OS**: Debian Bookworm
- **smartmontools Version**: 7.3
- **eMMC Device**: `/dev/mmcblk0`

**Comment by chrfranke** [comment]
This is as expected because `/dev/mmcblk*` are not checked by `DEVICESCAN` (or `smartctl --scan`). I don't know which kind of diagnostic information such devices provide (if any). Therefore there is no eMMC specific support.

If diagnostics exists, the kernel device driver may map it SCSI (or ATA) world.
Please try `smartctl -d scsi -x /dev/mmc...` (or `smartctl -d sat -x /dev/mmc...`).

Do you have any specs or sample diagnostic information from such a device, for example from a vendor specific tool?

Use `smartd -q never` or `smartd -q nodev0` to prevent that smartd stops with an error status if no supported devices were found. See `man smartd` for details. Note that `-q nodev0` requires smartmontools 7.4 if used with systemd.

**Comment by fti-sfuke** [comment]
Hi @chrfranke 
Thanks for the details.

> I don't know which kind of diagnostic information such devices provide (if any). Therefore there is no eMMC specific support.
>  Do you have any specs or sample diagnostic information from such a device, for example from a vendor specific tool?

Regarding the diagnostic information from devices like eMMC, our current setup with the [MeLE Quieter 4C - N100 Mini PC](https://store.mele.cn/products/mele-quieter-4c-n100-3-4ghz-fanless-mini-computer-lpddr4x-win11-hdmi-4k-wi-fi-5-bt-5-1-usb-3-2-2-usb-2-0-1-type-c-1) includes 128GB eMMC onboard storage with Debian 12 installed on it. If necessary, we can request specifications or sample diagnostic information from the vendor regarding this storage device.

I attempted to gather storage device details using various methods but found it labeled as a generic product:
```
root@DEB-Quieter4-8QPH4F310P430477:~# lsblk -o NAME,SIZE,MODEL
NAME           SIZE MODEL
mmcblk0      115.2G
├─mmcblk0p1    512M
├─mmcblk0p2     18G
├─mmcblk0p3      6G
└─mmcblk0p4   90.7G
mmcblk0boot0     4M
mmcblk0boot1     4M
```
```
root@DEB-Quieter4-8QPH4F310P430477:~# udevadm info --query=all --name=/dev/mmcblk0
P: /devices/pci0000:00/0000:00:1a.0/mmc_host/mmc0/mmc0:0001/block/mmcblk0
M: mmcblk0
R: 0
U: block
T: disk
D: b 179:0
N: mmcblk0
L: 0
S: disk/by-id/mmc-A3A562_0x07c925e1
S: disk/by-diskseq/1
Q: 1
E: DEVPATH=/devices/pci0000:00/0000:00:1a.0/mmc_host/mmc0/mmc0:0001/block/mmcblk0
E: DEVNAME=/dev/mmcblk0
E: DEVTYPE=disk
E: DISKSEQ=1
E: MAJOR=179
E: MINOR=0
E: SUBSYSTEM=block
E: USEC_INITIALIZED=1065902
E: ID_SERIAL=0x07c925e1
E: ID_NAME=A3A562
E: ID_PART_TABLE_UUID=015eee0a-6961-45cc-bb01-76a517b39cd8
E: ID_PART_TABLE_TYPE=gpt
E: DEVLINKS=/dev/disk/by-id/mmc-A3A562_0x07c925e1 /dev/disk/by-diskseq/1
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

root@DEB-Quieter4-8QPH4F310P430477:~#
```

> Please try smartctl -d scsi -x /dev/mmc... (or smartctl -d sat -x /dev/mmc...).

Here are the results of these commands:
```
root@DEB-Quieter4-8QPH4F310P430477:~# smartctl -d scsi -x /dev/mmcblk0
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.5.0-0.deb12.4-amd64] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

Standard Inquiry (36 bytes) failed [Invalid argument]
Retrying with a 64 byte Standard Inquiry
Standard Inquiry (64 bytes) failed [Invalid argument]
A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.
root@DEB-Quieter4-8QPH4F310P430477:~#
```


```
root@DEB-Quieter4-8QPH4F310P430477:~# smartctl -d sat -x /dev/mmcblk0
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.5.0-0.deb12.4-amd64] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

Read Device Identity failed: Invalid argument

If this is a USB connected device, look at the various --device=TYPE variants
A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.
root@DEB-Quieter4-8QPH4F310P430477:~#

```

> Use smartd -q never or smartd -q nodev0 to prevent that smartd stops with an error status if no supported devices were found 

The addition of smartd_opts `-q never` has resolved my issue. I have added it to /etc/default/smartmontools.

```
# Defaults for smartmontools initscript (/etc/init.d/smartmontools)
# This is a POSIX shell fragment

# List of devices you want to explicitly enable S.M.A.R.T. for
# Not needed (and not recommended) if the device is monitored by smartd
#enable_smart="/dev/hda /dev/hdb"

# uncomment to pass additional options to smartd on startup
#smartd_opts="--interval=1800"
smartd_opts="-A /var/log/smartd/ -i 600 -q never"

```

With these changes, I am now able to restart the smartd service without any failures.
```
root@DEB-Quieter4-8QPH4F310P430477:~# systemctl restart smartd
root@DEB-Quieter4-8QPH4F310P430477:~# systemctl status smartd
● smartmontools.service - Self Monitoring and Reporting Technology (SMART) Daemon
     Loaded: loaded (/lib/systemd/system/smartmontools.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-07-05 00:30:55 JST; 8s ago
       Docs: man:smartd(8)
             man:smartd.conf(5)
   Main PID: 1185552 (smartd)
     Status: "Next check of 0 devices will start at 00:40:55"
      Tasks: 1 (limit: 629145)
     Memory: 1.1M
        CPU: 17ms
     CGroup: /system.slice/smartmontools.service
             └─1185552 /usr/sbin/smartd -n -A /var/log/smartd/ -i 600 -q never

Jul 05 00:30:55 DEB-Quieter4-8QPH4F310P430477 systemd[1]: Starting smartmontools.service - Self Monitoring and Reporting Technology (SMART) Daemon...
Jul 05 00:30:55 DEB-Quieter4-8QPH4F310P430477 smartd[1185552]: smartd 7.3 2022-02-28 r5338 [x86_64-linux-6.5.0-0.deb12.4-amd64] (local build)
Jul 05 00:30:55 DEB-Quieter4-8QPH4F310P430477 smartd[1185552]: Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org
Jul 05 00:30:55 DEB-Quieter4-8QPH4F310P430477 smartd[1185552]: Opened configuration file /etc/smartd.conf
Jul 05 00:30:55 DEB-Quieter4-8QPH4F310P430477 smartd[1185552]: Drive: DEVICESCAN, implied '-a' Directive on line 21 of file /etc/smartd.conf
Jul 05 00:30:55 DEB-Quieter4-8QPH4F310P430477 smartd[1185552]: Configuration file /etc/smartd.conf was parsed, found DEVICESCAN, scanning devices
Jul 05 00:30:55 DEB-Quieter4-8QPH4F310P430477 smartd[1185552]: In the system's table of devices NO devices found to scan
Jul 05 00:30:55 DEB-Quieter4-8QPH4F310P430477 smartd[1185552]: Monitoring 0 ATA/SATA, 0 SCSI/SAS and 0 NVMe devices
Jul 05 00:30:55 DEB-Quieter4-8QPH4F310P430477 systemd[1]: Started smartmontools.service - Self Monitoring and Reporting Technology (SMART) Daemon.
root@DEB-Quieter4-8QPH4F310P430477:~#

```
![image](https://github.com/smartmontools/smartmontools/assets/87641643/950ac004-0253-4d49-8097-14b2f0337318)


Please review and let me know if there are any significant findings from this information

**Comment by chrfranke** [comment]
> ```
> root@DEB-Quieter4-8QPH4F310P430477:~# smartctl -d scsi -x /dev/mmcblk0
> ... 
> Standard Inquiry (36 bytes) failed [Invalid argument]
> Retrying with a 64 byte Standard Inquiry
> Standard Inquiry (64 bytes) failed [Invalid argument]
> ...
> root@DEB-Quieter4-8QPH4F310P430477:~# smartctl -d sat -x /dev/mmcblk0
> ...
> Read Device Identity failed: Invalid argument
> ```

The above shows that the kernel driver does not emulate standard SCSI behavior.

Various freely available specs from eMMC vendors suggest that eMMC does not offer any standard diagnostic support like temperature, bad block count, power on time, ...

> The addition of smartd_opts `-q never` has resolved my issue. I have added it to /etc/default/smartmontools.
> 
> ```
> ...
> smartd_opts="-A /var/log/smartd/ -i 600 -q never"
> ```
> 
> With these changes, I am now able to restart the smartd service without any failures.
> 
> ```
> ...
>      Status: "Next check of 0 devices will start at 00:40:55"
> ...
> ```

This solves the issue. Smartd now runs as a useless service which wakes up each 10min to do nothing :-)

Note that you need to restart or reload smartd if new (USB-)devices are connected and you want to monitor these.
If this never happens, I would suggest to simply disable the service: `systemctl disable smartd`.
