### ISSUE TITLE
static analysis scan issues (scsicmds.cpp, farmprint.cpp)

### ISSUE THREAD

**Issue by mhlavink** [smartmontools/smartmontools#272]
Hi,

we've run static analysis on smartmontools which found a few issues:

### 1) out of bound access at scsicmds.cpp

scsiModePageOffset()
checks for:
`1810:   if ((offset + 2) > len) {`

which should prevent out of bound access at
scsi_IsWarningEnabled()
`1905:   return (iecp->raw_curr[offset + 2] & EWASC_ENABLE) ? 1 : 0;`

but the check allows for offset + 2 == len which actually accesses (len+1)th element. 
Seems like the check should be if ((offset + 2) >= len)

same issue happens on a few more places, for example at:
scsi_IsExceptionControlEnabled()
`1891:    return (iecp->raw_curr[offset + 2] & DEXCPT_ENABLE) ? 0 : 1;`

scsiSetControlGLTSD()
`3015:    if (enabled == (buff[offset + 2] & 2))`

and more.

=====================

### 2) another out of bound access at scsicmds.cpp
scsicmds.cpp : supported_vpd_pages::supported_vpd_pages()

`203:    unsigned char b[0xfc] = {};`
size of b is 252
```
208:    int n = sizeof(pages);
209:    if (num_valid > n)
210:        num_valid = n;
```

sizeof(pages) is 256, so num_valid can be up to 256

`211:    memcpy(pages, b + 4, num_valid);`

tries to copy up to 256 (num_valid) bytes from b array of size 252, where b+4 points to 248 size array.

Seems like the 4 bytes difference has been considered, but b was made 4 bytes smaller instead of 4 bytes larger

=====================

### 3) strlen on uninitialized string at farmprint.cpp

farmprint.cpp : ataPrintFarmLog()

```
175:   char modelNumber[sizeof(farmLog.driveInformation.modelNumber) + 1];
177:   farm_format_id_string(&modelNumber[strlen(modelNumber)]
```
strlen() is called with the modelNumber which is not initialized

**Comment by chrfranke** [comment]
Thanks for these reports.

> ### 1) out of bound access at scsicmds.cpp
> ### 2) another out of bound access at scsicmds.cpp

Both reports forwarded to owner of smartmontools SCSI code.

> ### 3) strlen on uninitialized string at farmprint.cpp

Thanks. I obviously missed that during review of the [original code provided by seagate](../../../Seagate/smartmontools/blob/21452c5005c76ea764d8ef299471149477b76173/smartmontools/farmprint.cpp#L173).

**Comment by chrfranke** [comment]
> ### 3) strlen on uninitialized string at farmprint.cpp

Fixed by [r5617](https://www.smartmontools.org/changeset/5617) (e37bd13) from PR #285.

**Comment by chrfranke** [comment]
> ### 1) out of bound access at scsicmds.cpp
> ### 2) another out of bound access at scsicmds.cpp

Fixed by [r5618](https://www.smartmontools.org/changeset/5618) (466fc71).

If possible, please check whether this silences the related static analysis report.

**Comment by mhlavink** [comment]
I rerun static analyzer again and these issues are fixed.
