### ISSUE TITLE
Please add support for Unknown USB bridge [0x1352:0xa006 (0x100)]

### ISSUE THREAD

**Issue by hawui1** [smartmontools/smartmontools#283]
root@nas2:~# smartctl -a /dev/sdb
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.1.0-25-amd64] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sdb: Unknown USB bridge [0x1352:0xa006 (0x100)]
Please specify device type with the -d option.

By using -d sat it works

root@nas2:~# smartctl -a /dev/sdb -d sat
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.1.0-25-amd64] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     MB010000GWAYN
Serial Number:    1DGHXAAZ
LU WWN Device Id: 5 000cca 26cc73bed
Firmware Version: HPG5
User Capacity:    10,000,831,348,736 bytes [10.0 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        Not in smartctl database 7.3/5610
ATA Version is:   ACS-3 T13/2161-D revision 5
SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Wed Sep 25 14:18:03 2024 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
(...)

Thanks in advance for your help

**Comment by hawui1** [comment]
The above USB Bridge is used in a TerraMaster D2-320 USB 3.2 (Gen2) 10 Gbps 2-Bay enclosure

**Comment by chrfranke** [comment]
Option `-a` only checks legacy 24-bit ATA commands. Please provide output of `smartctl -d sat -x -a ...` for full test coverage.

**Comment by hawui1** [comment]
Here is the complete output of the command: smartctl -a -x /dev/sdb -d sat

smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.1.0-25-amd64] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     MB010000GWAYN
Serial Number:    1DGHXAAZ
LU WWN Device Id: 5 000cca 26cc73bed
Firmware Version: HPG5
User Capacity:    10,000,831,348,736 bytes [10.0 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        Not in smartctl database 7.3/5610
ATA Version is:   ACS-3 T13/2161-D revision 5
SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Wed Oct  2 14:41:41 2024 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
AAM feature is:   Unavailable
APM feature is:   Unavailable
Rd look-ahead is: Enabled
Write cache is:   Enabled
DSN feature is:   Unavailable
ATA Security is:  Unavailable
Wt Cache Reorder: Unavailable

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x82)	Offline data collection activity
					was completed without error.
					Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(   93) seconds.
Offline data collection
capabilities: 			 (0x5b) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Suspend Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					No Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   2) minutes.
Extended self-test routine
recommended polling time: 	 (1148) minutes.
SCT capabilities: 	       (0x0025)	SCT Status supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
  1 Raw_Read_Error_Rate     POSR--   100   100   016    -    0
  2 Throughput_Performance  POS---   133   100   054    -    97
  3 Spin_Up_Time            PO----   153   100   024    -    415 (Average 443)
  5 Reallocated_Sector_Ct   PO--CK   100   100   005    -    0
  7 Seek_Error_Rate         POSR--   100   100   067    -    0
  8 Seek_Time_Performance   P-S---   128   100   020    -    18
  9 Power_On_Hours          -O--CK   093   093   000    -    53867
 10 Spin_Retry_Count        PO--C-   100   100   060    -    0
 22 Helium_Level            PO---K   100   100   025    -    100
169 Unknown_Attribute       PO--CK   100   100   099    -    0
180 Unknown_HDD_Attribute   PO-RCK   100   100   098    -    0
194 Temperature_Celsius     -O---K   162   120   000    -    37 (Min/Max 18/50)
196 Reallocated_Event_Count PO--CK   100   100   000    -    0
                            ||||||_ K auto-keep
                            |||||__ C event count
                            ||||___ R error rate
                            |||____ S speed/performance
                            ||_____ O updated online
                            |______ P prefailure warning

General Purpose Log Directory Version 1
SMART           Log Directory Version 1 [multi-sector log support]
Address    Access  R/W   Size  Description
0x00       GPL,SL  R/O      1  Log Directory
0x03       GPL     R/O      1  Ext. Comprehensive SMART error log
0x04       GPL     R/O    256  Device Statistics log
0x04       SL      R/O    255  Device Statistics log
0x07       GPL     R/O      1  Extended self-test log
0x08       GPL     R/O      2  Power Conditions log
0x09           SL  R/W      1  Selective self-test log
0x0c       GPL     R/O   5501  Pending Defects log
0x0d       GPL     R/O      7  LPS Mis-alignment log
0x10       GPL     R/O      1  NCQ Command Error log
0x11       GPL     R/O      1  SATA Phy Event Counters log
0x16       GPL     R/W      1  Out Of Band Management Control log
0x17       GPL     -        1  Reserved for Serial ATA
0x30       GPL     R/O      9  IDENTIFY DEVICE data log
0x80       GPL     R/W     16  Host vendor specific log
0x81-0x9f  GPL,SL  R/W     16  Host vendor specific log
0xb5           SL  VS       1  Device vendor specific log
0xb6       GPL     VS     127  Device vendor specific log
0xd0       GPL     VS       1  Device vendor specific log
0xd7       GPL     VS       1  Device vendor specific log
0xe0       GPL,SL  R/W      1  SCT Command/Status
0xe1       GPL,SL  R/W      1  SCT Data Transfer

SMART Extended Comprehensive Error Log Version: 1 (1 sectors)
Device Error Count: 12 (device log contains only the most recent 4 errors)
	CR     = Command Register
	FEATR  = Features Register
	COUNT  = Count (was: Sector Count) Register
	LBA_48 = Upper bytes of LBA High/Mid/Low Registers ]  ATA-8
	LH     = LBA High (was: Cylinder High) Register    ]   LBA
	LM     = LBA Mid (was: Cylinder Low) Register      ] Register
	LL     = LBA Low (was: Sector Number) Register     ]
	DV     = Device (was: Device/Head) Register
	DC     = Device Control Register
	ER     = Error register
	ST     = Status register
Powered_Up_Time is measured from power on, and printed as
DDd+hh:mm:SS.sss where DD=days, hh=hours, mm=minutes,
SS=sec, and sss=millisec. It "wraps" after 49.710 days.

Error 12 [3] occurred at disk power-on lifetime: 53770 hours (2240 days + 10 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER -- ST COUNT  LBA_48  LH LM LL DV DC
  -- -- -- == -- == == == -- -- -- -- --
  04 -- 51 00 00 00 00 00 00 00 00 00 00  Error: ABRT

  Commands leading to the command that caused the error were:
  CR FEATR COUNT  LBA_48  LH LM LL DV DC  Powered_Up_Time  Command/Feature_Name
  -- == -- == -- == == == -- -- -- -- --  ---------------  --------------------
  b0 00 d5 00 01 00 00 00 c2 4f 01 00 00     00:00:40.943  SMART READ LOG
  ef 00 03 00 46 00 00 00 c2 4f 06 00 00     00:00:40.933  SET FEATURES [Set transfer mode]
  ef 00 03 00 0c 00 00 00 c2 4f 06 00 00     00:00:40.835  SET FEATURES [Set transfer mode]
  ec 00 d5 00 01 00 00 00 c2 4f 06 00 00     00:00:40.834  IDENTIFY DEVICE
  b0 00 d5 00 01 00 00 00 c2 4f 06 00 04     00:00:40.810  SMART READ LOG

Error 11 [2] occurred at disk power-on lifetime: 53770 hours (2240 days + 10 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER -- ST COUNT  LBA_48  LH LM LL DV DC
  -- -- -- == -- == == == -- -- -- -- --
  04 -- 51 00 00 00 00 00 00 00 00 00 00  Error: ABRT

  Commands leading to the command that caused the error were:
  CR FEATR COUNT  LBA_48  LH LM LL DV DC  Powered_Up_Time  Command/Feature_Name
  -- == -- == -- == == == -- -- -- -- --  ---------------  --------------------
  b0 00 d5 00 01 00 00 00 c2 4f 06 00 00     00:00:40.810  SMART READ LOG
  b0 00 d5 00 01 00 00 00 c2 4f 00 00 00     00:00:40.809  SMART READ LOG
  b0 00 db 00 f8 00 00 00 c2 4f 00 00 00     00:00:40.808  SMART EN/DISABLE AUTO OFFLINE [NS (SFF-8035i)]
  b0 00 d1 00 01 00 00 00 c2 4f 01 00 00     00:00:40.789  SMART READ ATTRIBUTE THRESHOLDS [OBS-4]
  b0 00 d0 00 01 00 00 00 c2 4f 00 00 00     00:00:40.785  SMART READ DATA

Error 10 [1] occurred at disk power-on lifetime: 53749 hours (2239 days + 13 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER -- ST COUNT  LBA_48  LH LM LL DV DC
  -- -- -- == -- == == == -- -- -- -- --
  04 -- 51 00 00 00 00 00 00 00 00 00 00  Error: ABRT

  Commands leading to the command that caused the error were:
  CR FEATR COUNT  LBA_48  LH LM LL DV DC  Powered_Up_Time  Command/Feature_Name
  -- == -- == -- == == == -- -- -- -- --  ---------------  --------------------
  b0 00 d5 00 01 00 00 00 c2 4f 01 00 00     00:00:40.190  SMART READ LOG
  ef 00 03 00 46 00 00 00 c2 4f 06 00 00     00:00:40.186  SET FEATURES [Set transfer mode]
  ef 00 03 00 0c 00 00 00 c2 4f 06 00 00     00:00:40.087  SET FEATURES [Set transfer mode]
  ec 00 d5 00 01 00 00 00 c2 4f 06 00 00     00:00:40.087  IDENTIFY DEVICE
  b0 00 d5 00 01 00 00 00 c2 4f 06 00 04     00:00:40.062  SMART READ LOG

Error 9 [0] occurred at disk power-on lifetime: 53749 hours (2239 days + 13 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER -- ST COUNT  LBA_48  LH LM LL DV DC
  -- -- -- == -- == == == -- -- -- -- --
  04 -- 51 00 00 00 00 00 00 00 00 00 00  Error: ABRT

  Commands leading to the command that caused the error were:
  CR FEATR COUNT  LBA_48  LH LM LL DV DC  Powered_Up_Time  Command/Feature_Name
  -- == -- == -- == == == -- -- -- -- --  ---------------  --------------------
  b0 00 d5 00 01 00 00 00 c2 4f 06 00 00     00:00:40.061  SMART READ LOG
  b0 00 d5 00 01 00 00 00 c2 4f 00 00 00     00:00:40.060  SMART READ LOG
  b0 00 db 00 f8 00 00 00 c2 4f 00 00 00     00:00:40.059  SMART EN/DISABLE AUTO OFFLINE [NS (SFF-8035i)]
  b0 00 d1 00 01 00 00 00 c2 4f 01 00 00     00:00:40.040  SMART READ ATTRIBUTE THRESHOLDS [OBS-4]
  b0 00 d0 00 01 00 00 00 c2 4f 00 00 00     00:00:40.037  SMART READ DATA

SMART Error Log not supported

SMART Extended Self-test Log Version: 1 (1 sectors)
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%     53828         -
# 2  Short offline       Completed without error       00%     53827         -
# 3  Short offline       Completed without error       00%     53826         -
# 4  Short offline       Completed without error       00%     53825         -
# 5  Short offline       Completed without error       00%     53824         -
# 6  Short offline       Completed without error       00%     53823         -
# 7  Short offline       Completed without error       00%     53822         -
# 8  Short offline       Completed without error       00%     53821         -
# 9  Short offline       Completed without error       00%     53820         -
#10  Short offline       Completed without error       00%     53819         -
#11  Short offline       Completed without error       00%     53818         -
#12  Short offline       Completed without error       00%     53817         -
#13  Short offline       Completed without error       00%     53816         -
#14  Short offline       Completed without error       00%     53815         -
#15  Short offline       Completed without error       00%     53814         -
#16  Short offline       Completed without error       00%     53813         -
#17  Short offline       Completed without error       00%     53812         -
#18  Short offline       Completed without error       00%     53811         -
#19  Short offline       Completed without error       00%     53810         -

SMART Self-test Log not supported

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.

SCT Status Version:                  3
SCT Version (vendor specific):       256 (0x0100)
Device State:                        Active (0)
Current Temperature:                    37 Celsius
Power Cycle Min/Max Temperature:     36/40 Celsius
Lifetime    Min/Max Temperature:     18/50 Celsius
Specified Max Operating Temperature:    60 Celsius
Under/Over Temperature Limit Count:   0/0

SCT Temperature History Version:     2
Temperature Sampling Period:         1 minute
Temperature Logging Interval:        1 minute
Min/Max recommended Temperature:      0/60 Celsius
Min/Max Temperature Limit:           -40/70 Celsius
Temperature History Size (Index):    128 (30)

Index    Estimated Time   Temperature Celsius
  31    2024-10-02 12:34    37  ******************
 ...    ..(  7 skipped).    ..  ******************
  39    2024-10-02 12:42    37  ******************
  40    2024-10-02 12:43    36  *****************
  41    2024-10-02 12:44    36  *****************
  42    2024-10-02 12:45    36  *****************
  43    2024-10-02 12:46    37  ******************
  44    2024-10-02 12:47    36  *****************
  45    2024-10-02 12:48    37  ******************
  46    2024-10-02 12:49    37  ******************
  47    2024-10-02 12:50    37  ******************
  48    2024-10-02 12:51    36  *****************
 ...    ..(  5 skipped).    ..  *****************
  54    2024-10-02 12:57    36  *****************
  55    2024-10-02 12:58    37  ******************
  56    2024-10-02 12:59    36  *****************
 ...    ..(  7 skipped).    ..  *****************
  64    2024-10-02 13:07    36  *****************
  65    2024-10-02 13:08    37  ******************
  66    2024-10-02 13:09    36  *****************
 ...    ..( 16 skipped).    ..  *****************
  83    2024-10-02 13:26    36  *****************
  84    2024-10-02 13:27    37  ******************
  85    2024-10-02 13:28    37  ******************
  86    2024-10-02 13:29    36  *****************
  87    2024-10-02 13:30    37  ******************
  88    2024-10-02 13:31    37  ******************
  89    2024-10-02 13:32    36  *****************
 ...    ..(  5 skipped).    ..  *****************
  95    2024-10-02 13:38    36  *****************
  96    2024-10-02 13:39    37  ******************
  97    2024-10-02 13:40    36  *****************
  98    2024-10-02 13:41    37  ******************
  99    2024-10-02 13:42    36  *****************
 ...    ..( 14 skipped).    ..  *****************
 114    2024-10-02 13:57    36  *****************
 115    2024-10-02 13:58    37  ******************
 116    2024-10-02 13:59    36  *****************
 ...    ..(  3 skipped).    ..  *****************
 120    2024-10-02 14:03    36  *****************
 121    2024-10-02 14:04    37  ******************
 122    2024-10-02 14:05    36  *****************
 123    2024-10-02 14:06    36  *****************
 124    2024-10-02 14:07    37  ******************
 125    2024-10-02 14:08    37  ******************
 126    2024-10-02 14:09    36  *****************
 127    2024-10-02 14:10    36  *****************
   0    2024-10-02 14:11    37  ******************
   1    2024-10-02 14:12    37  ******************
   2    2024-10-02 14:13    37  ******************
   3    2024-10-02 14:14    36  *****************
   4    2024-10-02 14:15    36  *****************
   5    2024-10-02 14:16    37  ******************
 ...    ..( 11 skipped).    ..  ******************
  17    2024-10-02 14:28    37  ******************
  18    2024-10-02 14:29    36  *****************
  19    2024-10-02 14:30    37  ******************
  20    2024-10-02 14:31    36  *****************
  21    2024-10-02 14:32    37  ******************
 ...    ..(  8 skipped).    ..  ******************
  30    2024-10-02 14:41    37  ******************

SCT Error Recovery Control command not supported

Device Statistics (GP Log 0x04)
Page  Offset Size        Value Flags Description
0x01  =====  =               =  ===  == General Statistics (rev 1) ==
0x01  0x008  4              49  ---  Lifetime Power-On Resets
0x01  0x010  4           53867  ---  Power-on Hours
0x01  0x018  6    142746558722  ---  Logical Sectors Written
0x01  0x020  6       628786228  ---  Number of Write Commands
0x01  0x028  6    898119519849  ---  Logical Sectors Read
0x01  0x030  6      2132506902  ---  Number of Read Commands
0x01  0x038  6    193924647500  ---  Date and Time TimeStamp
0x03  =====  =               =  ===  == Rotating Media Statistics (rev 1) ==
0x03  0x008  4           53857  ---  Spindle Motor Power-on Hours
0x03  0x010  4           53857  ---  Head Flying Hours
0x03  0x018  4             656  ---  Head Load Events
0x03  0x020  4               0  ---  Number of Reallocated Logical Sectors
0x03  0x028  4             612  ---  Read Recovery Attempts
0x03  0x030  4               0  ---  Number of Mechanical Start Failures
0x04  =====  =               =  ===  == General Errors Statistics (rev 1) ==
0x04  0x008  4               1  ---  Number of Reported Uncorrectable Errors
0x04  0x010  4              16  ---  Resets Between Cmd Acceptance and Completion
0x05  =====  =               =  ===  == Temperature Statistics (rev 1) ==
0x05  0x008  1              37  ---  Current Temperature
0x05  0x010  1              36  N--  Average Short Term Temperature
0x05  0x018  1              37  N--  Average Long Term Temperature
0x05  0x020  1              50  ---  Highest Temperature
0x05  0x028  1              18  ---  Lowest Temperature
0x05  0x030  1              49  N--  Highest Average Short Term Temperature
0x05  0x038  1              25  N--  Lowest Average Short Term Temperature
0x05  0x040  1              38  N--  Highest Average Long Term Temperature
0x05  0x048  1              25  N--  Lowest Average Long Term Temperature
0x05  0x050  4               0  ---  Time in Over-Temperature
0x05  0x058  1              60  ---  Specified Maximum Operating Temperature
0x05  0x060  4               0  ---  Time in Under-Temperature
0x05  0x068  1               0  ---  Specified Minimum Operating Temperature
0x06  =====  =               =  ===  == Transport Statistics (rev 1) ==
0x06  0x008  4               0  ---  Number of Hardware Resets
0x06  0x010  4              11  ---  Number of ASR Events
0x06  0x018  4               0  ---  Number of Interface CRC Errors
0xff  =====  =               =  ===  == Vendor Specific Statistics (rev 1) ==
                                |||_ C monitored condition met
                                ||__ D supports DSN
                                |___ N normalized value

Pending Defects log (GP Log 0x0c)
No Defects Logged

SATA Phy Event Counters (GP Log 0x11)
ID      Size     Value  Description
0x0001  2            0  Command failed due to ICRC error
0x0002  2            0  R_ERR response for data FIS
0x0003  2            0  R_ERR response for device-to-host data FIS
0x0004  2            0  R_ERR response for host-to-device data FIS
0x0005  2            0  R_ERR response for non-data FIS
0x0006  2            0  R_ERR response for device-to-host non-data FIS
0x0007  2            0  R_ERR response for host-to-device non-data FIS
0x0008  2            0  Device-to-host non-data FIS retries
0x0009  2            0  Transition from drive PhyRdy to drive PhyNRdy
0x000a  2            1  Device-to-host register FISes sent due to a COMRESET
0x000b  2            0  CRC errors within host-to-device FIS
0x000d  2            0  Non-CRC errors within host-to-device FIS

**Comment by hawui1** [comment]
I include the full output of the command smartctl -a -x /dev/sdb -d sat
[output.txt](https://github.com/user-attachments/files/17229463/output.txt)

**Comment by hawui1** [comment]
Great ! Thanks chrfranke !
