### ISSUE TITLE
Can't get 202 attribute to be ignored

### ISSUE THREAD

**Issue by Phurion** [smartmontools/smartmontools#293]
My smartd.conf file is below.

`DEVICESCAN -I 202 -t -R 5 -o on -S on -l error -l selftest -f -s (S/../.././01) -m XX@XXXXXX -M daily`

I still get 202 emails even though I have -I 202. I'm not sure what I'm doing wrong.

OS: Ubuntu 24.04.01 LTS (noble)
Version: smartctl 7.4

Email:
This message was generated by the smartd daemon running on:

   host name:  xxxx
   DNS domain: xxxxxx

The following warning/error was logged by the smartd daemon:

Device: /dev/sdx [SAT], Failed SMART usage Attribute: 202 Percent_Lifetime_Remain.

Device info:
xxxxxx

For details see host's SYSLOG.

You can also use the smartctl utility for further investigation.
The original message about this issue was sent at xxxxx Another message will be sent in 24 hours if the problem persists.

**Comment by chrfranke** [comment]
```
$ man smartd.conf
...
   -f     [ATA only] Check for 'failure' of any Usage Attributes. ...
   ...
   -i ID  [ATA  only] Ignore device Attribute number ID when checking for failure of Usage Attributes. ...
   ...
   -I ID  [ATA only] Ignore device Attribute ID when tracking changes in the Attribute  values. ...
...
```
The _failure_ (`VALUE <= THRESH`) check of all usage attributes is enabled with `-f`. Using `-I 202` only suppresses LOG_INFO messages of attribute changes. Add  `-i 202` to suppress the failure check which triggers the email,

**Comment by Phurion** [comment]
I knew it had to be something simple. Thank you so much ^__^
