### ISSUE TITLE
please add USB bridge

### ISSUE THREAD

**Issue by gilbahat** [smartmontools/smartmontools#32]
root@meadow:~# smartctl -a /dev/sdd
smartctl 6.6 2017-11-05 r4594 [x86_64-linux-5.0.0-13-generic] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sdd: Unknown USB bridge [0x8564:0x7000 (0x8000)]
Please specify device type with the -d option.

root@meadow:~# smartctl -d sat -a /dev/sdd
smartctl 6.6 2017-11-05 r4594 [x86_64-linux-5.0.0-13-generic] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     HGST HCC545050A7E630
Serial Number:    RBH50AAH1VK1BP
LU WWN Device Id: 5 000cca 8aada2922
Firmware Version: GR2OA300
User Capacity:    500,107,862,016 bytes [500 GB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ATA8-ACS T13/1699-D revision 6
SATA Version is:  SATA 2.6, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Fri May  3 11:55:55 2019 IDT
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

**Comment by chrfranke** [comment]
https://www.smartmontools.org/changeset/4921
https://www.smartmontools.org/changeset/4924
