### ISSUE TITLE
smartd not writing attributes (-A) for NVMe devices on FreeBSD

### ISSUE THREAD

**Issue by openspork** [smartmontools/smartmontools#33]
Steps to reproduce:

smartd.conf:
`DEVICESCAN -a -o on -S on -s (S/../.././02|L/../../6/03) -W 4,35,40 -m root`

smartd flags:
`smartd -c /usr/local/etc/smartd.conf -p /var/run/smartd.pid -A /var/log/smartd/ -i 600`

`/var/log/smartd/` contains all my sata drives, but not my NVMe drives.

If I do `smartclt -a /dev/nvme0` I get output, and smartd sends alerts as normal (temp etc.) for the NVMe devices.

Thanks!

**Comment by samm-git** [comment]
Hi, this is currently not implemented for NVME, only for SCSI and SATA. I need to think how to make it properly, as there is no such things as attributes in nvme. However, writing some historical data sounds as a good think. I will create a ticket in upstream trac

**Comment by openspork** [comment]
Thanks @samm-git, good to know this isn't broken but is rather not a feature yet.

I actually already created a trac ticket at: https://www.smartmontools.org/ticket/1190

It would be nice to track the historical data that is available (temp, as I mentioned, is one such example).

**Comment by samm-git** [comment]
Ok, lets handle in the upstream trac. I was implementing that for SCSI already, should be to +- trivial to implement it for the NVMe

**Comment by samm-git** [comment]
temp, also r/w stat to see if something is killing ssd, etc
