### ISSUE TITLE
trac server is not sending confirmation email

### ISSUE THREAD

**Issue by foresto** [smartmontools/smartmontools#37]
The trac server at www.smartmontools.org is not sending confirmation email for new accounts, so people attempting to sign up in order to report bugs are left without the privileges to do so.

Relatedly, the recaptcha implementation on the signup page is a royal pain. My experience went something like this:
* Complete the signup form
* Submit
* Get error page complaining that a captcha wasn't completed.
* Look for captcha
* Discover that it was a recaptcha, served by google.com, and was therefore (correctly) blocked by normal web browser safety measures
* Whilelist google.com scripts for smartmontools.org pages
* Resubmit
* Discover that recaptcha requires gstatic.com scripts as well
* Whilelist gstatic.com scripts for smartmontools.org pages
* Resubmit
* Discover that recaptcha requires google.com frame permissions as well
* Whilelist google.com frames for smartmontools.org pages
* Resubmit
* Discover that recaptcha requires google.com media permissions as well
* Whilelist google.com media for smartmontools.org pages
* Resubmit
* Click the images expected by recaptcha, and the Verify button
* Get another batch of captcha images to click
* Click the images expected by recaptcha, and the Verify button, again
* Get yet another batch of captcha images to click
* Click the images expected by recaptcha, but wait a couple of seconds before clicking Verify
* Notice that, given a few seconds, each clicked captcha image slowly fades out, and then a new image slowly fades in to replace it
* Continue clicking each new recaptcha image, waiting for the painfully slow replacements to appear, and clicking those as well, for maybe ten or fifteen more seconds
* Curse at the people who made it such a huge pain just to submit a bug report
* Finally reach the point where no new images are fading in, and click Verify
* Submit the signup form
* Get error page complaining that a password is required, despite the fact that I already entered it twice, because this infuriating procedure deleted the one that I entered
* Enter my new password again, twice
* Go through recaptcha hell *again*
* Submit the signup form
* Get message directing me to verify my email address when the verification email arrives
* Wait 10-15 minutes, with no such email arriving
* Test my email address, and find that it is accepting and delivering messages just fine, and quite quickly
* Conclude that trac never sent the verification email
* Realize that I just spent something like 20-25 minutes just trying to work my way past all the obstacles that someone put in the way of reporting a simple bug
* Give up

I eventually found this github site. I hope someone on the team reads it. I don't have the endurance to keep tangling with your trac server.

**Comment by foresto** [comment]
Update: The confirmation email did eventually arrive. If the timestamps in the header are correct, it took around 2-3 hours. :(

**Comment by samm-git** [comment]
@foresto please share via headers with me (could be anonymized) to see where the problem was. Most likely it was a mailserver greylisting and in that case there is nothing we can do about it

**Comment by foresto** [comment]
I'm afraid the message is already purged. I'll try to remember to keep it if I go through the process again.
