### ISSUE TITLE
CSMI support for AMD chipsets?

### ISSUE THREAD

**Issue by Shine-** [smartmontools/smartmontools#39]
CrystalDiskInfo has added support for AMD RAIDXpert2 a few days ago. Any chance this can be added to smartmontools as well?

Here's the pull for CrystalDiskInfo:
https://github.com/hiyohiyo/CrystalDiskInfo/pull/28

**Comment by chrfranke** [comment]
Please provide output of `smartctl -r ioctl,2 --scan`.

**Comment by Shine-** [comment]
Here you go (using current snapshot 7.1 r4949):

`C:\Windows\system32>smartctl -r ioctl,2 --scan
 \\.\PhysicalDrive0: successfully opened
  IOCTL_STORAGE_QUERY_PROPERTY returns:
    Vendor:   "AMD-RAID"
    Product:  "Samsung SSD 840 "
    Revision: "DXM0"
    Removable: No
    BusType:   0x08
  SMART_GET_VERSION failed, Error=1117
 \\.\Scsi0:: successfully opened
  IOCTL_SCSI_MINIPORT(CC_CSMI_1) succeeded, bytes returned: 204
CSMI_SAS_DRIVER_INFO:
  Name:        "rcraid"
  Description: "AMD-RAID Controller [storport] Device Driver"
  Revision:    9.2
  IOCTL_SCSI_MINIPORT(CC_CSMI_20) succeeded, bytes returned: 2080
CSMI_SAS_PHY_INFO: NumberOfPhys=0
 \\.\Scsi1:: successfully opened
  IOCTL_SCSI_MINIPORT(CC_CSMI_1) failed, Error=31
  \\.\Scsi0:: successfully opened
  nvme probe failed: NVME_PASS_THROUGH failed, Error=1117
  \\.\Scsi1:: successfully opened
  nvme probe failed: NVME_PASS_THROUGH failed, Error=31
  \\.\Scsi2:: Open failed, Error=2
  \\.\Scsi3:: Open failed, Error=2
  \\.\Scsi4:: Open failed, Error=2
  \\.\Scsi5:: Open failed, Error=2
  \\.\Scsi6:: Open failed, Error=2
  \\.\Scsi7:: Open failed, Error=2
  \\.\Scsi8:: Open failed, Error=2
  \\.\Scsi9:: Open failed, Error=2
  \\.\Scsi10:: Open failed, Error=2
  \\.\Scsi11:: Open failed, Error=2
  \\.\Scsi12:: Open failed, Error=2
  \\.\Scsi13:: Open failed, Error=2
  \\.\Scsi14:: Open failed, Error=2
  \\.\Scsi15:: Open failed, Error=2
  \\.\Scsi16:: Open failed, Error=2
  \\.\Scsi17:: Open failed, Error=2
  \\.\Scsi18:: Open failed, Error=2
  \\.\Scsi19:: Open failed, Error=2
  \\.\Scsi20:: Open failed, Error=2
  \\.\Scsi21:: Open failed, Error=2
  \\.\Scsi22:: Open failed, Error=2
  \\.\Scsi23:: Open failed, Error=2
  \\.\Scsi24:: Open failed, Error=2
  \\.\Scsi25:: Open failed, Error=2
  \\.\Scsi26:: Open failed, Error=2
  \\.\Scsi27:: Open failed, Error=2
  \\.\Scsi28:: Open failed, Error=2
  \\.\Scsi29:: Open failed, Error=2
  \\.\Scsi30:: Open failed, Error=2
  \\.\Scsi31:: Open failed, Error=2
/dev/sda -d scsi # /dev/sda, SCSI device`

The SSD it detects is currently the only (non-RAIDed) drive. I could add more drives and build a RAID if needed.

**Comment by chrfranke** [comment]
> CSMI_SAS_PHY_INFO: NumberOfPhys=0

Unlike Intel RST drivers, the AMD driver does not properly report the attached drives in the PHY_INFO struct (the patch for CrystalDiskInfo sets all to attached).

Please repeat the `smartctl -r ioctl,2 --scan` test with r4951 from https://builds.smartmontools.org/. This version does not fix it, but prints more info.

> /dev/sda -d scsi # /dev/sda, SCSI device

Non-RAID devices may work via IOCTL_ATA_PASS_THROUGH as with IRST.
Please test `smartctl -d ata -i /dev/sda`.

You could also send the results via private mail (see AUTHORS or ChangeLog file).

**Comment by Shine-** [comment]
Output of `smartctl -r ioctl,2 --scan from` r4951 is exactly the same as for r4949.
`smartctl -d ata -i /dev/sda` works somehow, e.g. drive S/N is displayed properly. However, model and firmware version are as truncated as above and it insists that SMART support is available but disabled for the drive (even after using `--smart=on`).

**Comment by chrfranke** [comment]
AMD's CC_CSMI_SAS_GET_PHY_INFO apparently does not return anything useful. IOCTL_ATA_PASS_THROUGH is apparently not implemented for non-RAID devices. Looks like the long tradition of AMD driver's ATA pass-through functionality continues: either missing or incomplete or broken :-(

A heuristics to support this driver would need some experiments.  I currently don't have access to a machine for testing. Feel free to send me a PM if you are willing to test experimental builds.

**Comment by Shine-** [comment]
Couldn't find a PM function on GitHub...
Yes, I can test experimental builds, no problem.

**Comment by Shine-** [comment]
Might be helpful, I dumped the CSMI_SAS_PHY_INFO structure and compared to Intel (RSTe 4.6 in my case). The first 28 bytes are identical, then comes a 0 (where Intel shows the number of physical drives I assume):
`  0000  1c 00 00 00 43 53 4d 49 53 41 53 00 3c 00 00 00  ....CSMISAS.<...`
`  0010  14 00 00 00 00 00 00 00 04 08 00 00 00 00 00 00  ................`
The rest, till the end, is zeroed for AMD (where I assume Intel lists the info for each physical port).

**Comment by Shine-** [comment]
After removing a few sanity checks that will always fail with AMDs empty struct, I got it to work. See here:
https://github.com/Shine-/smartmontools/commit/d346016a1b47d57646659b981962ed78bb62d207
I'll add more drives to be able to test with a RAID1 or RAID0, too. Will take a few days, though, until I can free up the space.

**Comment by chrfranke** [comment]
Thanks. Here a version which keeps IRST support as is: [os_win32.cpp-amdraid.patch.txt](https://github.com/smartmontools/smartmontools/files/3674437/os_win32.cpp-amdraid.patch.txt)

For now, limited to 8 drives and "rcraid" drivers which actually return nothing. Might be incomplete as the CrystalDiskInfo patch suggests that the driver might return nonempty data under some circumstances (if RAID is activated?).

And (as expected ?-) the driver also does not return ATA output registers to the caller. This is also the case in various SAT Layers and USB-bridges. The problem affects SMART STATUS and SCT GET commands.

**Comment by Shine-** [comment]
Works as expected. Will report back what happens when using RAID.

**Comment by Shine-** [comment]
I tried with one single drive (same as above) plus a RAID1 array now. Suddenly CSMI_SAS_PHY_INFO does contain info: The (previously unlisted) single drive and the first drive from the RAID array. The second drive from the RAID array is not listed in CSMI_SAS_PHY_INFO.

Here's the relevant output:
`  IOCTL_SCSI_MINIPORT(CC_CSMI_20) succeeded, bytes returned: 2080`
`CSMI_SAS_PHY_INFO: NumberOfPhys=2`
`Phy[0] Port:   4`
`  Type:        0x10, 0x10`
`  InitProto:   0x01, 0x01`
`  TargetProto: 0x01, 0x01`
`  PortIdent:   0x04`
`  PhyIdent:    0x00, 0x00`
`  SignalClass: 0x00, 0x00`
`  Restricted:  0x00, 0x00`
`  SASAddress:  00 00 00 00 00 00 00 00, 00 00 00 00 00 00 00 00`
`Phy[1] Port:   5`
`  Type:        0x10, 0x10`
`  InitProto:   0x01, 0x01`
`  TargetProto: 0x01, 0x01`
`  PortIdent:   0x05`
`  PhyIdent:    0x01, 0x00`
`  SignalClass: 0x00, 0x00`
`  Restricted:  0x00, 0x00`
`  SASAddress:  00 00 00 00 00 00 00 00, 00 00 00 00 00 00 00 00`

`smartctl -a /dev/csmi0,4` returns the data from the non-RAID drive.
`smartctl -a /dev/csmi0,5` returns the data from the first drive in the RAID array.

Hex dump of CSMI_SAS_PHY_INFO:
`  0000  1c 00 00 00 43 53 4d 49 53 41 53 00 3c 00 00 00  ....CSMISAS.<...`
`  0010  14 00 00 00 00 00 00 00 04 08 00 00 02 00 00 00  ................`
`  0020  10 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00  ................`
`  0030  00 00 00 00 00 00 00 00 00 00 00 00 04 0a aa aa  ................`
`  0040  00 03 01 00 10 00 01 01 00 00 00 00 00 00 00 00  ................`
`  0050  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................`
`  0060  10 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00  ................`
`  0070  00 00 00 00 01 00 00 00 00 00 00 00 05 0a aa aa  ................`
`  0080  00 03 01 00 10 00 01 01 00 00 00 00 00 00 00 00  ................`
`  0090  [the rest is zeroes]`

With this strange behavior, neither my patch nor your patch is able to query data from the second drive in the array.

When removing the "nonempty" check (your patch) or the check for NumberOfPhys (my patch), all three drives can be read, though at port 0, 1 and 2 (`/dev/csmi0,0`, `/dev/csmi0,1` and `/dev/csmi0,2`, respectively), instead of 4, 5, ...

**Comment by chrfranke** [comment]
Thanks!  Looks like `CSMI_SAS_PHY_INFO.bNumberOfPhys` counts RAID drives only but the `Phy[]` array returns this number of drives regardless of RAID mode. The CSMI pass-through apparently uses `bPhyIdentifier` for addressing (IRST uses `bDestinationSASAddress[9]`).

> smartctl -a /dev/csmi0,4 returns the data from the non-RAID drive.
> smartctl -a /dev/csmi0,5 returns the data from the first drive in the RAID array

Do 4 and 5 match with the actual SATA port numbers on the board?

According to the CrystalDiskInfo patch, `CSMI_SAS_RAID_INFO.uMaxPhysicalDrives` (not used yet)  might return the (currently used or maximum supported?) number of physical drives. 

I will provide a new patch soon...

**Comment by Shine-** [comment]
> Do 4 and 5 match with the actual SATA port numbers on the board?

No, the drives are connected to SATA1 (single drive) and SATA3/4 (RAID array). My board has 4 SATA ports in total. I can try moving around the drives and see how the port number reported changes.

**Comment by Shine-** [comment]
I have to correct myself, the port numbers are correct indeed, just the driver's port numbering scheme seems different from the BIOS. For my board, it appears to be:
SATA1 -> Port0
SATA2 -> Port1
SATA3 -> Port4
SATA4 -> Port5
If I connect the non-RAID drive to the last port instead of the first, I can even query both drives from the RAID array (but not the non-RAID drive anymore).

**Comment by chrfranke** [comment]
Here a new patch which checks `CSMI_SAS_RAID_INFO.uMaxPhysicalDrives`, keeps known ports as is and guesses the others: [os_win32-amdraid-2.patch.txt](https://github.com/smartmontools/smartmontools/files/3714418/os_win32-amdraid-2.patch.txt) (yes, a possible final commit will have more comments...).

**Comment by Shine-** [comment]
Works, but port numbers are wrong.

If you go by port numbers, it **should** be:
single drive -> sata1 -> csmi0,0
first array member -> sata3 -> csmi0,4
second array member -> sata4 -> csmi0,5

However, it **is** currently:
csmi0,0 -> second array member
csmi0,4 -> single drive
csmi0,5 -> first array member

**Comment by chrfranke** [comment]
Looks like the values of PhyIdent addresses i'th used port but NumberOfPhys and PortIdent ignore single drives. The driver may return the result of something like this:

`uMaxPhysicalDrives = 16; // Some constant >= number of available ports`
`bNumberOfPhys = get_number_of_drives_but_forget_single_drives();`
`for (int i = 0; i < bNumberOfPhys; i++) {`
`  Phy[i].Identify.bPhyIdentifier = i; // Later used as address for pass-through`
`  Phy[i].bPortIdentifier = find_drive_port_number_but_forget_single_drives(i);`
`}`

So the bPortIdentifier values are only correct if no single drives precede raid members. For now, I keep the current heuristics as is and commit it soon.

**Comment by chrfranke** [comment]
Last patch committed with some modifications in https://www.smartmontools.org/changeset/4966.
A CI build is available at https://builds.smartmontools.org/.

I will add some improvements (more sane SMART STATUS message, device probe during open) later.

**Comment by Shine-** [comment]
Many thanks for your work!

One more thing, perhaps useful for the documentation:

The AMD driver apparently implements CSMI security without write access by default, so in order to be able to **change** any setting (e.g. write cache, AAM/APM, ...,), you'll have to first change the reg key

`[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\rcraid\Parameters\Device]`
`"DriverParameter"="CSMI=Limited;"`

to

`"DriverParameter"="CSMI=Full;"`

and reboot, otherwise you'll get an error "4" in smartctl.

**Comment by chrfranke** [comment]
A late followup:

> One more thing, perhaps useful for the documentation: ...

Thanks - Info about the registry entry is now on smartctl man page.

> SMART Status command still fails (see below). ...

Should now print a less verbose message.
