### ISSUE TITLE
Question regarding return value of smartctl

### ISSUE THREAD

**Issue by fonic** [smartmontools/smartmontools#45]
I have a question regarding the return value of `smartctl`.

Does it _always_ reflect the device's status or is that only the case when using `--health`? The man page is unclear about this.

In my specific use case, I need attributes and device health, preferably in a single run, but it remains unclear for me if the return value reflects the device's status when running `smartctl --attributes <device>`.

Sadly (or luckily), I have no broken device to test/verify.

**Comment by chrfranke** [comment]
Bit 3 of smartctl exit code is never set if `--health` option is not used.
