### ISSUE TITLE
Make "Data Units Written/Read" from TB to GB.

### ISSUE THREAD

**Issue by Slenkis** [smartmontools/smartmontools#46]
### Is it possible to make GB instead of TB in the output?
![smrtctl](https://user-images.githubusercontent.com/30866426/71643598-b6cc1500-2ccc-11ea-82c7-c7995699a5f9.png)

**Comment by chrfranke** [comment]
Please be more specific and explain why this should be changed.

Note that _NVM Express Revision 1.4_ says:
**Data Units Read:** Contains the number of 512 byte data units the host has read from the controller; ... This value is reported in thousands (i.e., a value of 1 corresponds to 1,000 units of 512 bytes read) and is rounded up (e.g., one indicates the that number of 512 byte data units read is from 1 to 1,000, three indicates that the number of 512 byte data units read is from 2,001 to 3,000). ...

**Comment by chrfranke** [comment]
Output is IMO correct, see above comment.

**Comment by Slenkis** [comment]
### If I manually want to translate from GB to TB, should I multiply by 1000 or by 1024?
Example: I have **2.27 TB**, I multiply by 1000 and get **2270 GB** _or_ I multiply by 1024 and get **2324,48 GB**. Which option will be right?

**Comment by chrfranke** [comment]
Smartctl uses factors 1000^i for KB, GB, TB, PB. Disk vendors do the same for device capacity. If factors 1024^i would be used, smartctl would print IEC prefixes KiB, GiB, TiB, PiB. See also https://en.wikipedia.org/wiki/Binary_prefix.

If you want GB of Data Units Read/Written, use `VALUE * 512 / 1000000`. Some examples using the "Read" value from the screenshot:
```
$ bc
...
scale=2
print 4011289*512*1000/(1000^3)," GB\n"
2053.77 GB
print 4011289*512*1000/(1024^3)," GiB\n"
1912.73 GiB
print 4011289*512*1000/(1000^4)," TB\n"
2.05 TB
print 4011289*512*1000/(1024^4)," TiB\n"
1.86 TiB
```
Note that `smartctl -j` or `smartctl --json=g` output is possibly easier to parse.
