### ISSUE TITLE
Crucial MX500 SSD return 1 pending sector intermittently (add --firmwarebug option?)

### ISSUE THREAD

**Issue by eLvErDe** [smartmontools/smartmontools#48]
Hello,

Here are the report I receive from three different machine (hardware is new):

```
Device: /dev/sdb [SAT], 1 Currently unreadable (pending) sectors

Device info:
CT250MX500SSD1, S/N:1931E21587D5, WWN:5-00a075-1e21587d5, FW:M3CR023, 250 GB
```

```
Device: /dev/sdb [SAT], 1 Currently unreadable (pending) sectors

Device info:
CT250MX500SSD1, S/N:1931E215B362, WWN:5-00a075-1e215b362, FW:M3CR023, 250 GB
```

```
Device: /dev/sdb [SAT], 1 Currently unreadable (pending) sectors

Device info:
CT500MX500SSD1, S/N:1934E21A7C80, WWN:5-00a075-1e21a7c80, FW:M3CR023, 500 GB
```

In this Trac ticket https://www.smartmontools.org/ticket/977 someone (from your team ?) stated that a --firmwarebug options could be added to workaround this.

All drive are running latest firwmare (from 2018 so I doubt it'll ever get fixed) and you can found plenty of similar report over Internet.

Thanks in advance,

Regards, Adam.

**Comment by chrfranke** [comment]
This has been addressed via a new drive database entry, see [ticket 1227](https://www.smartmontools.org/ticket/1227). Please upgrade to smartmontools 7.1 or update the drive database.
