### ISSUE TITLE
Why is a SCSI type hard disk recognized as sat 

### ISSUE THREAD

**Issue by dreamtale90** [smartmontools/smartmontools#60]
I'm going to get some hard disk information through smartctl, including the type of hard disk. I think it is a good idea get info from json data. But I found that the hard disk type information output with "-ji" option is not correct.
I have a scsi type disk. If I run smartctl with "--scan" option, I get the correct result:
`$ sudo ./smartctl --scan`
`/dev/sda -d scsi # /dev/sda, SCSI device`

But I run smartctl with "-ji" option, the device type is "sat":
`$ sudo ./smartctl -ji /dev/sda`
`{
    "json_format_version":[
        1,
        0
    ],
    "smartctl":{
        "version":[
            7,
            2
        ],
        "platform_info":"x86_64-linux-4.19.0-6-amd64",
        "build_info":"(local build)",
        "argv":[
            "smartctl",
            "-ji",
            "/dev/sda"
        ],
        "exit_status":0
    },
    "device":{
        "name":"/dev/sda",
        "info_name":"/dev/sda [SAT]",
        "type":"sat",
        "protocol":"ATA"
    },
.......
`

 why is that? Is there a problem with this

**Comment by chrfranke** [comment]
This is unrelated to JSON output. The `--scan` option only guesses the type without accessing the device itself. The accuracy is platform specific. Retry with `--scan-open`. This should detect SAT if the SCSI INQUIRY returns `ATA`.

**Comment by dreamtale90** [comment]
Aha, that's exactly what you said. Thank you very much. 
`$ sudo ./smartctl --scan-open`
`/dev/sda -d sat # /dev/sda [SAT], ATA device`
