### ISSUE TITLE
Add ConditionVirtualization=!container to the smartd.service file

### ISSUE THREAD

**Issue by lahwaacz** [smartmontools/smartmontools#62]
Currently you need 2 different configurations if you manage a system for bare-metal hardware and containers (e.g. for testing). The problem is that smartd fails if you have `DEVICESCAN` in the config and no disks are found (which is the case of containers). For these cases systemd offers the [ConditionVirtualization](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#ConditionVirtualization=) option which can be set to `!container` to avoid starting the service inside containers. I think this is a sensible default option for the upstream service file.

**Comment by chrfranke** [comment]
Makes plenty of sense.

**Comment by DigitalDJ** [comment]
I realize this issue is more than a year old, but I have come across this issue finding that smartmontools hasn't been running since an upgrade to Ubuntu 21.04 (where this change was first implemented in Ubuntu). Essentially a silent failure.

I think this change is a little short sighted considering it is possible to pass through PCIe HBAs to virtualized systems, and that is absolutely a valid, albeit niche, setup.

Cheers

**Comment by samm-git** [comment]
...another (still niche) setup is VM with USB drive attached. Something i am using when need to repair some drive from another system, e.g. via sata->usb adapter. Also not sure if containers should be disabled - one can always pass /dev/sd* to the guest and get at least some benefits of the virtualization.

**Comment by samm-git** [comment]
.. my proposal is to leave default as-is but add comment to the unit file about it. As it still very rare (but valid) cases.

**Comment by lahwaacz** [comment]
> I only say this because I strongly believe the failure should be loud and hard, not silent. Sysadmins everywhere will be pulling their hair out, wondering why smartd isn't starting, or.....shitting themselves realizing them their monitoring solution hasn't been doing its job. You can't expect someone to read a comment in a unit file, if they don't know something has silently failed.

What? smartd is not _failing silently_, the reason why it did not start up is clearly visible in the service status:
```
> systemctl status smartd.service
○ smartd.service - Self Monitoring and Reporting Technology (SMART) Daemon
     Loaded: loaded (/usr/lib/systemd/system/smartd.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/smartd.service.d
             └─override.conf
     Active: inactive (dead)
  Condition: start condition failed at Fri 2022-01-14 06:33:04 CET; 20s ago
             └─ ConditionVirtualization=no was not met
       Docs: man:smartd(8)
             man:smartd.conf(5)
```
This is where I'd expect everyone to start looking if they expected a different behavior. Also if you can't figure out that you're missing monitoring data because a service did not start up, then your monitoring solution really sucks.

> a) want smartd to FAIL if no disks are found. That's likely a significant red flag.

Wrong. Diskless systems are a thing and disks may be attached during the system runtime.

> b) not want smartd to /silently/ stop loading because of the environment they have setup

Wrong premise, it's not _silent_ (see above).

> In the case of testing your production environment in a container, your "testing" environment should accept smartd failing as a success!

systemd has no concept of an "accepted failure" for services.

**Comment by DigitalDJ** [comment]
I think you're missing the point. In the case of say, a distro upgrade, this would be a pretty darn silent and likely to fall under the radar, unless you specifically knew of the change. What makes it even more significant, is that it's literally piece of software for potentially detecting impending data loss.

For example, a quick pass `systemctl list-units --failed` would not show any issues. The unit hasn't failed. It's just now inactive. Even though the user has explicitly enabled the service with `systemctl enable smartmontools`, the service is not starting.

> Also if you can't figure out that you're missing monitoring data because a service did not start up, then your monitoring solution really sucks.

That's not wrong, but a lot of monitoring solutions notify on bad things happening, not necessarily the absence of bad things happening. Not to mention, systemd itself is not saying that the unit has failed, it just no longer starts. 

>  Wrong. Diskless systems are a thing and disks may be attached during the system runtime.

Yes, absolutely. Obviously an exaggeration.  

But as per the original issue description, aren't these diskless systems already being screwed by smartmontools exiting if no disks are detected with `DEVICESCAN` ? Would it not be preferable that if the user says smartmontools should be running (i.e. they ran `systemctl enable smartmontools`) then smartmontools should run and keep scanning for disks when they show up?

I struggling to understand what the original use-case is for this change....and no one has made that clear, so a lot of assumptions are made.

**Comment by samm-git** [comment]
Let me summarize quickly: 

1. In the most typical cases it is not expected that smartd/smartctl will be useful in the virtual environment. So there is a very little sense to have it automatically started when OS is installed in it.
2. There are valid but edge-case scenarios where it could be useful. Most typical - SCSI/USB/PCI pass-thru, may be some iSCSI controller, etc. These are valid but marginal cases which will require some customization anyway. 
3. If there is such case nothing prevents system administrator to add systemd override for such variable.  Systemd gives very clear explanation why service is not started, also automated check for unit could/should be added anyway. 
4. Containers are different (and irrelevant) story as systemd usually never used inside containers.
5. This unit file here is only for the reference, OS maker could/should modify it if its not relevant to the use-case. 

So i would like to leave things as is and just add comment line to the unit.

**Comment by samm-git** [comment]
Comment added as r5301

**Comment by chrfranke** [comment]
A different approach would be:
```diff
- ConditionVirtualization=no
...
- ExecStart=/usr/local/sbin/smartd -n $smartd_opts
+ ExecStart=/usr/local/sbin/smartd -n -q never $smartd_opts
```
Then smartd continues to run even if there are no devices. The `-q` option could still be overridden in `$smartd_opts`.

Note that `-q never` is already the default on recent Debian packages because the package maintainer decided to change the long standing default (`-q nodev`). See https://sources.debian.org/patches/smartmontools/7.2-1/default_never-quit.patch/. Recent Ubuntu packages inherited this change.

A possibly useful `smartd` enhancement would be a variant of the `-q nodev[startup]` options which allows to change the no-device exit status to 0, for example `-q nodev[startup],0`. Then this could be used:

```diff
...
+ ExecStart=/usr/local/sbin/smartd -n -q nodev,0 $smartd_opts
```

**Comment by DigitalDJ** [comment]
Thanks for the change. I'll leave it there, even if I'm a little disappointed something more isn't done.

> So there is a very little sense to have it automatically started when OS is installed in it.

I agree, but I believe distro maintainers already make a lot of these decisions in their installers. e.g. installing open-vm-tools for virtualization systems, etc.

> These are valid but marginal cases which will require some customization anyway.

Generally, the case of passthrough USB or SCSI devices doesn't require any change to smartmontools previously, now it does.

>  Systemd gives very clear explanation why service is not started, also automated check for unit could/should be added anyway.

Agree the systemd explanation is clear, but unfortunately not very visible unless specifically monitored for.

> Containers are different (and irrelevant) story as systemd usually never used inside containers.

I think this is another thing that should not be assumed. There has recently been a bit of push forward with Podman and RHEL to run systemd in containers, leveraging distro packages for startup daemons etc. I personally am definitely looking at and containerizing smartmontools.

> This unit file here is only for the reference, OS maker could/should modify it if its not relevant to the use-case.

Agree, and maybe I should head over to launchpad to get a little more traction. The main reason I originally opened was that I saw this change while playing with the development builds of Ubuntu 22.04 LTS.

Cheers

**Comment by lahwaacz** [comment]
> Containers are different (and irrelevant) story as systemd usually never used inside containers.

It depends on what you call a container. Typically, the term is not limited to the Docker or Podman things which start only isolated services, but includes also Linux Containers and systemd-nspawn which are often used to spawn a whole OS instance (of course, except for the kernel space which is shared with the host).

**Comment by samm-git** [comment]
> 
> > These are valid but marginal cases which will require some customization anyway.
> 
> Previously, the case of passthrough USB or SCSI devices didnt't require any change to smartmontools systemd unit, now it does. No other custom configuration of smartd was necessary for passthrough devices in virtualized environments.
You dont need to change the unit, you can just override this specific setting (i think thats what `systemctl --edit` does by default). What to me seems to be very low effort. Much lower compared to USB pass-through.

> > Systemd gives very clear explanation why service is not started, also automated check for unit could/should be added anyway.
> 
> Agree the systemd explanation is clear, but unfortunately not very visible unless specifically monitored for.
One should always check if smartd is stated and doing something useful. Or there is very little sense having it at all :)
> 
> > Containers are different (and irrelevant) story as systemd usually never used inside containers.
> 
> I think this is another thing that should not be assumed. There has recently been a bit of push forward with Podman and RHEL to run systemd in containers, leveraging distro packages for startup daemons etc. I personally am definitely looking at containerizing smartmontools.

Systemd inside containers is likely a very bad idea. Usually you dont need any kind of init inside. Smartmontools containerization could be useful (usually - not), but in this case you will place unit to run container on the host and having container ONLY to run smartd/smartctl, its unlikely that you will need 2nd instance of systemd to do it :)

**Comment by samm-git** [comment]
@chrfranke not sure that having it running by default in vm is a good idea. In 99% of the cases it will be just one more process without any real use. Also some of the VM-s (virtualbox with some settings) emulating very basic "smart support", probably to make some OS happy, so smartd will run here and "monitor" this faked devices. IMO this was the intention to add this line initially.

**Comment by samm-git** [comment]
@lahwaacz may be its different with namespaces v2, but in the past running systemd inside containers was not working well at all, due to cgroups/namespaces collisions and it was not recommended/supported. May be things changed, i was not tracking that.

**Comment by DigitalDJ** [comment]
> You dont need to change the unit, you can just override this specific setting (i think thats what `systemctl --edit` does by default). What to me seems to be very low effort. Much lower compared to USB/PCI pass-through.

I understand it's low effort, but it is now a change that has to be made, rather than previously not. The main issue I have wasn't about having to configure the unit, it was about people upgrading and not realizing they have to now configure the unit, because systemd won't list the service as failed explicitly.

> not sure that having it running by default in vm is a good idea

I agree in principle, but maybe smartd should always check if there's a disk to monitor, and if not, then decide what to do from there.

> Systemd inside containers is likely a very bad idea.

This is subjective. There's numerous benefits to it, but also disadvantages too. Again, assuming things about the environment the daemon will run in.

**Comment by lahwaacz** [comment]
> it was about people upgrading and not realizing they have to now configure the unit, because systemd won't list the service as failed explicitly.

The change was [documented properly](https://github.com/smartmontools/smartmontools/blob/7369f7f2a0280ec71279b78e23f3041ce2844e06/smartmontools/ChangeLog#L775-L778). `systemctl list-units --failed` etc. is not a substitute for reading the release notes.

**Comment by DigitalDJ** [comment]
Respectfully, I'm aware it's documented, but it is unreasonable to expect users will generally read release notes for every package upgraded in a distro upgrade.

**Comment by chrfranke** [comment]
New smartmontools 7.3 allows:
```
ExecStart=/usr/local/sbin/smartd -n -q nodev0 $smartd_opts
```
This is like the default `-q nodev`, except that the exit status is 0 instead of 17 if there are no devices. The service should be no longer reported as failed then. `"No devices to monitor"` is reported via `sd_notify()` if configured.
The `-q` option could be overriden via `$smartd_opts`.
