### ISSUE TITLE
Accumlated power on time show with no option selected.

### ISSUE THREAD

**Issue by SimonFair** [smartmontools/smartmontools#65]
smartctl   /dev/sdd
smartctl 7.2 2020-09-19 r5083 [x86_64-linux-5.7.8-Unraid] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

Accumulated power on time, hours:minutes 36535:57

Also appears with -i

**Comment by chrfranke** [comment]
See PR #66.
