### ISSUE TITLE
Change comma separator for csmi devices [Question]

### ISSUE THREAD

**Issue by rootbdfy** [smartmontools/smartmontools#8]
Hello.
It's not an issue, just question.
May someone help me to change separator for csmi devices ?
E.g. in zabbix I cant use parameters with comma.
If change /dev/csmi0,3 to /dev/csmi0.3 it would be better.

**Comment by samm-git** [comment]
Hi, no we are using comma for most of our devides. For  questions i would suggest to use project mailing list (see smartmontools.org website)
