### ISSUE TITLE
Running smartctl inside a Docker without -privileged

### ISSUE THREAD

**Issue by aschaepper** [smartmontools/smartmontools#88]
Hello together

I hope im allowed to ask this here:
I'm trying to run smartctl inside a docker container, but if possible without the -privileged option.
So for example this works:

$ sudo docker container run -it --rm -privileged --name test testimage bash

I can then install smartmontools inside in and call smartctl with:
$ smartctl --all /dev/sda

But if possible I would like to avoid the -priviliged flag when running the container.
I read into it and I found that there are possibilities to map stuff into the container in a more finegrained manner like this (avoiding -priviliged):

$ sudo docker container run --rm --device=/dev/sda:rw --device=/dev/bus/usb/001 --device=/dev/bus/usb/002 --name test testimage

But this didn't work, maybe you know more about the implementation details of smartmontools and can help me, how I could achieve this. I know it's open source and I could look into it myself but It would definitly take me forever and im not sure if I'm even skilled enough.

For your information, I used this call inside the docker:
$ smartctl --all /dev/sda -d ata -T permissive
and 
$ smartctl --all /dev/sda -d sat -T permissive

If you have any idea how I could get smartctl to work inside a docker container I would appreciate it!

**Comment by PrplHaz4** [comment]
From this project: https://github.com/AnalogJ/scrutiny it looks like you need `--cap-add SYS_RAWIO` along with passing the devices.

**Comment by aschaepper** [comment]
Youre a genius! Thank you very much I just tested it and it worked!

**Comment by samm-git** [comment]
Closing as it is not a smartmontools issue and answer is already provided. P.S. i do not see a lot of benefits running it this way.

**Comment by aschaepper** [comment]
F.Y.I
As far as I could find out, running docker with the -priviliged flag poses a security risk and should be avoided. So this is the reason why I wanted to have only the most necessary capabilities added to the running container.

**Comment by samm-git** [comment]
@aschaepper my point is that you are providing direct access to the storage devices, so any kind of isolation with such type of access does not help a lot.

**Comment by aschaepper** [comment]
@samm-git
Now I understand what you mean. The background here is that we are building a microsoft iot edge based device, the builtin automatic deployment mechanism for software components of this "azure iot edge stack" is based on docker containers.
If we want to deliver software from the cloud service to the headless device, we have to build it with containers (so all the automatic update works as well)
But now as you say it even providing this single capability could be a security risk.

Thanks a lot for raising the concerns, and give insight!
