### ISSUE TITLE
[question] how it works?

### ISSUE THREAD

**Issue by gg187on** [smartmontools/smartmontools#94]
Hello, I'm writting Diploma and I need to know how this work, but I'm confused after reading source code, and https://www.smartmontools.org/static/doxygen/ don't help me too. Can someone simply explain how are S.M.A.R.T data gathered from disk?

**Comment by chrfranke** [comment]
ATA SMART data is read via ATA command SMART READ DATA. See for example "T13/2161-D - ATA/ATAPI Command Set - 3 (ACS-3)" from https://www.t13.org/. For more info, you need to ask more specific questions.

**Comment by gg187on** [comment]
thanks so much,... that PDF document (https://people.freebsd.org/~imp/asiabsdcon2015/works/d2161r5-ATAATAPI_Command_Set_-_3.pdf) from t13.org is really good.
