### ISSUE TITLE
Cannot see more than 24 drives under linux

### ISSUE THREAD

**Issue by rjsears** [smartmontools/smartmontools#95]
I have about 150 drives mounted on my Linux NAS and I was quite surprised when one started failing but was not reported by smartd. When I started digging into the logs I noticed that it only shows up to /dev/sdx.

Is this an intentional limitation or do I have something misconfigured in /etc/smartd.conf?

Thanks

**Comment by chrfranke** [comment]
Under Linux, `DEVICESCAN` does not support 150 devices but `/dev/sd[a-z]` and `/dev/sd[a-c][a-z]` (104 devices) should be included.

Please provide version information (`smartctl -V` output) and contents of `smartd.conf` file.
Please try: `smartctl --scan` and `smartctl --scan-open`.

**Comment by chrfranke** [comment]
> ... but in /var/log/syslog, this is the output:

This output only shows that the self-tests are not run for most devices. This might have several reasons: devices not included in scan, no pass-through support, no self-test support (e.g. NVMe), ...

Please run `smartd -q onecheck > onecheck.txt` and provide `onecheck.txt` as an attachment.

**Comment by rjsears** [comment]
[onecheck.txt](https://github.com/smartmontools/smartmontools/files/6469782/onecheck.txt)

Here it is....

**Comment by chrfranke** [comment]
```
$ egrep 'S/N|Monitoring|state written' onecheck.txt
Device: /dev/sdb [SAT], OOS12000G, S/N:00000000, WWN:5-000c50-0b01a23f0, FW:OOS1, 12.0 TB
Device: /dev/sdc [SAT], OOS12000G, S/N:00000000, WWN:5-000c50-0b015c512, FW:OOS1, 12.0 TB
...
Device: /dev/sdz [SAT], OOS12000G, S/N:00000000, WWN:5-000c50-0c3a6dfc7, FW:OOS1, 12.0 TB
Device: /dev/sdaa [SAT], OOS12000G, S/N:00000000, WWN:5-000c50-0c329a6ca, FW:OOS1, 12.0 TB
...
Device: /dev/sdas [SAT], OOS12000G, S/N:00000000, WWN:5-000c50-0b58ac54c, FW:OOS1, 12.0 TB
Device: /dev/sdat, [HGST     HUH721010AL4200  A384], lu id: 0x5000cca256770404, S/N: 7GJ3G2RK, 10.0 TB
...
Device: /dev/sdbc, [HGST     HUH721010AL4200  A384], lu id: 0x5000cca2567bef6c, S/N: 7GJ64YTK, 10.0 TB
Device: /dev/bus/0 [megaraid_disk_04], [HITACHI  HUSMM114 CLAR400 C252], lu id: 0x5000cca04eb133e0, S/N: 0QY4G3GA, 400 GB
Device: /dev/bus/0 [megaraid_disk_05], [HITACHI  HUSMM114 CLAR400 C252], lu id: 0x5000cca04e73a158, S/N: 0QX1LBGA, 400 GB
Device: /dev/nvme0, 7335943:ICDPC5ED2ORA6.4T, S/N:PHLE738400PH6P4BGN-1, FW:QDV1RF30, 3.20 TB
Device: /dev/nvme1, 7335943:ICDPC5ED2ORA6.4T, S/N:PHLE738400PH6P4BGN-2, FW:QDV1RF30, 3.20 TB
Monitoring 44 ATA/SATA, 12 SCSI/SAS and 2 NVMe devices
Device: /dev/sdb [SAT], state written to /var/lib/smartmontools/smartd.OOS12000G-00000000.ata.state
...
Device: /dev/sdas [SAT], state written to /var/lib/smartmontools/smartd.OOS12000G-00000000.ata.state
Device: /dev/sdat, state written to /var/lib/smartmontools/smartd.HGST-HUH721010AL4200-7GJ3G2RK.scsi.state
...
Device: /dev/sdbc, state written to /var/lib/smartmontools/smartd.HGST-HUH721010AL4200-7GJ64YTK.scsi.state
Device: /dev/bus/0 [megaraid_disk_04], state written to /var/lib/smartmontools/smartd.HITACHI-HUSMM114_CLAR400-0QY4G3GA.scsi.state
Device: /dev/bus/0 [megaraid_disk_05], state written to /var/lib/smartmontools/smartd.HITACHI-HUSMM114_CLAR400-0QX1LBGA.scsi.state
Device: /dev/nvme0, state written to /var/lib/smartmontools/smartd.7335943_ICDPC5ED2ORA6_4T-PHLE738400PH6P4BGN_1.nvme.state
Device: /dev/nvme1, state written to /var/lib/smartmontools/smartd.7335943_ICDPC5ED2ORA6_4T-PHLE738400PH6P4BGN_2.nvme.state
```
The line `"Monitoring 44 ATA/SATA, 12 SCSI/SAS and 2 NVMe devices"` does nether match with the topic _"Cannot see more than 24 drives ..."_ nor with _"I have about 150 drives ..."_. If there are more drives, these might be connected to a (RAID) controller not supported by smartmontools or not included in `DEVICESCAN`.

One problem is that all `OOS12000G` devices use the same fake serial number `00000000`. This violates ATA standards since ATA-3 (1997): _The combination of Serial number (words 10..19) and Model number (words 27..46) shall be unique for a given manufacturer._ As a consequence, smartd uses the same state file `smartd.OOS12000G-00000000.ata.state` for all of these devices. This produces misleading results as the last state of the last device `/dev/sdas` is read for all `OOS12000G` devices if smartd restarts.

The WWN is not used in the filename because it is not always available (added as optional in ATA-7, mandatory since ATA-8 ACS, in practice occasionally missing or set to all zeroes).

State persistence cannot be used with these devices. Create a custom init script or systemd service file which adds `-s ''` (empty string as argument to `-s`) to the smartd command line or rebuild smartd without the `--with-savestates` option. See `-s` option on `man smartd` for details.

**Comment by rjsears** [comment]
These drives are not connected to a raid controller, they are connected to an LSI 9300 in jbod mode. As to the drive serial numbers, I am not the drive manufacturer, these are all brand new Seagate hard drives. Also, per the Syslog, only 24 of the drives on the system are being monitored, hence the "cannot see more than 24 drives" comment. To further troubleshoot the problem, I disconnected all of my external enclosures to lower the number of drives on the system to see if anymore would show up in Syslog, but no more did.

Are you saying that I just need to start smartd with the `-s` option to fix this issue?

**Comment by chrfranke** [comment]
> These drives are not connected to a raid controller, they are connected to an LSI 9300 in jbod mode. 

Are _these drives_ behind `/dev/sdb` to `/dev/sdas` ?

> As to the drive serial numbers, I am not the drive manufacturer, these are all brand new Seagate hard drives. 

You might want to complain about this obvious ATA violation to your drive vendor.

> Also, per the Syslog, only 24 of the drives on the system are being monitored, hence the "cannot see more than 24 drives" 

This observation does not match the `smartd -q onecheck` output you provided. It shows 44+12+2 = 58 devices. Please restart smartd on the system, then search for the most recent syslog entry matching the grep pattern `'Monitoring.*devices'` and report the result here.

> Are you saying that I just need to start smartd with the `-s` option to fix this issue?

No, `-s` has no effect on device scanning itself. Starting smartd with `-s ''` would prevent negative effects from the identical serial numbers. One of the effects could be that self-tests are not run for all drives.

**Comment by chrfranke** [comment]
Above results do not match the topic "_Cannot_ see more than 24 drives ..._". No further feedback from reporter.
