### ISSUE TITLE
"smartctl -j -i <disk>' does not report whether SMART is supported

### ISSUE THREAD

**Issue by MrPippin66** [smartmontools/smartmontools#96]
smartmontools = smartmontools-7.1-1.el8.x86_64

If I run "smartctl -i <disk>", I get the SMART status listed in the output.

`smartctl 7.1 2020-04-05 r5049 [x86_64-linux-4.18.0-240.15.1.el8_3.x86_64] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               VMware
Product:              Virtual disk
Revision:             2.0
Compliance:           SPC-4
User Capacity:        53,687,091,200 bytes [53.6 GB]
Logical block size:   512 bytes
LU is fully provisioned
Device type:          disk
Local Time is:        Tue Jun  1 08:26:57 2021 CDT
SMART support is:     Unavailable - device lacks SMART capability.
`

But if I include the JSON format option, the SMART status isn't included.

`{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      1
    ],
    "svn_revision": "5049",
    "platform_info": "x86_64-linux-4.18.0-240.15.1.el8_3.x86_64",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-ji",
      "/dev/sda"
    ],
    "exit_status": 0
  },
  "device": {
    "name": "/dev/sda",
    "info_name": "/dev/sda",
    "type": "scsi",
    "protocol": "SCSI"
  },
  "vendor": "VMware",
  "product": "Virtual disk",
  "model_name": "VMware Virtual disk",
  "revision": "2.0",
  "scsi_version": "SPC-4",
  "user_capacity": {
    "blocks": 104857600,
    "bytes": 53687091200
  },
  "logical_block_size": 512,
  "rotation_rate": 0,
  "device_type": {
    "scsi_value": 0,
    "name": "disk"
  },
  "local_time": {
    "time_t": 1622554025,
    "asctime": "Tue Jun  1 08:27:05 2021 CDT"
  }
}
`

**Comment by chrfranke** [comment]
```
SMART support is: Unavailable - device lacks SMART capability.
```
The above is not _SMART status_ information, but _SMART support_ information. This is actually missing in JSON output of this version of smartctl. Changeset [r5217](https://www.smartmontools.org/changeset/5217) added this for SCSI. It will be added for ATA.

To read _SMART status_ information, `-H` is required:
```
# smartctl -j -i -H ...
...
"smart_status": {
    "passed": true
}
````
If `-H` is specified and the above output is missing, SMART is not supported.

Note:
```
Vendor: VMware
Product: Virtual disk
```
Such virtual disks never support (or emulate) SMART.

**Comment by MrPippin66** [comment]
Apologies. I meant the SMART support information. Thanks for the information for this being added for SCSI. Any idea when this will include SATA as well?

**Comment by chrfranke** [comment]
Added for (S)ATA and NVMe in [r5218](https://www.smartmontools.org/changeset/5218) (1151fb1).
