### ISSUE TITLE
Intel SSD behind LSI MegaRAID adapter shows failed via "smartctl" command

### ISSUE THREAD

**Issue by MrPippin66** [smartmontools/smartmontools#98]
Environment: RHEL V7.8

smartmontools = smartmontools-7.0-2.el7.x86_64

smartctl = 7.0 2018-12-30 r4883

When running "smartctl" to get current S.M.A.R.T. status for an Intel SSD (Lenovo server), I get a failed status for the drive smart check (via RC) despite status showing OK in text of message (other than the one warning message).

--

# smartctl -iH /dev/bus/0 -d megaraid,0
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-3.10.0-1127.19.1.el7.x86_64] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     SSDSC2KG240G8L       01PE336D7A09684LEN
Serial Number:    BTYG84420724240AGN
LU WWN Device Id: 5 5cd2e4 1500d2880
Firmware Version: XCV1LX41
User Capacity:    240,057,409,536 bytes [240 GB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    Solid State Device
Form Factor:      2.5 inches
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ACS-3 T13/2161-D revision 5
SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Mon Jun 21 09:57:07 2021 CDT
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART Status not supported: ATA return descriptor not supported by controller firmware
SMART overall-health self-assessment test result: PASSED
Warning: This result is based on an Attribute check.

# echo $?
4

--

Software support is stating because this drive is not in the drivedb.h list, this is essentially working-as-designed.

I'm not sure if that's an accurate statement, and wanted to see if any further details could be added, here.

**Comment by chrfranke** [comment]
Status 4 (man smartctl: _Bit 2: Some SMART or other ATA command to the disk failed, ..._) is because of this limitation (bug) the MegaRAID SAT layer:
> SMART Status not supported: ATA return descriptor not supported by controller firmware

A failing SMART STATUS is not reported (man smartctl: _Bit 3: SMART status check returned "DISK FAILING"_):
> SMART overall-health self-assessment test result: PASSED
> Warning: This result is based on an Attribute check.

Related or duplicate: [ticket #1441](https://www.smartmontools.org/ticket/1441).

**Comment by chrfranke** [comment]
Fixed, see [ticket #1441](https://www.smartmontools.org/ticket/1441).
